export default [
	[
		'Inf. present: be',
		'I want to be a doctor.',
		'Quiero ser médico.',
		'Inf. present: is',
		'She is very smart.',
		'Ella es muy inteligente.',
		'Past tense: was/were',
		'I was at the store yesterday.',
		'Ayer estuve en la tienda.',
		'Past participle: been',
		'She has been to Paris twice.',
		'Ella ha estado en París dos veces.',
		'Gerund: being',
		'Being happy is important.',
		'Ser feliz es importante.',
	],
	[
		'Inf. present: beat',
		'She can beat anyone at chess.',
		'Ella puede vencer a cualquiera en ajedrez.',
		'Inf. present: beats',
		'He beats the drum loudly.',
		'Él golpea el tambor fuerte.',
		'Past tense: beat',
		'They beat the other team 5-0.',
		'Vencieron al otro equipo 5-0.',
		'Past participle: beaten',
		'I have never been beaten at that game.',
		'Nunca he sido vencido en ese juego.',
		'Gerund: beating',
		'He is beating the eggs for the omelette.',
		'Está batiendo los huevos para la tortilla.',
	],
	[
		'Inf. present: bear',
		'I cannot bear the heat.',
		'No puedo soportar el calor.',
		'Inf. present: bears',
		'The tree bears fruit every year.',
		'El árbol da frutos todos los años.',
		'Past tense: bore',
		'She bore the pain bravely.',
		'Ella soportó el dolor valientemente.',
		'Past participle: borne/born',
		'The burden has been borne by her.',
		'La carga ha sido soportada por ella.',
		'Gerund: bearing',
		'He is bearing the responsibility well.',
		'Él está llevando la responsabilidad bien.',
	],
	[
		'Inf. present: become',
		'I want to become a doctor.',
		'Quiero ser doctor.',
		'Inf. present: becomes',
		"He becomes very quiet when he's nervous.",
		'Se pone muy callado cuando está nervioso.',
		'Past tense: became',
		'She became a manager last year.',
		'Se convirtió en gerente el año pasado.',
		'Past participle: become',
		'He has become a successful businessman.',
		'Se ha convertido en un empresario exitoso.',
		'Gerund: becoming',
		'Becoming a lawyer takes many years of study.',
		'Ser abogado requiere muchos años de estudio.',
	],
	[
		'Inf. present: begin',
		"Let's begin the meeting.",
		'Empecemos la reunión.',
		'Inf. present: begins',
		'She always begins her day with a cup of coffee.',
		'Ella siempre comienza su día con una taza de café.',
		'Past tense: began',
		'He began his career as a teacher.',
		'Comenzó su carrera como profesor.',
		'Past participle: begun',
		'They have already begun the project.',
		'Ya han empezado el proyecto.',
		'Gerund: beginning',
		'Beginning a new job can be challenging.',
		'Empezar un trabajo nuevo puede ser un reto.',
	],
	[
		'Inf. present: bend',
		'He likes to bend the rules.',
		'Le gusta torcer las reglas.',
		'Inf. present: bends',
		'The tree bends in the wind.',
		'El árbol se dobla con el viento.',
		'Past tense: bent',
		'She bent down to pick up the pen.',
		'Se agachó para recoger la pluma.',
		'Past participle: bent',
		'The wire is bent out of shape.',
		'El alambre está doblado fuera de forma.',
		'Gerund: bending',
		'Bending over for long periods can be hard on your back.',
		'Agacharse por largos periodos puede ser duro para la espalda.',
	],
	[
		'Inf. present: bet',
		'I always bet on the red team to win.',
		'Siempre apuesto por el equipo rojo para ganar.',
		'Inf. present: bets',
		'She usually bets on the favorite horse.',
		'Ella normalmente apuesta por el caballo favorito.',
		'Past tense: bet',
		'He bet all his money on the roulette.',
		'Apostó todo su dinero en la ruleta.',
		'Past participle: bet',
		'I have never bet on a boxing match before.',
		'Nunca he apostado en una pelea de boxeo antes.',
		'Gerund: betting',
		'They are addicted to betting on sports.',
		'Están adictos a apostar en deportes.',
	],
	[
		'Inf. present: bleed',
		'The wound is bleeding a lot.',
		'La herida está sangrando mucho.',
		'Inf. present: bleeds',
		'He always bleeds after he shaves.',
		'Siempre sangra después de afeitarse.',
		'Past tense: bled',
		'She bled for hours before they found her.',
		'Sangró durante horas antes de que la encontraran.',
		'Past participle: bled',
		'The bandage is soaked with blood from the wound.',
		'La venda está empapada de sangre de la herida.',
		'Gerund: bleeding',
		"I'm sorry, but your dog is bleeding internally.",
		'Lo siento, pero tu perro está sangrando internamente.',
	],
	[
		'Inf. present: blow',
		'The wind is blowing really hard today.',
		'El viento está soplando muy fuerte hoy.',
		'Inf. present: blows',
		'She blows bubbles with her chewing gum.',
		'Ella hace burbujas con su chicle.',
		'Past tense: blew',
		'He blew the candles on his birthday cake.',
		'Sopló las velas en su pastel de cumpleaños.',
		'Past participle: blown',
		'The fuse has blown again.',
		'El fusible ha saltado de nuevo.',
		'Gerund: blowing',
		'The leaves are blowing away in the wind.',
		'Las hojas se están llevando el viento.',
	],
	[
		'Inf. present: breed',
		'Many people breed dogs as a hobby.',
		'Muchas personas crían perros como hobby.',
		'Inf. present: breeds',
		'This type of cat breeds well in cold weather.',
		'Este tipo de gato se reproduce bien en clima frío.',
		'Past tense: bred',
		'She bred horses for racing.',
		'Ella criaba caballos para carreras.',
		'Past participle: bred',
		'The farm has bred sheep for generations.',
		'La granja ha criado ovejas durante generaciones.',
		'Gerund: breeding',
		'The breeding of endangered animals is an important conservation effort.',
		'La cría de animales en peligro de extinción es un importante esfuerzo de conservación.',
	],
	[
		'Inf. present: break',
		'He wants to break the record for the 100 meter dash.',
		'Quiere romper el récord para los 100 metros planos.',
		'Inf. present: breaks',
		'The storm will break the branches on the trees.',
		'La tormenta romperá las ramas de los árboles.',
		'Past tense: broke',
		'She broke her leg while skiing.',
		'Se rompió la pierna mientras esquiaba.',
		'Past participle: broken',
		'The vase was broken when it fell off the table.',
		'El jarrón se rompió cuando se cayó de la mesa.',
		'Gerund: breaking',
		'The breaking of the sound barrier was a major milestone in aviation history.',
		'La ruptura de la barrera del sonido fue un hito importante en la historia de la aviación.',
	],
	[
		'Inf. present: bring',
		'Can you bring me a glass of water, please?',
		'¿Me puedes traer un vaso de agua, por favor?',
		'Inf. present: brings',
		'The new manager brings a fresh perspective to the company.',
		'El nuevo gerente trae una perspectiva fresca a la empresa.',
		'Past tense: brought',
		'He brought his girlfriend to the party last night.',
		'Anoche trajo a su novia a la fiesta.',
		'Past participle: brought',
		'I have brought a gift for the host of the party.',
		'He traído un regalo para el anfitrión de la fiesta.',
		'Gerund: bringing',
		'Bringing a water bottle to class is a good idea.',
		'Traer una botella de agua a clase es una buena idea.',
	],
	[
		'Inf. present: build',
		'I want to build a house someday.',
		'Quiero construir una casa algún día.',
		'Inf. present: builds',
		'The company builds high-quality products.',
		'La compañía fabrica productos de alta calidad.',
		'Past tense: built',
		"He built a birdhouse for his daughter's birthday.",
		'Construyó una casita para pájaros para el cumpleaños de su hija.',
		'Past participle: built',
		'They have built several houses in this neighborhood.',
		'Han construido varias casas en este vecindario.',
		'Gerund: building',
		'We are currently building a new office building.',
		'Actualmente estamos construyendo un nuevo edificio de oficinas.',
	],
	[
		'Inf. present: burn',
		'The firewood burns quickly.',
		'La leña quema rápidamente.',
		'Inf. present: burns',
		'The candle burns brightly in the dark.',
		'La vela arde brillantemente en la oscuridad.',
		'Past tense: burned / burnt',
		'The toast burned because I left it in the toaster too long.',
		'El pan tostado se quemó porque lo dejé en la tostadora demasiado tiempo.',
		'Past participle: burned / burnt',
		'The forest was burned down by a wildfire.',
		'El bosque fue arrasado por un incendio forestal.',
		'Gerund: burning',
		'I could smell the burning rubber from the car accident.',
		'Podía oler el olor a goma quemada del accidente de coche.',
	],
	[
		'Inf. present: buy',
		'I need to buy groceries for the week.',
		'Necesito comprar alimentos para la semana.',
		'Inf. present: buys',
		'She buys all her clothes online.',
		'Ella compra toda su ropa en línea.',
		'Past tense: bought',
		'He bought a new car last month.',
		'Compró un coche nuevo el mes pasado.',
		'Past participle: bought',
		'I have never bought anything from that store before.',
		'Nunca he comprado nada en esa tienda antes.',
		'Gerund: buying',
		'They enjoy buying antiques at the flea market.',
		'Disfrutan comprando antigüedades en el mercado de pulgas.',
	],
	[
		'Inf. present: cast',
		'I want to cast a spell on you.',
		'Quiero lanzarte un hechizo.',
		'Inf. present: casts',
		'He casts a shadow on the wall.',
		'Él proyecta una sombra en la pared.',
		'Past tense: cast',
		'She cast her vote in the election.',
		'Ella emitió su voto en las elecciones.',
		'Past participle: cast',
		'They have cast the actors for the play.',
		'Han elegido a los actores para la obra.',
		'Gerund: casting',
		'He enjoys casting his fishing line into the river.',
		'Disfruta lanzando su línea de pesca al río.',
	],
	[
		'Inf. present: catch',
		'Can you catch the ball?',
		'¿Puedes atrapar la pelota?',
		'Inf. present: catches',
		'She catches the bus every morning.',
		'Ella toma el autobús todas las mañanas.',
		'Past tense: caught',
		'He caught a cold last week.',
		'Él se resfrió la semana pasada.',
		'Past participle: caught',
		'Have you ever caught a fish?',
		'¿Alguna vez has atrapado un pez?',
		'Gerund: catching',
		'Catching a fly with chopsticks is not easy.',
		'Atrapar una mosca con palillos no es fácil.',
	],
	[
		'Inf. present: choose',
		'I need to choose a new outfit for the party.',
		'Necesito elegir un nuevo atuendo para la fiesta.',
		'Inf. present: chooses',
		'She always chooses the healthiest option on the menu.',
		'Siempre elige la opción más saludable del menú.',
		'Past tense: chose',
		'We chose to take the scenic route.',
		'Elegimos tomar la ruta panorámica.',
		'Past participle: chosen',
		'Have you ever chosen a career path?',
		'¿Alguna vez has elegido un camino profesional?',
		'Gerund: choosing',
		'Choosing a college can be a difficult decision.',
		'Elegir una universidad puede ser una decisión difícil.',
	],
	[
		'Inf. present: come',
		'I come to this café every morning.',
		'Vengo a este café todas las mañanas.',
		'Inf. present: comes',
		'He never comes to the office on time.',
		'Nunca llega a la oficina a tiempo.',
		'Past tense: came',
		'She came to my party last weekend.',
		'Vino a mi fiesta el fin de semana pasado.',
		'Past participle: come',
		'Have you ever come to this city before?',
		'¿Has venido alguna vez a esta ciudad antes?',
		'Gerund: coming',
		'The train is coming, so we need to hurry.',
		'El tren está llegando, así que necesitamos apurarnos.',
	],
	[
		'Inf. present: cost',
		'This shirt costs $20.',
		'Esta camisa cuesta $20.',
		'Inf. present: costs',
		'Healthy food usually costs more than junk food.',
		'La comida saludable suele ser más cara que la comida chatarra.',
		'Past tense: cost',
		'How much did your phone cost?',
		'¿Cuánto te costó tu teléfono?',
		'Past participle: cost',
		'The damage caused by the storm will cost millions of dollars to repair.',
		'Los daños causados por la tormenta costarán millones de dólares para reparar.',
		'Gerund: costing',
		'The project is costing us more money than we expected.',
		'El proyecto nos está costando más dinero de lo que esperábamos.',
	],
	[
		'Inf. present: dig',
		'I need to dig a hole for the new plant.',
		'Necesito cavar un hoyo para la nueva planta.',
		'Inf. present: digs',
		'The dog digs holes in the backyard.',
		'El perro cava hoyos en el patio trasero.',
		'Past tense: dug',
		'We dug a trench for the new sprinkler system.',
		'Cavamos una zanja para el nuevo sistema de riego.',
		'Past participle: dug',
		'Have you ever dug for buried treasure?',
		'¿Alguna vez has excavado en busca de un tesoro enterrado?',
		'Gerund: digging',
		'Digging in the garden is a great way to relieve stress.',
		'Cavar en el jardín es una excelente manera de aliviar el estrés.',
	],
	[
		'Inf. present: dive',
		'He likes to dive off the high diving board.',
		'Le gusta zambullirse desde el trampolín alto.',
		'Inf. present: dives',
		'She dives into the pool with a cannonball.',
		'Ella se tira a la piscina con un bombazo.',
		'Past tense: dove/dived',
		'He dove off the diving board and did a flip.',
		'Se zambulló desde el trampolín y dio una voltereta.',
		'Past participle: dived',
		'Have you ever dived with sharks?',
		'¿Alguna vez has buceado con tiburones?',
		'Gerund: diving',
		'Diving is a great way to explore the underwater world.',
		'Bucear es una excelente manera de explorar el mundo submarino.',
	],
	[
		'Inf. present: do',
		'I need to do my homework before I go out.',
		'Necesito hacer mi tarea antes de salir.',
		'Inf. present: does',
		'She always does her best on tests.',
		'Siempre da lo mejor de sí en los exámenes.',
		'Past tense: did',
		'He did a great job on the project.',
		'Hizo un gran trabajo en el proyecto.',
		'Past participle: done',
		'I have already done my laundry for the week.',
		'Ya he hecho mi ropa sucia de la semana.',
		'Gerund: doing',
		'Doing your best is all that matters.',
		'Dar lo mejor de ti es lo que importa.',
	],
	[
		'Inf. present: dream',
		'I often dream about traveling the world.',
		'A menudo sueño con viajar por el mundo.',
		'Inf. present: dreams',
		'She dreams of becoming a famous singer one day.',
		'Sueña con convertirse en una cantante famosa algún día.',
		'Past tense: dreamed/dreamt',
		'Last night, I dreamed that I could fly.',
		'Anoche soñé que podía volar.',
		'Past participle: dreamed/dreamt',
		'Have you ever dreamed of winning the lottery?',
		'¿Alguna vez has soñado con ganar la lotería?',
		'Gerund: dreaming',
		'Daydreaming is a good way to relax.',
		'Soñar despierto es una buena forma de relajarse.',
	],
	[
		'Inf. present: drown',
		"It's important to learn how to swim to avoid drowning.",
		'Es importante aprender a nadar para evitar ahogarse.',
		'Inf. present: drowns',
		'Every year, many people drown in the ocean.',
		'Cada año, muchas personas se ahogan en el océano.',
		'Past tense: drowned',
		'She nearly drowned when she fell into the river.',
		'Casi se ahogó cuando cayó al río.',
		'Past participle: drowned',
		'The victim had drowned before the ambulance arrived.',
		'La víctima había fallecido ahogada antes de que llegara la ambulancia.',
		'Gerund: drowning',
		'Drowning can happen quickly and silently.',
		'Ahogarse puede suceder rápidamente y en silencio.',
	],
	[
		'Inf. present: drink',
		'I always drink a glass of water before going to bed.',
		'Siempre bebo un vaso de agua antes de irme a la cama.',
		'Inf. present: drinks',
		'She never drinks coffee after noon.',
		'Nunca toma café después del mediodía.',
		'Past tense: drank',
		'Last night, I drank too much wine.',
		'Anoche bebí demasiado vino.',
		'Past participle: drunk',
		'He has never drunk alcohol in his life.',
		'Nunca ha bebido alcohol en su vida.',
		'Gerund: drinking',
		'Drinking water is essential for good health.',
		'Beber agua es esencial para una buena salud.',
	],
	[
		'Inf. present: drive',
		'I usually drive to work.',
		'Normalmente manejo al trabajo.',
		'Inf. present: drives',
		'He drives a sports car.',
		'Él conduce un coche deportivo.',
		'Past tense: drove',
		'I drove to the beach last weekend.',
		'Manejé a la playa el fin de semana pasado.',
		'Past participle: driven',
		'She has driven across the country before.',
		'Ella ha conducido por todo el país antes.',
		'Gerund: driving',
		"I don't like driving in the rain.",
		'No me gusta conducir bajo la lluvia.',
	],
	[
		'Inf. present: eat',
		'I always eat breakfast before work.',
		'Siempre desayuno antes del trabajo.',
		'Inf. present: eats',
		'She eats a salad for lunch every day.',
		'Ella come una ensalada para el almuerzo todos los días.',
		'Past tense: ate',
		'We ate at a fancy restaurant for our anniversary.',
		'Comimos en un restaurante elegante para nuestro aniversario.',
		'Past participle: eaten',
		'Have you ever eaten sushi?',
		'¿Alguna vez has comido sushi?',
		'Gerund: eating',
		'He is always snacking and eating throughout the day.',
		'Él siempre está picoteando y comiendo durante todo el día.',
	],
	[
		'Inf. present: fall',
		'The leaves fall from the trees in the autumn.',
		'Las hojas caen de los árboles en otoño.',
		'Inf. present: falls',
		'She fell down the stairs and broke her leg.',
		'Ella se cayó por las escaleras y se fracturó la pierna.',
		'Past tense: fell',
		'I fell asleep during the movie.',
		'Me quedé dormido durante la película.',
		'Past participle: fallen',
		'The book has fallen off the shelf.',
		'El libro se ha caído del estante.',
		'Gerund: falling',
		"I need to be careful when I'm walking on the icy sidewalk to avoid falling.",
		'Necesito tener cuidado cuando estoy caminando en la acera helada para evitar caerme.',
	],
	[
		'Inf. present: feed',
		'I need to feed the cat before I leave.',
		'Necesito alimentar al gato antes de irme.',
		'Inf. present: feeds',
		'She feeds the birds every morning.',
		'Ella alimenta a los pájaros todas las mañanas.',
		'Past tense: fed',
		'He fed the dog while I was away.',
		'Él alimentó al perro mientras yo estaba fuera.',
		'Past participle: fed',
		'The animals were well-fed during the winter months.',
		'Los animales estuvieron bien alimentados durante los meses de invierno.',
		'Gerund: feeding',
		'Feeding the hungry is a noble act.',
		'Alimentar a los hambrientos es un acto noble.',
	],
	[
		'Inf. present: feel',
		'I feel sick.',
		'Me siento enfermo.',
		'Inf. present: feels',
		"She feels happy when she's with her friends.",
		'Se siente feliz cuando está con sus amigos.',
		'Past tense: felt',
		'He felt tired after the long hike.',
		'Se sintió cansado después de la larga caminata.',
		'Past participle: felt',
		'I have never felt more alive than in this moment.',
		'Nunca me he sentido más vivo que en este momento.',
		'Gerund: feeling',
		"Feeling loved is one of life's greatest joys.",
		'Sentirse amado es una de las mayores alegrías de la vida.',
	],
	[
		'Inf. present: fight',
		"I don't like to fight with my friends.",
		'No me gusta pelear con mis amigos.',
		'Inf. present: fights',
		'She fights for what she believes in.',
		'Ella lucha por lo que cree.',
		'Past tense: fought',
		"They fought for their country's freedom.",
		'Lucharon por la libertad de su país.',
		'Past participle: fought',
		'The battle had been fought and won.',
		'La batalla había sido librada y ganada.',
		'Gerund: fighting',
		'Fighting for justice is a lifelong pursuit.',
		'Luchar por la justicia es una búsqueda de toda la vida.',
	],
	[
		'Inf. present: find',
		'I need to find my keys before we leave.',
		'Necesito encontrar mis llaves antes de salir.',
		'Inf. present: finds',
		'She always finds a way to solve problems.',
		'Ella siempre encuentra una manera de resolver problemas.',
		'Past tense: found',
		'He found a dollar on the street.',
		'Encontró un dólar en la calle.',
		'Past participle: found',
		'I have found the perfect gift for her birthday.',
		'He encontrado el regalo perfecto para su cumpleaños.',
		'Gerund: finding',
		'Finding the right words can be difficult sometimes.',
		'Encontrar las palabras adecuadas puede ser difícil a veces.',
	],
	[
		'Inf. present: fit',
		"This shirt doesn't fit me anymore.",
		'Esta camisa ya no me queda bien.',
		'Inf. present: fits',
		'The shoes fit perfectly.',
		'Los zapatos me quedan perfectos.',
		'Past tense: fit',
		'The dress fit her like a glove.',
		'El vestido le quedaba como un guante.',
		'Past participle: fit',
		'He has always been fit and healthy.',
		'Él siempre ha estado en forma y saludable.',
		'Gerund: fitting',
		'I am fitting the pieces together.',
		'Estoy ensamblando las piezas.',
	],
	[
		'Inf. present: fly',
		'I love to fly in airplanes.',
		'Me encanta volar en aviones.',
		'Inf. present: flies',
		'The bird flies very high in the sky.',
		'El pájaro vuela muy alto en el cielo.',
		'Past tense: flew',
		'She flew to New York last week.',
		'Ella voló a Nueva York la semana pasada.',
		'Past participle: flown',
		'Have you ever flown in a helicopter?',
		'¿Alguna vez has volado en un helicóptero?',
		'Gerund: flying',
		'Flying a kite is a fun activity for kids.',
		'Volar una cometa es una actividad divertida para los niños.',
	],
	[
		'Inf. present: forbid',
		'The sign forbids swimming in the lake.',
		'El letrero prohíbe nadar en el lago.',
		'Inf. present: forbids',
		'The law forbids the sale of alcohol to minors.',
		'La ley prohíbe la venta de alcohol a menores.',
		'Past tense: forbade',
		'His parents forbade him from going out late at night.',
		'Sus padres le prohibieron salir tarde en la noche.',
		'Past participle: forbidden',
		'Smoking is forbidden in the building.',
		'Fumar está prohibido en el edificio.',
		'Gerund: forbidding',
		'The forbidding tone of the letter made me nervous.',
		'El tono amenazante de la carta me puso nervioso.',
	],
	[
		'Inf. present: forget',
		'I always forget where I put my keys.',
		'Siempre olvido dónde puse mis llaves.',
		'Inf. present: forgets',
		"She never forgets her friends' birthdays.",
		'Nunca olvida los cumpleaños de sus amigos.',
		'Past tense: forgot',
		'I forgot to turn off the oven.',
		'Olvidé apagar el horno.',
		'Past participle: forgotten',
		'I have never forgotten my first trip abroad.',
		'Nunca he olvidado mi primer viaje al extranjero.',
		'Gerund: forgetting',
		'Her forgetfulness often gets her into trouble.',
		'Su olvido a menudo la mete en problemas.',
	],
	[
		'Inf. present: forgive',
		"It's important to forgive people who have hurt you.",
		'Es importante perdonar a las personas que te han lastimado.',
		'Inf. present: forgives',
		"He forgives easily and doesn't hold grudges.",
		'Él perdona fácilmente y no guarda rencor.',
		'Past tense: forgave',
		'She forgave her sister for breaking her favorite vase.',
		'Ella perdonó a su hermana por romper su florero favorito.',
		'Past participle: forgiven',
		'I hope I can be forgiven for my mistake.',
		'Espero que pueda ser perdonado por mi error.',
		'Gerund: forgiving',
		"Forgiving someone can be difficult, but it's worth it.",
		'Perdonar a alguien puede ser difícil, pero vale la pena.',
	],
	[
		'Inf. present: get',
		'I need to get some groceries from the store.',
		'Necesito comprar algunos víveres en la tienda.',
		'Inf. present: gets',
		'She always gets to work early.',
		'Siempre llega temprano al trabajo.',
		'Past tense: got',
		'I got a good grade on my exam.',
		'Obtuve una buena nota en mi examen.',
		'Past participle: gotten/got',
		'I have never gotten a speeding ticket.',
		'Nunca me han multado por exceso de velocidad.',
		'Gerund: getting',
		'I am getting better at playing the guitar.',
		'Estoy mejorando en tocar la guitarra.',
	],
	[
		'Inf. present: give',
		'I want to give my mom a birthday present.',
		'Quiero darle un regalo de cumpleaños a mi mamá.',
		'Inf. present: gives',
		'He always gives generously to charity.',
		'Siempre da generosamente a la caridad.',
		'Past tense: gave',
		'She gave me a ride to the airport.',
		'Me llevó al aeropuerto.',
		'Past participle: given',
		'The professor has given us a lot of homework this week.',
		'El profesor nos ha dado mucho trabajo esta semana.',
		'Gerund: giving',
		'Giving back to the community is important.',
		'Devolver a la comunidad es importante.',
	],
	[
		'Inf. present: go',
		'I want to go to the beach this weekend.',
		'Quiero ir a la playa este fin de semana.',
		'Inf. present: goes',
		'He goes for a run every morning.',
		'Sale a correr todas las mañanas.',
		'Past tense: went',
		'We went to the movies last night.',
		'Fuimos al cine anoche.',
		'Past participle: gone',
		'She has gone to Paris twice.',
		'Ha ido a París dos veces.',
		'Gerund: going',
		'What are you going to do this weekend?',
		'¿Qué vas a hacer este fin de semana?',
	],
	[
		'Inf. present: grind',
		'I need to grind some coffee beans.',
		'Necesito moler algunos granos de café.',
		'Inf. present: grinds',
		'He grinds his own flour.',
		'Él muele su propia harina.',
		'Past tense: ground',
		'She ground the spices in a mortar and pestle.',
		'Ella molió las especias en un mortero.',
		'Past participle: ground',
		'The meat is ground fresh every day.',
		'La carne se muele fresca todos los días.',
		'Gerund: grinding',
		'The sound of the coffee grinder is soothing to me.',
		'El sonido del molinillo de café es relajante para mí.',
	],
	[
		'Inf. present: grow',
		'These plants grow well in the shade.',
		'Estas plantas crecen bien en la sombra.',
		'Inf. present: grows',
		'The tomato plant grows quickly in the summer.',
		'La planta de tomate crece rápidamente en verano.',
		'Past tense: grew',
		'She grew up in a small town.',
		'Ella creció en un pueblo pequeño.',
		'Past participle: grown',
		'The tree has grown a lot since we planted it.',
		'El árbol ha crecido mucho desde que lo plantamos.',
		'Gerund: growing',
		'I enjoy watching my garden growing.',
		'Disfruto viendo crecer mi jardín.',
	],
	[
		'Inf. present: hang',
		'I need to hang this picture on the wall.',
		'Necesito colgar este cuadro en la pared.',
		'Inf. present: hangs',
		'The coat hangs in the closet.',
		'El abrigo cuelga en el armario.',
		'Past tense: hung',
		'She hung the curtains in the living room.',
		'Ella colgó las cortinas en la sala.',
		'Past participle: hung',
		'The painting has been hung in the museum.',
		'El cuadro ha sido colgado en el museo.',
		'Gerund: hanging',
		'The decoration hanging from the ceiling is beautiful.',
		'La decoración que cuelga del techo es hermosa.',
	],
	[
		'Inf. present: have',
		'I have a lot of work to do today.',
		'Tengo mucho trabajo que hacer hoy.',
		'Inf. present: has',
		'He has a new car.',
		'Él tiene un coche nuevo.',
		'Past tense: had',
		'I had a great time at the party.',
		'Me divertí mucho en la fiesta.',
		'Past participle: had',
		'We have had many challenges to overcome.',
		'Hemos tenido muchos desafíos que superar.',
		'Gerund: having',
		'Having good communication skills is important in any job.',
		'Tener buenas habilidades de comunicación es importante en cualquier trabajo.',
	],
	[
		'Inf. present: hear',
		'I can hear the birds singing outside.',
		'Puedo oír a los pájaros cantando afuera.',
		'Inf. present: hears',
		'She hears everything that is going on in the next room.',
		'Ella oye todo lo que está sucediendo en la habitación de al lado.',
		'Past tense: heard',
		'I heard the news on the radio this morning.',
		'Escuché las noticias en la radio esta mañana.',
		'Past participle: heard',
		'Have you ever heard of that band?',
		'¿Alguna vez has oído hablar de esa banda?',
		'Gerund: hearing',
		'Her hearing has improved since she got hearing aids.',
		'Su audición ha mejorado desde que obtuvo audífonos.',
	],
	[
		'Inf. present: hit',
		'He hit the ball out of the park.',
		'Él bateó la pelota fuera del parque.',
		'Inf. present: hits',
		'She always hits the snooze button in the morning.',
		'Siempre presiona el botón de repetición en la mañana.',
		'Past tense: hit',
		'The car hit a pothole and blew out a tire.',
		'El coche golpeó un bache y reventó un neumático.',
		'Past participle: hit',
		'He has been hit with a lot of bad luck lately.',
		'Ha sido golpeado con mucha mala suerte últimamente.',
		'Gerund: hitting',
		'I am not good at hitting a baseball.',
		'No soy bueno para golpear una pelota de béisbol.',
	],
	[
		'Inf. present: hold',
		'Can you hold this for a second?',
		'¿Puedes sostener esto por un segundo?',
		'Inf. present: holds',
		'She always holds her baby tightly.',
		'Ella siempre sostiene a su bebé fuertemente.',
		'Past tense: held',
		'He held the door open for me.',
		'Me abrió la puerta y me la mantuvo abierta.',
		'Past participle: held',
		'She has held many leadership positions in her career.',
		'Ella ha ocupado muchos puestos de liderazgo en su carrera.',
		'Gerund: holding',
		'Holding a grudge can be harmful to your relationships.',
		'Mantener rencor puede ser dañino para tus relaciones.',
	],
	[
		'Inf. present: hurt',
		'I hurt my knee while running.',
		'Me lastimé la rodilla mientras corría.',
		'Inf. present: hurts',
		'Her head hurts from studying too much.',
		'Le duele la cabeza de tanto estudiar.',
		'Past tense: hurt',
		'He hurt his ankle playing basketball.',
		'Se lastimó el tobillo jugando baloncesto.',
		'Past participle: hurt',
		"The company's reputation was hurt by the scandal.",
		'La reputación de la empresa se vio afectada por el escándalo.',
		'Gerund: hurting',
		'His words were hurting her feelings.',
		'Sus palabras le estaban lastimando los sentimientos.',
	],
	[
		'Inf. present: keep',
		'I need to keep my room clean.',
		'Necesito mantener mi habitación limpia.',
		'Inf. present: keeps',
		'She keeps a diary to track her progress.',
		'Ella lleva un diario para registrar su progreso.',
		'Past tense: kept',
		'He kept his promise to call me back.',
		'Cumplió su promesa de volverme a llamar.',
		'Past participle: kept',
		'They have kept the tradition alive for generations.',
		'Han mantenido la tradición viva por generaciones.',
		'Gerund: keeping',
		'Keeping a schedule helps me stay organized.',
		'Mantener un horario me ayuda a estar organizado.',
	],
	[
		'Inf. present: knit',
		'I learned how to knit a scarf last winter.',
		'Aprendí a tejer una bufanda el invierno pasado.',
		'Inf. present: knits',
		'She knits sweaters for her grandchildren.',
		'Ella teje suéteres para sus nietos.',
		'Past tense: knit/knitted',
		"She knit a blanket for her best friend's baby.",
		'Tejió una manta para el bebé de su mejor amiga.',
		'Past participle: knit/knitted',
		'He has knitted his own scarf.',
		'Ha tejido su propia bufanda.',
		'Gerund: knitting',
		'Knitting helps me relax.',
		'Tejer me ayuda a relajarme.',
	],
	[
		'Inf. present: know',
		'Do you know how to play guitar?',
		'¿Sabes tocar guitarra?',
		'Inf. present: knows',
		'He knows a lot about history.',
		'Él sabe mucho sobre historia.',
		'Past tense: knew',
		'I knew him when we were in college.',
		'Lo conocí cuando estábamos en la universidad.',
		'Past participle: known',
		'She is known for her cooking skills.',
		'Ella es conocida por sus habilidades culinarias.',
		'Gerund: knowing',
		'Knowing a second language can be very useful.',
		'Saber un segundo idioma puede ser muy útil.',
	],
	[
		'Inf. present: lead',
		'She wants to lead the company to success.',
		'Quiere liderar la empresa hacia el éxito.',
		'Inf. present: leads',
		'He always leads the group in warm-up exercises.',
		'Siempre dirige al grupo en ejercicios de calentamiento.',
		'Past tense: led',
		'She led her team to victory in the championship.',
		'Llevó a su equipo a la victoria en el campeonato.',
		'Past participle: led',
		'He has led many successful projects in his career.',
		'Ha liderado muchos proyectos exitosos en su carrera.',
		'Gerund: leading',
		'Leading a team can be challenging but rewarding.',
		'Liderar un equipo puede ser desafiante pero gratificante.',
	],
	[
		'Inf. present: leap',
		'The cat loves to leap from tree branches.',
		'Al gato le encanta saltar de las ramas de los árboles.',
		'Inf. present: leaps',
		'The athlete leaps gracefully over the hurdle.',
		'El atleta salta graciosamente sobre la valla.',
		'Past tense: leaped/leapt',
		'She leaped out of bed when the alarm went off.',
		'Saltó de la cama cuando sonó la alarma.',
		'Past participle: leaped/leapt',
		'The rabbit had leaped away before the fox could catch it.',
		'El conejo había saltado lejos antes de que el zorro pudiera atraparlo.',
		'Gerund: leaping',
		'The horse was leaping over the fence.',
		'El caballo estaba saltando sobre la cerca.',
	],
	[
		'Inf. present: learn',
		'I want to learn how to play the piano.',
		'Quiero aprender a tocar el piano.',
		'Inf. present: learns',
		'She learns quickly and easily.',
		'Ella aprende rápido y fácilmente.',
		'Past tense: learned/learnt',
		'He learned a lot during his time in college.',
		'Aprendió mucho durante su tiempo en la universidad.',
		'Past participle: learned/learnt',
		'I have learned so much from my experiences.',
		'He aprendido tanto de mis experiencias.',
		'Gerund: learning',
		'Learning a new language is challenging but rewarding.',
		'Aprender un nuevo idioma es desafiante pero gratificante.',
	],
	[
		'Inf. present: leave',
		'I have to leave early tomorrow morning.',
		'Tengo que salir temprano mañana por la mañana.',
		'Inf. present: leaves',
		"The train leaves at 10 o'clock.",
		'El tren sale a las 10 en punto.',
		'Past tense: left',
		'She left her phone at home.',
		'Ella dejó su teléfono en casa.',
		'Past participle: left',
		'Have you ever left a job without notice?',
		'¿Alguna vez has dejado un trabajo sin aviso?',
		'Gerund: leaving',
		'Leaving home for the first time can be scary.',
		'Dejar el hogar por primera vez puede ser aterrador.',
	],
	[
		'Inf. present: lend',
		'Can you lend me your pen?',
		'¿Me puedes prestar tu bolígrafo?',
		'Inf. present: lends',
		'The library lends out books for free.',
		'La biblioteca presta libros de forma gratuita.',
		'Past tense: lent',
		'She lent me her car for the weekend.',
		'Me prestó su coche para el fin de semana.',
		'Past participle: lent',
		'He has never lent anyone money before.',
		'Nunca ha prestado dinero a nadie antes.',
		'Gerund: lending',
		'Banks make money by lending out funds.',
		'Los bancos ganan dinero prestando fondos.',
	],
	[
		'Inf. present: let',
		'Let me know if you need any help.',
		'Déjame saber si necesitas ayuda.',
		'Inf. present: lets',
		'She lets her kids play outside in the afternoons.',
		'Deja a sus hijos jugar afuera por las tardes.',
		'Past tense: let',
		'He let his dog run free in the park.',
		'Dejó que su perro corriera libre en el parque.',
		'Past participle: let',
		'The landlord has let the apartment to a new tenant.',
		'El dueño ha alquilado el apartamento a un nuevo inquilino.',
		'Gerund: letting',
		'The teacher is letting the students work on the project together.',
		'El profesor está dejando que los estudiantes trabajen en el proyecto juntos.',
	],
	[
		'Inf. present: light',
		'She always lights a candle before bedtime.',
		'Siempre enciende una vela antes de dormir.',
		'Inf. present: lights',
		'The street lights turn on automatically at dusk.',
		'Las luces de la calle se encienden automáticamente al atardecer.',
		'Past tense: lit/lighted',
		'He lit the match and held it to the candle wick.',
		'Encendió el fósforo y lo acercó a la mecha de la vela.',
		'Past participle: lit/lighted',
		'The stage was lit with bright spotlights.',
		'El escenario estaba iluminado con brillantes focos.',
		'Gerund: lighting',
		'The lighting in the room was too dim for reading.',
		'La iluminación en la habitación era demasiado tenue para leer.',
	],
	[
		'Inf. present: lie',
		'I always tell the truth, I never lie.',
		'Siempre digo la verdad, nunca miento.',
		'Inf. present: lies',
		'She lies about her age.',
		'Ella miente sobre su edad.',
		'Past tense: lay',
		'She lay down on the couch to take a nap.',
		'Ella se acostó en el sofá para tomar una siesta.',
		'Past participle: lain',
		'The dog has lain in the sun all day.',
		'El perro ha estado tumbado al sol todo el día.',
		'Gerund: lying',
		'Stop lying to me, I know the truth.',
		'Deja de mentirme, sé la verdad.',
	],
	[
		'Inf. present: lose',
		'I always lose my keys.',
		'Siempre pierdo mis llaves.',
		'Inf. present: loses',
		'He loses his temper very easily.',
		'Él pierde fácilmente la paciencia.',
		'Past tense: lost',
		'I lost my wallet on the bus.',
		'Perdí mi cartera en el autobús.',
		'Past participle: lost',
		'Have you ever lost a bet?',
		'¿Alguna vez has perdido una apuesta?',
		'Gerund: losing',
		'She is afraid of losing her job.',
		'Ella teme perder su trabajo.',
	],
	[
		'Inf. present: meet',
		'I want to meet your family.',
		'Quiero conocer a tu familia.',
		'Inf. present: meets',
		'He meets with his boss every Monday.',
		'Se reúne con su jefe todos los lunes.',
		'Past tense: met',
		'I met my best friend in kindergarten.',
		'Conocí a mi mejor amigo en el jardín de infancia.',
		'Past participle: met',
		'Have you ever met a celebrity?',
		'¿Alguna vez has conocido a una celebridad?',
		'Gerund: meeting',
		'I am looking forward to meeting your parents.',
		'Estoy deseando conocer a tus padres.',
	],
	[
		'Inf. present: mistake',
		'I always mistake her for her sister.',
		'Siempre la confundo con su hermana.',
		'Inf. present: mistakes',
		'He never mistakes the time of his appointments.',
		'Nunca se equivoca en la hora de sus citas.',
		'Past tense: mistook',
		'I mistook the time and arrived too early.',
		'Me equivoqué de hora y llegué demasiado temprano.',
		'Past participle: mistaken',
		'I am mistaken about his intentions.',
		'Estoy equivocado acerca de sus intenciones.',
		'Gerund: mistaking',
		'Mistaking kindness for weakness is a common mistake.',
		'Confundir amabilidad con debilidad es un error común.',
	],
	[
		'Inf. present: pay',
		'I need to pay the rent by the end of the week.',
		'Necesito pagar el alquiler para el fin de semana.',
		'Inf. present: pays',
		'She always pays her bills on time.',
		'Siempre paga sus cuentas a tiempo.',
		'Past tense: paid',
		'I paid for the concert tickets last night.',
		'Pagué por las entradas del concierto anoche.',
		'Past participle: paid',
		'Have you paid the electric bill yet?',
		'¿Ya pagaste la factura de electricidad?',
		'Gerund: paying',
		'Paying attention is key to learning a new language.',
		'Prestar atención es clave para aprender un nuevo idioma.',
	],
	[
		'Inf. present: put',
		'Can you help me put the groceries away?',
		'¿Puedes ayudarme a guardar los alimentos?',
		'Inf. present: puts',
		'He always puts his keys in the same place.',
		'Siempre pone sus llaves en el mismo lugar.',
		'Past tense: put',
		'I put the book on the shelf.',
		'Puse el libro en el estante.',
		'Past participle: put',
		'Have you ever put together a piece of furniture?',
		'¿Alguna vez has armado un mueble?',
		'Gerund: putting',
		'Putting effort into your work can lead to great results.',
		'Poner esfuerzo en tu trabajo puede llevar a grandes resultados.',
	],
	[
		'Inf. present: quit',
		'I want to quit smoking.',
		'Quiero dejar de fumar.',
		'Inf. present: quits',
		'She never quits when she faces a challenge.',
		'Nunca se rinde cuando enfrenta un desafío.',
		'Past tense: quit',
		'He quit his job last month.',
		'Renunció a su trabajo el mes pasado.',
		'Past participle: quit/quit',
		'She has quit playing video games.',
		'Ha dejado de jugar videojuegos.',
		'Gerund: quitting',
		'Quitting is not always the best solution.',
		'Rendirse no siempre es la mejor solución.',
	],
	[
		'Inf. present: read',
		'I like to read books in my free time.',
		'Me gusta leer libros en mi tiempo libre.',
		'Inf. present: reads',
		'He reads the newspaper every morning.',
		'Él lee el periódico todas las mañanas.',
		'Past tense: read',
		'I read that book last year.',
		'Leí ese libro el año pasado.',
		'Past participle: read/read',
		'I have read all the Harry Potter books.',
		'He leído todos los libros de Harry Potter.',
		'Gerund: reading',
		'Reading helps improve vocabulary.',
		'La lectura ayuda a mejorar el vocabulario.',
	],
	[
		'Inf. present: ride',
		'I like to ride my bike to work.',
		'Me gusta ir en bicicleta al trabajo.',
		'Inf. present: rides',
		'She rides horses every weekend.',
		'Ella monta a caballo todos los fines de semana.',
		'Past tense: rode',
		'He rode his motorcycle across the country.',
		'Condujo su motocicleta por todo el país.',
		'Past participle: ridden',
		'She has never ridden a rollercoaster before.',
		'Nunca ha montado en una montaña rusa antes.',
		'Gerund: riding',
		'Riding a bike is a great form of exercise.',
		'Andar en bicicleta es una excelente forma de ejercicio.',
	],
	[
		'Inf. present: ring',
		'I need to ring my mom back.',
		'Necesito devolver la llamada a mi mamá.',
		'Inf. present: rings',
		'The phone rings every time I take a shower.',
		'El teléfono suena cada vez que me ducho.',
		'Past tense: rang',
		'She rang the doorbell twice before I heard it.',
		'Ella tocó el timbre dos veces antes de que lo oyera.',
		'Past participle: rung',
		'The church bells have rung for over a century.',
		'Las campanas de la iglesia han sonado durante más de un siglo.',
		'Gerund: ringing',
		'The constant ringing of the phone is driving me crazy.',
		'El constante sonido del teléfono me está volviendo loco.',
	],
	[
		'Inf. present: rise',
		'I always rise early on weekends.',
		'Siempre me levanto temprano los fines de semana.',
		'Inf. present: rises',
		'The sun rises in the east and sets in the west.',
		'El sol sale por el este y se pone por el oeste.',
		'Past tense: rose',
		'He rose from his chair and walked out of the room.',
		'Se levantó de su silla y salió de la habitación.',
		'Past participle: risen',
		'The moon has already risen over the horizon.',
		'La luna ya ha salido sobre el horizonte.',
		'Gerund: rising',
		'The rising cost of living is a concern for many people.',
		'El aumento del costo de vida es una preocupación para muchas personas.',
	],
	[
		'Inf. present: run',
		'I try to run at least three times a week.',
		'Trato de correr al menos tres veces a la semana.',
		'Inf. present: runs',
		'My dog runs faster than I do.',
		'Mi perro corre más rápido que yo.',
		'Past tense: ran',
		'She ran her first marathon last year.',
		'Ella corrió su primer maratón el año pasado.',
		'Past participle: run',
		'I have run out of patience with him.',
		'He perdido la paciencia con él.',
		'Gerund: running',
		'Running can be a great way to relieve stress.',
		'Correr puede ser una excelente manera de aliviar el estrés.',
	],
	[
		'Inf. present: see',
		'I see the mountains in the distance.',
		'Veo las montañas a lo lejos.',
		'Inf. present: sees',
		'He sees the world in black and white.',
		'Él ve el mundo en blanco y negro.',
		'Past tense: saw',
		'I saw an old friend at the grocery store.',
		'Vi a un viejo amigo en el supermercado.',
		'Past participle: seen',
		'She has seen that movie three times already.',
		'Ella ya ha visto esa película tres veces.',
		'Gerund: seeing',
		'Seeing is believing.',
		'Ver es creer.',
	],
	[
		'Inf. present: seek',
		'We seek knowledge and understanding.',
		'Buscamos conocimiento y comprensión.',
		'Inf. present: seeks',
		'She seeks the truth about her family history.',
		'Ella busca la verdad sobre la historia de su familia.',
		'Past tense: sought',
		'He sought advice from his mentor.',
		'Buscó consejo de su mentor.',
		'Past participle: sought',
		'They have sought justice for years.',
		'Han buscado justicia durante años.',
		'Gerund: seeking',
		'The company is currently seeking new talent.',
		'La empresa actualmente está buscando nuevo talento.',
	],
	[
		'Inf. present: sell',
		'I sell handmade crafts at the local market.',
		'Vendo artesanías hechas a mano en el mercado local.',
		'Inf. present: sells',
		'The store sells a variety of products.',
		'La tienda vende una variedad de productos.',
		'Past tense: sold',
		'She sold her car to pay for college.',
		'Ella vendió su auto para pagar la universidad.',
		'Past participle: sold',
		'He has sold over 100 paintings in his career.',
		'Ha vendido más de 100 pinturas en su carrera.',
		'Gerund: selling',
		'The company is currently selling its products overseas.',
		'La empresa actualmente está vendiendo sus productos en el extranjero.',
	],
	[
		'Inf. present: send',
		'I need to send an email to my boss.',
		'Necesito enviar un correo electrónico a mi jefe.',
		'Inf. present: sends',
		'The company sends out a newsletter every month.',
		'La compañía envía un boletín cada mes.',
		'Past tense: sent',
		'She sent me a birthday card.',
		'Ella me envió una tarjeta de cumpleaños.',
		'Past participle: sent',
		'I have never been sent on a business trip before.',
		'Nunca antes me habían enviado en un viaje de negocios.',
		'Gerund: sending',
		'Sending a text message while driving is dangerous.',
		'Enviar un mensaje de texto mientras se conduce es peligroso.',
	],
	[
		'Inf. present: set',
		'I need to set my alarm for 6am.',
		'Necesito programar mi alarma para las 6 am.',
		'Inf. present: sets',
		'The sun sets in the west.',
		'El sol se pone en el oeste.',
		'Past tense: set',
		'She set the table for dinner.',
		'Ella puso la mesa para la cena.',
		'Past participle: set',
		'Have you ever set foot in Europe?',
		'¿Alguna vez has puesto un pie en Europa?',
		'Gerund: setting',
		'Setting goals is important for success.',
		'Establecer metas es importante para el éxito.',
	],
	[
		'Inf. present: shake',
		'The earthquake shook the building.',
		'El terremoto sacudió el edificio.',
		'Inf. present: shakes',
		'He shakes his head in disbelief.',
		'Él mueve la cabeza incrédulo.',
		'Past tense: shook',
		'She shook the rug outside.',
		'Ella sacudió la alfombra afuera.',
		'Past participle: shaken',
		'The experience has shaken me to the core.',
		'La experiencia me ha conmocionado hasta lo más profundo.',
		'Gerund: shaking',
		'Shaking hands is a common greeting.',
		'Estrechar las manos es un saludo común.',
	],
	[
		'Inf. present: shine',
		'The sun shines brightly today.',
		'El sol brilla con fuerza hoy.',
		'Inf. present: shines',
		'The stars shine in the night sky.',
		'Las estrellas brillan en el cielo nocturno.',
		'Past tense: shone',
		'The moon shone over the lake.',
		'La luna brillaba sobre el lago.',
		'Past participle: shone',
		'Her talent has shone through since she was young.',
		'Su talento ha brillado desde que era joven.',
		'Gerund: shining',
		'The diamond is shining brilliantly in the sunlight.',
		'El diamante brilla brillantemente en la luz del sol.',
	],
	[
		'Inf. present: shoot',
		'He likes to shoot his bow and arrow.',
		'Le gusta disparar su arco y flecha.',
		'Inf. present: shoots',
		'The basketball player shoots and scores!',
		'¡El jugador de baloncesto lanza y anota!',
		'Past tense: shot',
		'She shot a bird with her camera.',
		'Ella tomó una foto de un pájaro con su cámara.',
		'Past participle: shot',
		'The wounded soldier was shot in battle.',
		'El soldado herido fue disparado en la batalla.',
		'Gerund: shooting',
		'He spends his weekends shooting targets at the range.',
		'Pasa sus fines de semana disparando a objetivos en el campo de tiro.',
	],
	[
		'Inf. present: sing',
		'She loves to sing in the shower.',
		'Le encanta cantar en la ducha.',
		'Inf. present: sings',
		'He sings lead vocals in the band.',
		'Él canta la voz principal en la banda.',
		'Past tense: sang',
		'They sang "Happy Birthday" to him at the party.',
		'Le cantaron "Feliz Cumpleaños" en la fiesta.',
		'Past participle: sung',
		'The choir has sung at many events.',
		'El coro ha cantado en muchos eventos.',
		'Gerund: singing',
		'Singing in the choir helps her relax.',
		'Cantar en el coro la ayuda a relajarse.',
	],
	[
		'Inf. present: sit',
		'I like to sit on the balcony and read.',
		'Me gusta sentarme en el balcón y leer.',
		'Inf. present: sits',
		'She always sits in the front row.',
		'Ella siempre se sienta en la primera fila.',
		'Past tense: sat',
		'I sat next to a famous actor on the plane.',
		'Me senté al lado de un actor famoso en el avión.',
		'Past participle: sat',
		'He has sat through many boring meetings.',
		'Ha asistido a muchas reuniones aburridas.',
		'Gerund: sitting',
		'Sitting for too long can be bad for your health.',
		'Sentarse durante demasiado tiempo puede ser malo para la salud.',
	],
	[
		'Inf. present: sleep',
		'I need to sleep at least 8 hours every night.',
		'Necesito dormir al menos 8 horas cada noche.',
		'Inf. present: sleeps',
		'My cat sleeps for most of the day.',
		'Mi gato duerme la mayor parte del día.',
		'Past tense: slept',
		'I slept like a baby last night.',
		'Dormí como un bebé anoche.',
		'Past participle: slept',
		'She has slept for 12 hours straight.',
		'Ella ha dormido durante 12 horas seguidas.',
		'Gerund: sleeping',
		'Sleeping in on weekends is one of my guilty pleasures.',
		'Dormir hasta tarde los fines de semana es uno de mis placeres culpables.',
	],
	[
		'Inf. present: slide',
		'The children love to slide down the hill.',
		'A los niños les encanta deslizarse por la colina.',
		'Inf. present: slides',
		'The ball slides easily on the polished floor.',
		'La pelota se desliza fácilmente sobre el suelo pulido.',
		'Past tense: slid',
		'I slid on the ice and fell.',
		'Me deslicé sobre el hielo y caí.',
		'Past participle: slid',
		'The drawer slid out smoothly.',
		'El cajón se deslizó suavemente hacia afuera.',
		'Gerund: sliding',
		'Sliding into the pool, he felt the cool water surround him.',
		'Deslizándose en la piscina, sintió el agua fresca rodearlo.',
	],
	[
		'Inf. present: speak',
		'He speaks three languages fluently.',
		'Habla con fluidez tres idiomas.',
		'Inf. present: speaks',
		"She speaks softly when she's nervous.",
		'Habla suavemente cuando está nerviosa.',
		'Past tense: spoke',
		'He spoke for an hour about his trip.',
		'Habló durante una hora sobre su viaje.',
		'Past participle: spoken',
		'Have you ever spoken in public?',
		'¿Alguna vez has hablado en público?',
		'Gerund: speaking',
		'Speaking clearly is important in public speaking.',
		'Hablar claramente es importante en la oratoria.',
	],
	[
		'Inf. present: spend',
		'She spends too much money on clothes.',
		'Ella gasta demasiado dinero en ropa.',
		'Inf. present: spends',
		'He spends his weekends volunteering at the animal shelter.',
		'Pasa sus fines de semana como voluntario en el refugio de animales.',
		'Past tense: spent',
		'We spent our vacation in Europe last year.',
		'Pasamos nuestras vacaciones en Europa el año pasado.',
		'Past participle: spent',
		'She has spent her entire career working in education.',
		'Ha pasado toda su carrera trabajando en educación.',
		'Gerund: spending',
		'Spending time with loved ones is important for mental health.',
		'Pasando tiempo con seres queridos es importante para la salud mental.',
	],
	[
		'Inf. present: spill',
		'He accidentally spilled coffee on his shirt.',
		'Derramó accidentalmente café en su camisa.',
		'Inf. present: spills',
		'She always spills food on her clothes.',
		'Siempre derrama comida en su ropa.',
		'Past tense: spilled/spilt',
		'She spilled the milk all over the counter.',
		'Derramó la leche por todo el mostrador.',
		'Past participle: spilled/spilt',
		'The ship had spilled oil into the ocean.',
		'El barco había derramado aceite en el océano.',
		'Gerund: spilling',
		'Spilling secrets can damage relationships.',
		'Revelar secretos puede dañar relaciones.',
	],
	[
		'Inf. present: spit',
		'He spit out his coffee because it was too hot.',
		'Escupió su café porque estaba muy caliente.',
		'Inf. present: spits',
		'The cat always spits at the dog when he comes near her food bowl.',
		'El gato siempre le escupe al perro cuando se acerca a su plato de comida.',
		'Past tense: spat',
		'She spat out her gum before entering the building.',
		'Ella escupió su chicle antes de entrar al edificio.',
		'Past participle: spat/spit',
		"The wrestler spat in his opponent's face, which caused a commotion.",
		'El luchador escupió en la cara de su oponente, lo que causó una conmoción.',
		'Gerund: spitting',
		'Spitting on the sidewalk is illegal in some places.',
		'Escupir en la acera es ilegal en algunos lugares.',
	],
	[
		'Inf. present: spring',
		'The cat sprung out of the box when I opened it.',
		'El gato saltó de la caja cuando la abrí.',
		'Inf. present: springs',
		'The water in the lake springs up from an underground source.',
		'El agua del lago surge de una fuente subterránea.',
		'Past tense: sprang/sprung',
		'He sprang out of bed when he heard the alarm.',
		'Saltó de la cama cuando escuchó la alarma.',
		'Past participle: sprung',
		'The trap had already been sprung when we arrived.',
		'La trampa ya había sido activada cuando llegamos.',
		'Gerund: springing',
		'The squirrel was springing from branch to branch in the tree.',
		'La ardilla saltaba de rama en rama en el árbol.',
	],
	[
		'Inf. present: stand',
		'I always stand up when someone enters the room.',
		'Siempre me levanto cuando alguien entra en la habitación.',
		'Inf. present: stands',
		'The tower stands over 100 feet tall.',
		'La torre tiene más de 100 pies de altura.',
		'Past tense: stood',
		'He stood at attention when the general entered the room.',
		'Se puso en posición de firmes cuando el general entró en la habitación.',
		'Past participle: stood',
		'She has stood up for what she believes in her whole life.',
		'Ella ha defendido lo que cree en toda su vida.',
		'Gerund: standing',
		'Standing in line for hours is no fun.',
		'Estar de pie en línea durante horas no es divertido.',
	],
	[
		'Inf. present: steal',
		'He was caught trying to steal a car.',
		'Fue atrapado tratando de robar un coche.',
		'Inf. present: steals',
		'She steals money from her parents.',
		'Ella roba dinero a sus padres.',
		'Past tense: stole',
		'Someone stole my bike from the park.',
		'Alguien robó mi bicicleta del parque.',
		'Past participle: stolen',
		'The stolen necklace was worth thousands of dollars.',
		'El collar robado valía miles de dólares.',
		'Gerund: stealing',
		'Stealing is a crime that can have serious consequences.',
		'Robar es un delito que puede tener consecuencias graves.',
	],
	[
		'Inf. present: sweep',
		'I need to sweep the floor before the guests arrive.',
		'Necesito barrer el piso antes de que lleguen los invitados.',
		'Inf. present: sweeps',
		'She sweeps the porch every morning.',
		'Ella barre el porche todas las mañanas.',
		'Past tense: swept',
		'I swept the leaves off the driveway.',
		'Barrí las hojas del camino de entrada.',
		'Past participle: swept',
		'The room was swept clean before the party.',
		'La habitación fue limpiada a fondo antes de la fiesta.',
		'Gerund: sweeping',
		'Sweeping the floor is a chore that needs to be done regularly.',
		'Barrer el suelo es una tarea que debe hacerse regularmente.',
	],
	[
		'Inf. present: swim',
		'I like to swim in the ocean during the summer.',
		'Me gusta nadar en el océano durante el verano.',
		'Inf. present: swims',
		'He swims every morning at the gym.',
		'Él nada todas las mañanas en el gimnasio.',
		'Past tense: swam',
		'She swam across the lake in under an hour.',
		'Nadó a través del lago en menos de una hora.',
		'Past participle: swum',
		'I have never swum in a lake before.',
		'Nunca he nadado en un lago antes.',
		'Gerund: swimming',
		'Swimming is a great form of exercise.',
		'Nadar es una excelente forma de ejercicio.',
	],
	[
		'Inf. present: swing',
		'She likes to swing on the playground.',
		'Le gusta columpiarse en el parque infantil.',
		'Inf. present: swings',
		'He swings the bat with great force.',
		'Él golpea el bate con gran fuerza.',
		'Past tense: swung',
		'They swung their arms back and forth.',
		'Movieron los brazos de un lado a otro.',
		'Past participle: swung',
		'The door swung open with a loud creak.',
		'La puerta se abrió con un fuerte chirrido.',
		'Gerund: swinging',
		'The couple was swinging on the porch swing.',
		'La pareja estaba balanceándose en el columpio del porche.',
	],
	[
		'Inf. present: take',
		'I always take the bus to work.',
		'Siempre tomo el autobús al trabajo.',
		'Inf. present: takes',
		'She takes her coffee with cream and sugar.',
		'Toma su café con crema y azúcar.',
		'Past tense: took',
		'He took a nap after lunch.',
		'Tomó una siesta después del almuerzo.',
		'Past participle: taken',
		'Have you ever taken a dance class?',
		'¿Alguna vez has tomado una clase de baile?',
		'Gerund: taking',
		'Taking care of plants is relaxing for me.',
		'Cuidar las plantas es relajante para mí.',
	],
	[
		'Inf. present: teach',
		'She likes to teach her students about different cultures.',
		'Le gusta enseñar a sus estudiantes sobre diferentes culturas.',
		'Inf. present: teaches',
		'He teaches math at the local college.',
		'Enseña matemáticas en el colegio local.',
		'Past tense: taught',
		'She taught me how to cook lasagna.',
		'Me enseñó a cocinar lasaña.',
		'Past participle: taught',
		'The course is taught in English.',
		'El curso se imparte en inglés.',
		'Gerund: teaching',
		'Teaching can be a very rewarding profession.',
		'La enseñanza puede ser una profesión muy gratificante.',
	],
	[
		'Inf. present: tear',
		'I accidentally tore my shirt.',
		'Me rasguñé accidentalmente la camisa.',
		'Inf. present: tears',
		'She tears up whenever she watches that movie.',
		'Ella se emociona cada vez que ve esa película.',
		'Past tense: tore',
		'The paper tore easily.',
		'El papel se rasgó fácilmente.',
		'Past participle: torn',
		'I have torn my ACL before.',
		'Me he desgarrado el ligamento cruzado anterior antes.',
		'Gerund: tearing',
		'The wind was tearing through the trees.',
		'El viento estaba arrasando los árboles.',
	],
	[
		'Inf. present: tell',
		'I need to tell you something important.',
		'Necesito decirte algo importante.',
		'Inf. present: tells',
		'She tells the best stories.',
		'Ella cuenta las mejores historias.',
		'Past tense: told',
		'He told us about his adventures.',
		'Él nos contó sobre sus aventuras.',
		'Past participle: told',
		'I have never been told that before.',
		'Nunca me han dicho eso antes.',
		'Gerund: telling',
		'Telling jokes is one of his favorite things to do.',
		'Contar chistes es una de sus cosas favoritas.',
	],
	[
		'Inf. present: think',
		'I always think before I speak.',
		'Siempre pienso antes de hablar.',
		'Inf. present: thinks',
		"She thinks that he's the one for her.",
		'Ella piensa que él es el indicado para ella.',
		'Past tense: thought',
		'I thought that was a great movie.',
		'Pensé que era una gran película.',
		'Past participle: thought',
		'Have you ever thought about moving abroad?',
		'¿Alguna vez has pensado en mudarte al extranjero?',
		'Gerund: thinking',
		'Thinking positively can change your life.',
		'Pensar positivamente puede cambiar tu vida.',
	],
	[
		'Inf. present: throw',
		'He throws the ball to his teammate.',
		'Él lanza la pelota a su compañero de equipo.',
		'Inf. present: throws',
		'She throws away anything that is expired.',
		'Ella tira cualquier cosa que esté vencida.',
		'Past tense: threw',
		'He threw the frisbee over the fence.',
		'Él lanzó el frisbee por encima de la cerca.',
		'Past participle: thrown',
		'They have never thrown a surprise party before.',
		'Nunca han organizado una fiesta sorpresa antes.',
		'Gerund: throwing',
		'Throwing a baseball requires a lot of skill.',
		'Lanzar una pelota de béisbol requiere mucha habilidad.',
	],
	[
		'Inf. present: undertake',
		'I will undertake the project next week.',
		'Empezaré el proyecto la semana que viene.',
		'Inf. present: undertakes',
		'The company undertakes various construction projects.',
		'La empresa realiza varios proyectos de construcción.',
		'Past tense: undertook',
		'He undertook the task without hesitation.',
		'Asumió la tarea sin vacilar.',
		'Past participle: undertaken',
		'They have already undertaken a similar project in the past.',
		'Ya han realizado un proyecto similar en el pasado.',
		'Gerund: undertaking',
		'Undertaking such a big project requires careful planning.',
		'Realizar un proyecto tan grande requiere una planificación cuidadosa.',
	],
	[
		'Inf. present: upset',
		'She is upset about the situation.',
		'Está molesta por la situación.',
		'Inf. present: upsets',
		'Spicy food upsets my stomach.',
		'La comida picante me revuelve el estómago.',
		'Past tense: upset',
		'He upset his boss with his behavior.',
		'Molestó a su jefe con su comportamiento.',
		'Past participle: upset',
		'The team was upset by their loss.',
		'El equipo estaba molesto por su derrota.',
		'Gerund: upsetting',
		'The news was very upsetting for the whole family.',
		'La noticia fue muy perturbadora para toda la familia.',
	],
	[
		'Inf. present: wake',
		'I usually wake up at 6am.',
		'Normalmente me despierto a las 6 de la mañana.',
		'Inf. present: wakes',
		'The baby wakes up every two hours at night.',
		'El bebé se despierta cada dos horas por la noche.',
		'Past tense: woke',
		'I woke up late this morning and missed my bus.',
		'Me desperté tarde esta mañana y perdí mi autobús.',
		'Past participle: woken',
		'I have never woken up feeling so refreshed before.',
		'Nunca antes me había despertado sintiéndome tan renovado.',
		'Gerund: waking',
		'Waking up early has many benefits.',
		'Levantarse temprano tiene muchos beneficios.',
	],
	[
		'Inf. present: wear',
		"I like to wear comfortable clothes when I'm at home.",
		'Me gusta llevar ropa cómoda cuando estoy en casa.',
		'Inf. present: wears',
		'She always wears her favorite necklace to important meetings.',
		'Siempre lleva su collar favorito a las reuniones importantes.',
		'Past tense: wore',
		'I wore my new dress to the party last night.',
		'Llevé mi vestido nuevo a la fiesta anoche.',
		'Past participle: worn',
		'I have never worn such uncomfortable shoes before.',
		'Nunca antes he usado zapatos tan incómodos.',
		'Gerund: wearing',
		"Wearing sunglasses protects your eyes from the sun's harmful rays.",
		'Usar gafas de sol protege tus ojos de los rayos dañinos del sol.',
	],
	[
		'Inf. present: wet',
		'The rain is making everything wet.',
		'La lluvia está mojando todo.',
		'Inf. present: wets',
		"The dog wets the floor if he doesn't go outside on time.",
		'El perro moja el suelo si no sale a tiempo.',
		'Past tense: wet',
		'I got wet walking home in the rain.',
		'Me mojé caminando a casa bajo la lluvia.',
		'Past participle: wet',
		"The paint isn't dry yet, be careful not to touch it and get wet.",
		'La pintura aún no está seca, ten cuidado de no tocarla y mojarte.',
		'Gerund: wetting',
		'Wetting your hair before swimming can help protect it from chlorine.',
		'Mojarse el cabello antes de nadar puede ayudar a protegerlo del cloro.',
	],
	[
		'Inf. present: win',
		'We always play to win.',
		'Siempre jugamos para ganar.',
		'Inf. present: wins',
		'She wins every game she plays.',
		'Ella gana todos los juegos que juega.',
		'Past tense: won',
		'He won the race last year.',
		'Ganó la carrera el año pasado.',
		'Past participle: won',
		'I have never won a lottery before.',
		'Nunca he ganado una lotería antes.',
		'Gerund: winning',
		'Winning isn’t everything.',
		'Ganar no es todo.',
	],
	[
		'Inf. present: wind',
		'The road winds through the mountains.',
		'La carretera serpentea a través de las montañas.',
		'Inf. present: winds',
		'The river winds its way through the valley.',
		'El río se abre camino a través del valle.',
		'Past tense: wound',
		'He wound the rope around the post.',
		'Enrolló la cuerda alrededor del poste.',
		'Past participle: wound',
		'The clock has wound down.',
		'El reloj se ha desgastado.',
		'Gerund: winding',
		'The winding path led us to a hidden garden.',
		'El camino serpenteante nos llevó a un jardín escondido.',
	],
	[
		'Inf. present: write',
		'I like to write stories in my free time.',
		'Me gusta escribir cuentos en mi tiempo libre.',
		'Inf. present: writes',
		'She writes poetry that touches people’s hearts.',
		'Ella escribe poesía que conmueve los corazones de las personas.',
		'Past tense: wrote',
		'He wrote a letter to his friend in Europe.',
		'Escribió una carta a su amigo en Europa.',
		'Past participle: written',
		'Have you ever written a book?',
		'¿Alguna vez has escrito un libro?',
		'Gerund: writing',
		'Writing a novel takes a lot of time and effort.',
		'Escribir una novela requiere mucho tiempo y esfuerzo.',
	],
];
