export default [
    "accept",
    "accepted",
    "accepting",
    "aceptar",
    "answer",
    "answered",
    "answering",
    "responder",
    "contestar",
    "arrive",
    "arrived",
    "arriving",
    "llegar",
    "ask",
    "asked",
    "asking",
    "preguntar",
    "belong",
    "belonged",
    "belonging",
    "pertenecer",
    "bother",
    "bothered",
    "bothering",
    "molestar",
    "change",
    "changed",
    "changing",
    "cambiar",
    "clean",
    "cleaned",
    "cleaning",
    "limpiar",
    "climb",
    "climbed",
    "climbing",
    "subir",
    "escalar",
    "trepar",
    "close",
    "closed",
    "closing",
    "cerrar",
    "consider",
    "considered",
    "considering",
    "considerar",
    "cook",
    "cooked",
    "cooking",
    "cocinar",
    "count",
    "counted",
    "counting",
    "contar",
    "dance",
    "danced",
    "dancing",
    "bailar",
    "dare",
    "dared",
    "daring",
    "atreverse",
    "retar",
    "date",
    "dated",
    "dating",
    "salir con alguien",
    "fecha",
    "salir",
    "cita",
    "deliver",
    "delivered",
    "delivering",
    "entregar",
    "dress",
    "dressed",
    "dressing",
    "vestir",
    "end",
    "ended",
    "ending",
    "terminar",
    "enjoy",
    "enjoyed",
    "enjoying",
    "disfrutar",
    "erase",
    "erased",
    "erasing",
    "borrar",
    "expect",
    "expected",
    "expecting",
    "esperar",
    "fill",
    "filled",
    "filling",
    "llenar",
    "finish",
    "finished",
    "finishing",
    "finalizar",
    "follow",
    "followed",
    "following",
    "seguir",
    "help",
    "helped",
    "helping",
    "ayudar",
    "hurry",
    "hurried",
    "hurrying",
    "apresurarse",
    "apurar",
    "intend",
    "intended",
    "intending",
    "pretender",
    "intención",
    "jump",
    "jumped",
    "jumping",
    "saltar",
    "brincar",
    "learn",
    "learned",
    "learnt",
    "learning",
    "aprender",
    "lie",
    "lied",
    "lying",
    "mentir",
    "like",
    "liked",
    "liking",
    "gustar",
    "listen",
    "listened",
    "listening",
    "escuchar",
    "live",
    "lived",
    "living",
    "vivir",
    "look",
    "looked",
    "looking",
    "ver",
    "love",
    "loved",
    "loving",
    "amar",
    "miss",
    "missed",
    "missing",
    "extrañar",
    "name",
    "named",
    "naming",
    "nombrar",
    "need",
    "needed",
    "needing",
    "necesitar",
    "open",
    "opened",
    "opening",
    "abrir",
    "order",
    "ordered",
    "ordering",
    "ordenar",
    "plan",
    "planned",
    "planning",
    "planear",
    "plant",
    "planted",
    "planting",
    "plantar",
    "play",
    "played",
    "playing",
    "jugar",
    "point",
    "pointed",
    "pointing",
    "apuntar",
    "practice",
    "practiced",
    "practicing",
    "practicar",
    "push",
    "pushed",
    "pushing",
    "empujar",
    "rain",
    "rained",
    "raining",
    "llover",
    "remember",
    "remembered",
    "remembering",
    "recordar",
    "rent",
    "rented",
    "renting",
    "alquilar",
    "rentar",
    "repeat",
    "repeated",
    "repeating",
    "repetir",
    "resist",
    "resisted",
    "resisting",
    "resistir",
    "show",
    "showed",
    "showing",
    "mostrar",
    "enseñar",
    "smoke",
    "smoked",
    "smoking",
    "fumar",
    "start",
    "started",
    "starting",
    "empezar",
    "stay",
    "stayed",
    "staying",
    "quedarse",
    "stop",
    "stopped",
    "stopping",
    "detener",
    "parar",
    "study",
    "studied",
    "studying",
    "estudiar",
    "talk",
    "talked",
    "talking",
    "hablar",
    "travel",
    "traveled",
    "travelled",
    "traveling",
    "travelling",
    "viajar",
    "try",
    "tried",
    "trying",
    "intentar",
    "tratar",
    "turn",
    "turned",
    "turning",
    "girar",
    "voltear",
    "use",
    "used",
    "using",
    "usar",
    "visit",
    "visited",
    "visiting",
    "visitar",
    "wait",
    "waited",
    "waiting",
    "walk",
    "walked",
    "walking",
    "caminar",
    "want",
    "wanted",
    "wanting",
    "querer",
    "desear",
    "wash",
    "washed",
    "washing",
    "lavar",
    "wish",
    "wished",
    "wishing",
    "work",
    "worked",
    "working",
    "trabajar",
    "verbo",
    "verb",
    "infinitive",
    "present",
    "infinitivo",
    "presente",
    "past",
    "tense",
    "pasado",
    "simple",
    "Past",
    "participle",
    "participio",
    "perund",
    "perundio",
    "gerund",
    "gerundio",
    "accepts",
    "answers",
    "arrives",
    "asks",
    "belongs",
    "bothers",
    "changes",
    "cleans",
    "climbs",
    "closes",
    "considers",
    "cooks",
    "counts",
    "dances",
    "dares",
    "dates",
    "delivers",
    "dresses",
    "ends",
    "enjoys",
    "erases",
    "expects",
    "fills",
    "finishes",
    "follows",
    "helps",
    "hurries",
    "intends",
    "jumps",
    "learns",
    "lies",
    "likes",
    "listens",
    "lives",
    "looks",
    "loves",
    "misses",
    "names",
    "needs",
    "opens",
    "orders",
    "plans",
    "plants",
    "plays",
    "points",
    "practices",
    "pushes",
    "rains",
    "lluvia",
    "remembers",
    "rents",
    "repeats",
    "resists",
    "shows",
    "smokes",
    "starts",
    "stays",
    "stops",
    "studies",
    "talks",
    "travels",
    "tries",
    "turns",
    "uses",
    "visits",
    "waits",
    "walks",
    "wants",
    "washes",
    "wishes",
    "works",
    "acepta",
    "aceptado",
    "aceptando",
    "respuesta",
    "respuestas",
    "contestada",
    "respondiendo",
    "llega",
    "llegó",
    "llegando",
    "pregunta",
    "preguntó",
    "preguntando",
    "pertenece",
    "pertenecía",
    "pertenencia",
    "molesta",
    "molesto",
    "cambios",
    "cambió",
    "cambiando",
    "limpio",
    "limpia",
    "limpiado",
    "limpieza",
    "sube",
    "escalado",
    "escalada",
    "cerca",
    "cierra",
    "cerrado",
    "clausura",
    "considera",
    "consideró",
    "considerando",
    "cocineros",
    "cocido",
    "cocinando",
    "cuenta",
    "contado",
    "contando",
    "bailes",
    "danzado",
    "baile",
    "atrevimiento",
    "se atreve",
    "atrevido",
    "fechas",
    "con fecha de",
    "tener una cita",
    "entrega",
    "entregado",
    "entregando",
    "vestido",
    "vestidos",
    "vendaje",
    "fin",
    "termina",
    "terminó",
    "finalizando",
    "disfruta",
    "disfruté",
    "disfrutando",
    "borra",
    "borrado",
    "borrando",
    "espera",
    "esperado",
    "esperando",
    "llena",
    "completado",
    "relleno",
    "acabados",
    "finalizado",
    "refinamiento",
    "sigue",
    "seguido",
    "siguiente",
    "ayuda",
    "ayudó",
    "Ayudar",
    "apurarse",
    "se apresura",
    "apresurado",
    "apurado",
    "pretende",
    "destinado",
    "con la intención",
    "salta",
    "saltó",
    "saltando",
    "aprende",
    "aprendió",
    "aprendiendo",
    "mentiras",
    "mintió",
    "mintiendo",
    "como",
    "gustos",
    "apreciado",
    "gusto",
    "escucha",
    "escuchado",
    "escuchando",
    "vidas",
    "vivido",
    "viviendo",
    "mirar",
    "aspecto",
    "miró",
    "mirando",
    "ama",
    "amado",
    "cariñoso",
    "extraña",
    "omitido",
    "desaparecido",
    "nombre",
    "nombres",
    "llamado",
    "nombrando",
    "necesidad",
    "necesidades",
    "necesario",
    "necesitando",
    "abierto",
    "abre",
    "abrió",
    "apertura",
    "orden",
    "pedidos",
    "ordenado",
    "ordenando",
    "planes",
    "planificado",
    "planificación",
    "planta",
    "plantas",
    "plantado",
    "plantando",
    "obras de teatro",
    "jugó",
    "jugando",
    "punto",
    "puntos",
    "puntiagudo",
    "señalando",
    "práctica",
    "prácticas",
    "experto",
    "practicando",
    "empuja",
    "empujado",
    "emprendedor",
    "lluvias",
    "Inf.",
    "present:",
    "tense:",
    "participle:",
    "Gerund:",
]
// [
// 	'accept',
// 	'accepted',
// 	'accepting',
// 	'aceptar',
// 	'answer',
// 	'answered',
// 	'answering',
// 	'responder',
// 	'contestar',
// 	'arrive',
// 	'arrived',
// 	'arriving',
// 	'llegar',
// 	'ask',
// 	'asked',
// 	'asking',
// 	'preguntar',
// 	'belong',
// 	'belonged',
// 	'belonging',
// 	'pertenecer',
// 	'bother',
// 	'bothered',
// 	'bothering',
// 	'molestar',
// 	'change',
// 	'changed',
// 	'changing',
// 	'cambiar',
// 	'clean',
// 	'cleaned',
// 	'cleaning',
// 	'limpiar',
// 	'climb',
// 	'climbed',
// 	'climbing',
// 	'subir',
// 	'escalar',
// 	'trepar',
// 	'close',
// 	'closed',
// 	'closing',
// 	'cerrar',
// 	'consider',
// 	'considered',
// 	'considering',
// 	'considerar',
// 	'cook',
// 	'cooked',
// 	'cooking',
// 	'cocinar',
// 	'count',
// 	'counted',
// 	'counting',
// 	'contar',
// 	'dance',
// 	'danced',
// 	'dancing',
// 	'bailar',
// 	'dare',
// 	'dared',
// 	'daring',
// 	'atreverse',
// 	'retar',
// 	'date',
// 	'dated',
// 	'dating',
// 	'salir con alguien',
// 	'fecha',
// 	'salir',
// 	'cita',
// 	'deliver',
// 	'delivered',
// 	'delivering',
// 	'entregar',
// 	'dress',
// 	'dressed',
// 	'dressing',
// 	'vestir',
// 	'end',
// 	'ended',
// 	'ending',
// 	'terminar',
// 	'enjoy',
// 	'enjoyed',
// 	'enjoying',
// 	'disfrutar',
// 	'erase',
// 	'erased',
// 	'erasing',
// 	'borrar',
// 	'expect',
// 	'expected',
// 	'expecting',
// 	'esperar',
// 	'fill',
// 	'filled',
// 	'filling',
// 	'llenar',
// 	'finish',
// 	'finished',
// 	'finishing',
// 	'terminar',
// 	'finalizar',
// 	'follow',
// 	'followed',
// 	'following',
// 	'seguir',
// 	'help',
// 	'helped',
// 	'helping',
// 	'ayudar',
// 	'hurry',
// 	'hurried',
// 	'hurrying',
// 	'apresurarse',
// 	'apurar',
// 	'intend',
// 	'intended',
// 	'intending',
// 	'pretender',
// 	'intención',
// 	'jump',
// 	'jumped',
// 	'jumping',
// 	'saltar',
// 	'brincar',
// 	'learn',
// 	'learned',
// 	'learnt',
// 	'learning',
// 	'aprender',
// 	'lie',
// 	'lied',
// 	'lying',
// 	'mentir',
// 	'like',
// 	'liked',
// 	'liking',
// 	'gustar',
// 	'listen',
// 	'listened',
// 	'listening',
// 	'escuchar',
// 	'live',
// 	'lived',
// 	'living',
// 	'vivir',
// 	'look',
// 	'looked',
// 	'looking',
// 	'saltar',
// 	'ver',
// 	'love',
// 	'loved',
// 	'loving',
// 	'amar',
// 	'miss',
// 	'missed',
// 	'missing',
// 	'extrañar',
// 	'name',
// 	'named',
// 	'naming',
// 	'nombrar',
// 	'need',
// 	'needed',
// 	'needing',
// 	'necesitar',
// 	'open',
// 	'opened',
// 	'opening',
// 	'abrir',
// 	'order',
// 	'ordered',
// 	'ordering',
// 	'ordenar',
// 	'plan',
// 	'planned',
// 	'planning',
// 	'planear',
// 	'plant',
// 	'planted',
// 	'planting',
// 	'plantar',
// 	'play',
// 	'played',
// 	'playing',
// 	'jugar',
// 	'point',
// 	'pointed',
// 	'pointing',
// 	'apuntar',
// 	'practice',
// 	'practiced',
// 	'practicing',
// 	'practicar',
// 	'push',
// 	'pushed',
// 	'pushing',
// 	'empujar',
// 	'rain',
// 	'rained',
// 	'raining',
// 	'llover',
// 	'remember',
// 	'remembered',
// 	'remembering',
// 	'recordar',
// 	'rent',
// 	'rented',
// 	'renting',
// 	'alquilar',
// 	'rentar',
// 	'repeat',
// 	'repeated',
// 	'repeating',
// 	'repetir',
// 	'resist',
// 	'resisted',
// 	'resisting',
// 	'resistir',
// 	'show',
// 	'showed',
// 	'showing',
// 	'mostrar',
// 	'enseñar',
// 	'smoke',
// 	'smoked',
// 	'smoking',
// 	'fumar',
// 	'start',
// 	'started',
// 	'starting',
// 	'empezar',
// 	'stay',
// 	'stayed',
// 	'staying',
// 	'quedarse',
// 	'stop',
// 	'stopped',
// 	'stopping',
// 	'detener',
// 	'parar',
// 	'study',
// 	'studied',
// 	'studying',
// 	'estudiar',
// 	'talk',
// 	'talked',
// 	'talking',
// 	'hablar',
// 	'travel',
// 	'traveled',
// 	'travelled',
// 	'traveling',
// 	'travelling',
// 	'viajar',
// 	'try',
// 	'tried',
// 	'trying',
// 	'intentar',
// 	'tratar',
// 	'turn',
// 	'turned',
// 	'turning',
// 	'girar',
// 	'voltear',
// 	'cambiar',
// 	'use',
// 	'used',
// 	'using',
// 	'usar',
// 	'visit',
// 	'visited',
// 	'visiting',
// 	'visitar',
// 	'wait',
// 	'waited',
// 	'waiting',
// 	'esperar',
// 	'walk',
// 	'walked',
// 	'walking',
// 	'caminar',
// 	'want',
// 	'wanted',
// 	'wanting',
// 	'querer',
// 	'desear',
// 	'wash',
// 	'washed',
// 	'washing',
// 	'lavar',
// 	'wish',
// 	'wished',
// 	'wishing',
// 	'desear',
// 	'querer',
// 	'work',
// 	'worked',
// 	'working',
// 	'trabajar',
// 	'verbo',
// 	'verb',
// 	'infinitive',
// 	'present',
// 	'infinitivo',
// 	'presente',
// 	'past',
// 	'tense',
// 	'pasado',
// 	'simple',
// 	'Past',
// 	'participle',
// 	'pasado',
// 	'participio',
// 	'perund',
// 	'perundio',
// 	'gerund',
// 	'gerundio',
// 	'accept',
// 	'accepts',
// 	'accepted',
// 	'accepting',
// 	'answer',
// 	'answers',
// 	'answered',
// 	'answering',
// 	'arrive',
// 	'arrives',
// 	'arrived',
// 	'arriving',
// 	'ask',
// 	'asks',
// 	'asked',
// 	'asking',
// 	'belong',
// 	'belongs',
// 	'belonged',
// 	'belonging',
// 	'bother',
// 	'bothers',
// 	'bothered',
// 	'bothering',
// 	'change',
// 	'changes',
// 	'changed',
// 	'changing',
// 	'clean',
// 	'cleans',
// 	'cleaned',
// 	'cleaning',
// 	'climb',
// 	'climbs',
// 	'climbed',
// 	'climbing',
// 	'close',
// 	'closes',
// 	'closed',
// 	'closing',
// 	'consider',
// 	'considers',
// 	'considered',
// 	'considering',
// 	'cook',
// 	'cooks',
// 	'cooked',
// 	'cooking',
// 	'count',
// 	'counts',
// 	'counted',
// 	'counting',
// 	'dance',
// 	'dances',
// 	'danced',
// 	'dancing',
// 	'dare',
// 	'dares',
// 	'dared',
// 	'daring',
// 	'date',
// 	'dates',
// 	'dated',
// 	'dating',
// 	'deliver',
// 	'delivers',
// 	'delivered',
// 	'delivering',
// 	'dress',
// 	'dresses',
// 	'dressed',
// 	'dressing',
// 	'end',
// 	'ends',
// 	'ended',
// 	'ending',
// 	'enjoy',
// 	'enjoys',
// 	'enjoyed',
// 	'enjoying',
// 	'erase',
// 	'erases',
// 	'erased',
// 	'erasing',
// 	'expect',
// 	'expects',
// 	'expected',
// 	'expecting',
// 	'fill',
// 	'fills',
// 	'filled',
// 	'filling',
// 	'finish',
// 	'finishes',
// 	'finished',
// 	'finishing',
// 	'follow',
// 	'follows',
// 	'followed',
// 	'following',
// 	'help',
// 	'helps',
// 	'helped',
// 	'helping',
// 	'hurry',
// 	'hurries',
// 	'hurried',
// 	'hurrying',
// 	'intend',
// 	'intends',
// 	'intended',
// 	'intending',
// 	'jump',
// 	'jumps',
// 	'jumped',
// 	'jumping',
// 	'learn',
// 	'learns',
// 	'learned',
// 	'learning',
// 	'lie',
// 	'lies',
// 	'lied',
// 	'lying',
// 	'like',
// 	'likes',
// 	'liked',
// 	'liking',
// 	'listen',
// 	'listens',
// 	'listened',
// 	'listening',
// 	'live',
// 	'lives',
// 	'lived',
// 	'living',
// 	'look',
// 	'looks',
// 	'looked',
// 	'looking',
// 	'love',
// 	'loves',
// 	'loved',
// 	'loving',
// 	'miss',
// 	'misses',
// 	'missed',
// 	'missing',
// 	'name',
// 	'names',
// 	'named',
// 	'naming',
// 	'need',
// 	'needs',
// 	'needed',
// 	'needing',
// 	'open',
// 	'opens',
// 	'opened',
// 	'opening',
// 	'order',
// 	'orders',
// 	'ordered',
// 	'ordering',
// 	'plan',
// 	'plans',
// 	'planned',
// 	'planning',
// 	'plant',
// 	'plants',
// 	'planted',
// 	'planting',
// 	'play',
// 	'plays',
// 	'played',
// 	'playing',
// 	'point',
// 	'points',
// 	'pointed',
// 	'pointing',
// 	'practice',
// 	'practices',
// 	'practiced',
// 	'practicing',
// 	'push',
// 	'pushes',
// 	'pushed',
// 	'pushing',
// 	'rain',
// 	'rains',
// 	'rain',
// 	'rains',
// 	'rained',
// 	'raining',
// 	'lluvia',
// 	'remember',
// 	'remembers',
// 	'remembered',
// 	'remembering',
// 	'recordar',
// 	'rent',
// 	'rents',
// 	'rented',
// 	'renting',
// 	'alquilar',
// 	'rentar',
// 	'repeat',
// 	'repeats',
// 	'repeated',
// 	'repeating',
// 	'repetir',
// 	'resist',
// 	'resists',
// 	'resisted',
// 	'resisting',
// 	'resistir',
// 	'show',
// 	'shows',
// 	'showed',
// 	'showing',
// 	'mostrar',
// 	'enseñar',
// 	'smoke',
// 	'smokes',
// 	'smoked',
// 	'smoking',
// 	'fumar',
// 	'start',
// 	'starts',
// 	'started',
// 	'starting',
// 	'empezar',
// 	'stay',
// 	'stays',
// 	'stayed',
// 	'staying',
// 	'quedarse',
// 	'stop',
// 	'stops',
// 	'stopped',
// 	'stopping',
// 	'detener',
// 	'parar',
// 	'study',
// 	'studies',
// 	'studied',
// 	'studying',
// 	'estudiar',
// 	'talk',
// 	'talks',
// 	'talked',
// 	'talking',
// 	'hablar',
// 	'travel',
// 	'travels',
// 	'traveled',
// 	'traveling',
// 	'travelling',
// 	'viajar',
// 	'try',
// 	'tries',
// 	'tried',
// 	'trying',
// 	'intentar',
// 	'tratar',
// 	'turn',
// 	'turns',
// 	'turned',
// 	'turning',
// 	'girar',
// 	'voltear',
// 	'cambiar',
// 	'use',
// 	'uses',
// 	'used',
// 	'using',
// 	'usar',
// 	'visit',
// 	'visits',
// 	'visited',
// 	'visiting',
// 	'visitar',
// 	'wait',
// 	'waits',
// 	'waited',
// 	'waiting',
// 	'esperar',
// 	'walk',
// 	'walks',
// 	'walked',
// 	'walking',
// 	'caminar',
// 	'want',
// 	'wants',
// 	'wanted',
// 	'wanting',
// 	'querer',
// 	'desear',
// 	'wash',
// 	'washes',
// 	'washed',
// 	'washing',
// 	'lavar',
// 	'wish',
// 	'wishes',
// 	'wished',
// 	'wishing',
// 	'desear',
// 	'querer',
// 	'work',
// 	'works',
// 	'worked',
// 	'working',
// 	'trabajar',
// 	'aceptar',
// 	'acepta',
// 	'aceptado',
// 	'aceptando',
// 	'respuesta',
// 	'respuestas',
// 	'contestada',
// 	'respondiendo',
// 	'llegar',
// 	'llega',
// 	'llegó',
// 	'llegando',
// 	'preguntar',
// 	'pregunta',
// 	'preguntó',
// 	'preguntando',
// 	'pertenecer',
// 	'pertenece',
// 	'pertenecía',
// 	'pertenencia',
// 	'molestar',
// 	'molesta',
// 	'molesto',
// 	'molesto',
// 	'cambiar',
// 	'cambios',
// 	'cambió',
// 	'cambiando',
// 	'limpio',
// 	'limpia',
// 	'limpiado',
// 	'limpieza',
// 	'trepar',
// 	'sube',
// 	'escalado',
// 	'escalada',
// 	'cerca',
// 	'cierra',
// 	'cerrado',
// 	'clausura',
// 	'considerar',
// 	'considera',
// 	'consideró',
// 	'considerando',
// 	'cocinar',
// 	'cocineros',
// 	'cocido',
// 	'cocinando',
// 	'contar',
// 	'cuenta',
// 	'contado',
// 	'contando',
// 	'bailar',
// 	'bailes',
// 	'danzado',
// 	'baile',
// 	'atrevimiento',
// 	'se atreve',
// 	'atrevido',
// 	'atrevido',
// 	'fecha',
// 	'fechas',
// 	'con fecha de',
// 	'tener una cita',
// 	'entregar',
// 	'entrega',
// 	'entregado',
// 	'entregando',
// 	'vestido',
// 	'vestidos',
// 	'vestido',
// 	'vendaje',
// 	'fin',
// 	'termina',
// 	'terminó',
// 	'finalizando',
// 	'disfrutar',
// 	'disfruta',
// 	'disfruté',
// 	'disfrutando',
// 	'borrar',
// 	'borra',
// 	'borrado',
// 	'borrando',
// 	'esperar',
// 	'espera',
// 	'esperado',
// 	'esperando',
// 	'llenar',
// 	'llena',
// 	'completado',
// 	'relleno',
// 	'finalizar',
// 	'acabados',
// 	'finalizado',
// 	'refinamiento',
// 	'seguir',
// 	'sigue',
// 	'seguido',
// 	'siguiente',
// 	'ayuda',
// 	'ayuda',
// 	'ayudó',
// 	'Ayudar',
// 	'apurarse',
// 	'se apresura',
// 	'apresurado',
// 	'apurado',
// 	'pretender',
// 	'pretende',
// 	'destinado',
// 	'con la intención',
// 	'saltar',
// 	'salta',
// 	'saltó',
// 	'saltando',
// 	'aprender',
// 	'aprende',
// 	'aprendió',
// 	'aprendiendo',
// 	'mentir',
// 	'mentiras',
// 	'mintió',
// 	'mintiendo',
// 	'como',
// 	'gustos',
// 	'apreciado',
// 	'gusto',
// 	'escuchar',
// 	'escucha',
// 	'escuchado',
// 	'escuchando',
// 	'vivir',
// 	'vidas',
// 	'vivido',
// 	'viviendo',
// 	'mirar',
// 	'aspecto',
// 	'miró',
// 	'mirando',
// 	'amar',
// 	'ama',
// 	'amado',
// 	'cariñoso',
// 	'extrañar',
// 	'extraña',
// 	'omitido',
// 	'desaparecido',
// 	'nombre',
// 	'nombres',
// 	'llamado',
// 	'nombrando',
// 	'necesidad',
// 	'necesidades',
// 	'necesario',
// 	'necesitando',
// 	'abierto',
// 	'abre',
// 	'abrió',
// 	'apertura',
// 	'orden',
// 	'pedidos',
// 	'ordenado',
// 	'ordenando',
// 	'plan',
// 	'planes',
// 	'planificado',
// 	'planificación',
// 	'planta',
// 	'plantas',
// 	'plantado',
// 	'plantando',
// 	'jugar',
// 	'obras de teatro',
// 	'jugó',
// 	'jugando',
// 	'punto',
// 	'puntos',
// 	'puntiagudo',
// 	'señalando',
// 	'práctica',
// 	'prácticas',
// 	'experto',
// 	'practicando',
// 	'empujar',
// 	'empuja',
// 	'empujado',
// 	'emprendedor',
// 	'lluvia',
// 	'lluvias',
// ];
