export default [
	{
		verb: 'To accept',
		verbo: 'aceptar',
		'Infinitive present': 'I always accept invitations to parties.',
		'Infinitivo presente': 'Siempre acepto invitaciones a fiestas.',
		'Past tense': 'She accepted the job offer last week.',
		'Pasado simple': 'Aceptó la oferta de trabajo la semana pasada.',
		'Past participle': 'The package was accepted by the recipient.',
		'Pasado participio': 'El paquete fue aceptado por el destinatario.',
		Gerund: 'He is not used to accepting help from others.',
		Gerundio: 'No está acostumbrado a aceptar ayuda de otros.',
	},
	{
		verb: 'To answer',
		verbo: 'responder',
		'Infinitive present': 'They never answer their phones during meetings.',
		'Infinitivo presente': 'Nunca responden sus teléfonos durante reuniones.',
		'Past tense': 'She answered all the questions correctly on the exam.',
		'Pasado simple': 'Respondió todas las preguntas correctamente en el examen.',
		'Past participle': 'The letter has not been answered yet.',
		'Pasado participio': 'La carta aún no ha sido respondida.',
		Gerund: 'He is good at answering emails promptly.',
		Gerundio: 'Es bueno en responder correos electrónicos rápidamente.',
	},
	{
		verb: 'To arrive',
		verbo: 'llegar',
		'Infinitive present': 'They usually arrive at the office at 9 am.',
		'Infinitivo presente': 'Por lo general llegan a la oficina a las 9 am.',
		'Past tense': 'We arrived at the airport two hours before the flight.',
		'Pasado simple': 'Llegamos al aeropuerto dos horas antes del vuelo.',
		'Past participle': 'The package had already arrived when we got home.',
		'Pasado participio': 'El paquete ya había llegado cuando llegamos a casa.',
		Gerund: 'She hates arriving late to meetings.',
		Gerundio: 'Odia llegar tarde a las reuniones.',
	},
	{
		verb: 'To ask',
		verbo: 'preguntar',
		'Infinitive present': 'He always asks a lot of questions in class.',
		'Infinitivo presente': 'Siempre hace muchas preguntas en clase.',
		'Past tense': 'She asked me to help her with her homework.',
		'Pasado simple': 'Me pidió que la ayudara con su tarea.',
		'Past participle': 'He has never been asked to speak in public before.',
		'Pasado participio': 'Nunca le han pedido que hable en público antes.',
		Gerund: 'They are not used to asking for help.',
		Gerundio: 'No están acostumbrados a pedir ayuda.',
	},
	{
		verb: 'To belong',
		verbo: 'pertenecer',
		'Infinitive present': 'The book belongs on the top shelf.',
		'Infinitivo presente': 'El libro pertenece al estante superior.',
		'Past tense': 'The necklace belonged to her grandmother.',
		'Pasado simple': 'El collar pertenecía a su abuela.',
		'Past participle': 'I have belonged to that club for five years.',
		'Pasado participio': 'He pertenecido a ese club durante cinco años.',
		Gerund: 'She enjoys belonging to a community group.',
		Gerundio: 'Disfruta pertenecer a un grupo comunitario.',
	},
	{
		verb: 'To bother',
		verbo: 'molestar',
		'Infinitive present': "Please don't bother me while I'm working.",
		'Infinitivo presente': 'Por favor, no me molestes mientras estoy trabajando.',
		'Past tense': 'He bothered his sister all day with his constant talking.',
		'Pasado simple': 'Molesto a su hermana todo el día con su charla constante.',
		'Past participle': 'I was bothered by the loud noise outside my window.',
		'Pasado participio': 'Me molestaba el ruido fuerte fuera de mi ventana.',
		Gerund: 'Stop bothering me with all these questions.',
		Gerundio: 'Deja de molestarme con todas estas preguntas.',
	},
	{
		verb: 'To change',
		verbo: 'cambiar',
		'Infinitive present': 'She wants to change her hairstyle for the new year.',
		'Infinitivo presente': 'Quiere cambiar su peinado para el nuevo año.',
		'Past tense': 'They changed their plans at the last minute.',
		'Pasado simple': 'Cambiaron sus planes en el último minuto.',
		'Past participle': 'The company has changed its policy on vacation time.',
		'Pasado participio': 'La empresa ha cambiado su política sobre el tiempo de vacaciones.',
		Gerund: 'He is considering changing his major in college.',
		Gerundio: 'Está considerando cambiar su especialización en la universidad.',
	},
	{
		verb: 'To clean',
		verbo: 'limpiar',
		'Infinitive present': 'She cleans the kitchen every night after dinner.',
		'Infinitivo presente': 'Limpia la cocina todas las noches después de la cena.',
		'Past tense': 'He cleaned the garage on Saturday morning.',
		'Pasado simple': 'Limpió el garaje el sábado por la mañana.',
		'Past participle': 'The house was cleaned from top to bottom before the guests arrived.',
		'Pasado participio': 'La casa fue limpiada de arriba abajo antes de que llegaran los invitados.',
		Gerund: "She is always cleaning her house, even though it's already spotless.",
		Gerundio: 'Siempre está limpiando su casa, aunque ya esté impecable.',
	},
	{
		verb: 'To climb',
		verbo: 'escalar',
		'Infinitive present': 'They like to climb mountains in their free time.',
		'Infinitivo presente': 'Les gusta escalar montañas en su tiempo libre.',
		'Past tense': 'He climbed the tree to get a better view of the park.',
		'Pasado simple': 'Escaló el árbol para tener una mejor vista del parque.',
		'Past participle': 'She has climbed the highest peak in the state.',
		'Pasado participio': 'Ha escalado la cumbre más alta del estado.',
		Gerund: 'Climbing is his favorite hobby.',
		Gerundio: 'Escalar es su pasatiempo favorito.',
	},
	{
		verb: 'To close',
		verbo: 'cerrar',
		'Infinitive present': 'Please close the door when you leave.',
		'Infinitivo presente': 'Por favor, cierra la puerta cuando salgas.',
		'Past tense': 'He closed the window before going to bed.',
		'Pasado simple': 'Cerró la ventana antes de acostarse.',
		'Past participle': 'The store was closed for renovations.',
		'Pasado participio': 'La tienda estaba cerrada por renovaciones.',
		Gerund: 'Closing the deal took longer than expected.',
		Gerundio: 'Cerrar el trato llevó más tiempo de lo esperado.',
	},
	{
		verb: 'To consider',
		verbo: 'considerar',
		'Infinitive present': 'She is considering a job offer from another company.',
		'Infinitivo presente': 'Está considerando una oferta de trabajo de otra empresa.',
		'Past tense': 'We considered all the options before making a decision.',
		'Pasado simple': 'Consideramos todas las opciones antes de tomar una decisión.',
		'Past participle': 'He was considered the best candidate for the position.',
		'Pasado participio': 'Fue considerado el mejor candidato para el puesto.',
		Gerund: 'Considering the circumstances, he made the best choice.',
		Gerundio: 'Considerando las circunstancias, tomó la mejor decisión.',
	},
	{
		verb: 'To cook',
		verbo: 'cocinar',
		'Infinitive present': 'He likes to cook dinner for his family.',
		'Infinitivo presente': 'Le gusta cocinar la cena para su familia.',
		'Past tense': 'She cooked a delicious meal for her guests.',
		'Pasado simple': 'Cocinó una comida deliciosa para sus invitados.',
		'Past participle': 'The food was cooked to perfection.',
		'Pasado participio': 'La comida fue cocinada a la perfección.',
		Gerund: 'Cooking is a great way to unwind after a long day.',
		Gerundio: 'Cocinar es una gran manera de relajarse después de un largo día.',
	},
	{
		verb: 'To count',
		verbo: 'contar',
		'Infinitive present': 'Can you count to ten in Spanish?',
		'Infinitivo presente': '¿Puedes contar hasta diez en español?',
		'Past tense': 'She counted the money twice to make sure it was correct.',
		'Pasado simple': 'Contó el dinero dos veces para asegurarse de que era correcto.',
		'Past participle': 'The votes were counted and the winner was announced.',
		'Pasado participio': 'Los votos fueron contados y el ganador fue anunciado.',
		Gerund: 'Counting the number of stars in the sky is impossible.',
		Gerundio: 'Contar el número de estrellas en el cielo es imposible.',
	},
	{
		verb: 'To dance',
		verbo: 'bailar',
		'Infinitive present': 'They love to dance at weddings.',
		'Infinitivo presente': 'Les encanta bailar en las bodas.',
		'Past tense': 'She danced with her father at her quinceañera.',
		'Pasado simple': 'Bailó con su padre en su quinceañera.',
		'Past participle': 'The dance floor was cleared for the performance.',
		'Pasado participio': 'La pista de baile fue despejada para la presentación.',
		Gerund: 'Dancing is a fun way to stay active and healthy.',
		Gerundio: 'Bailar es una manera divertida de mantenerse activo y saludable.',
	},
	{
		verb: 'To dare',
		verbo: 'atreverse',
		'Infinitive present': "He doesn't dare to jump off the diving board.",
		'Infinitivo presente': 'No se atreve a saltar del trampolín.',
		'Past tense': 'She dared him to eat the spicy chili pepper.',
		'Pasado simple': 'Le desafió a comer el chile picante.',
		'Past participle': 'The stunt was daring and impressive.',
		'Pasado participio': 'La acrobacia fue atrevida e impresionante.',
		Gerund: 'Daring to dream big can lead to great things.',
		Gerundio: 'Atreverse a soñar en grande puede llevar a grandes cosas.',
	},
	{
		verb: 'To date',
		verbo: 'salir con alguien',
		'Infinitive present': 'She is dating her coworker.',
		'Infinitivo presente': 'Sale con su compañero de trabajo.',
		'Past tense': 'They dated for two years before getting married.',
		'Pasado simple': 'Salieron durante dos años antes de casarse.',
		'Past participle': 'The letter was dated April 1st.',
		'Pasado participio': 'La carta estaba fechada el 1 de abril.',
		Gerund: 'Dating can be a fun and exciting way to meet new people.',
		Gerundio: 'Salir con alguien puede ser una forma divertida y emocionante de conocer gente nueva.',
	},
	{
		verb: 'To deliver',
		verbo: 'entregar',
		'Infinitive present': 'The postman delivers mail to our house every day.',
		'Infinitivo presente': 'El cartero entrega el correo a nuestra casa todos los días.',
		'Past tense': 'She delivered the package to the correct address.',
		'Pasado simple': 'Entregó el paquete a la dirección correcta.',
		'Past participle': 'The speech was delivered with passion and enthusiasm.',
		'Pasado participio': 'El discurso fue entregado con pasión y entusiasmo.',
		Gerund: 'Delivering food to those in need is a rewarding experience.',
		Gerundio: 'Entregar comida a aquellos que la necesitan es una experiencia gratificante.',
	},
	{
		verb: 'To dress',
		verbo: 'vestirse',
		'Infinitive present': 'He always dresses in casual clothes on weekends.',
		'Infinitivo presente': 'Siempre se viste con ropa casual los fines de semana.',
		'Past tense': 'She dressed up in a fancy gown for the formal event.',
		'Pasado simple': 'Se vistió con un vestido elegante para el evento formal.',
		'Past participle': 'The man was well-dressed in a suit and tie.',
		'Pasado participio': 'El hombre estaba bien vestido con traje y corbata.',
		Gerund: 'Dressing for success can help boost confidence and motivation.',
		Gerundio: 'Vestirse para el éxito puede ayudar a aumentar la confianza y la motivación.',
	},
	{
		verb: 'To end',
		verbo: 'terminar',
		'Infinitive present': 'We need to end this meeting soon.',
		'Infinitivo presente': 'Necesitamos terminar esta reunión pronto.',
		'Past tense': 'The party ended at midnight.',
		'Pasado simple': 'La fiesta terminó a medianoche.',
		'Past participle': 'The book ended with a surprising twist.',
		'Pasado participio': 'El libro terminó con un giro sorprendente.',
		Gerund: 'Ending a relationship can be difficult but necessary.',
		Gerundio: 'Terminar una relación puede ser difícil pero necesario.',
	},
	{
		verb: 'To enjoy',
		verbo: 'disfrutar',
		'Infinitive present': 'She enjoys reading books on a lazy afternoon.',
		'Infinitivo presente': 'Disfruta leyendo libros en una tarde tranquila.',
		'Past tense': 'We enjoyed our vacation at the beach.',
		'Pasado simple': 'Disfrutamos nuestras vacaciones en la playa.',
		'Past participle': 'The enjoyed the concert so much that they went to see the band again the next night.',
		'Pasado participio':
			'Disfrutaron tanto del concierto que fueron a ver a la banda nuevamente la noche siguiente.',
		Gerund: 'Enjoying the simple things in life can bring great happiness.',
		Gerundio: 'Disfrutar de las cosas simples de la vida puede traer gran felicidad.',
	},
	{
		verb: 'To erase',
		verbo: 'borrar',
		'Infinitive present': 'He erases mistakes on the chalkboard during class.',
		'Infinitivo presente': 'Borra errores en la pizarra durante la clase.',
		'Past tense': 'She erased the message she had written on the whiteboard.',
		'Pasado simple': 'Borró el mensaje que había escrito en la pizarra blanca.',
		'Past participle': 'The file was erased from the computer by accident.',
		'Pasado participio': 'El archivo fue borrado accidentalmente de la computadora.',
		Gerund: "Erasing bad memories can be difficult, but it's important to focus on the present.",
		Gerundio: 'Borrar malos recuerdos puede ser difícil, pero es importante centrarse en el presente.',
	},
	{
		verb: 'To expect',
		verbo: 'esperar',
		'Infinitive present': 'They expect to arrive at the airport on time.',
		'Infinitivo presente': 'Esperan llegar al aeropuerto a tiempo.',
		'Past tense': "She expected to receive a promotion at work, but it didn't happen.",
		'Pasado simple': 'Esperaba recibir una promoción en el trabajo, pero no sucedió.',
		'Past participle': 'The guests were expected to arrive at 7 pm.',
		'Pasado participio': 'Se esperaba que los invitados llegaran a las 7 pm.',
		Gerund: 'Expecting too much from others can lead to disappointment.',
		Gerundio: 'Esperar demasiado de los demás puede llevar a la decepción.',
	},
	{
		verb: 'To fill',
		verbo: 'llenar',
		'Infinitive present': 'He fills his water bottle every morning before going to work.',
		'Infinitivo presente': 'Llena su botella de agua todas las mañanas antes de ir al trabajo.',
		'Past tense': 'She filled the bathtub with warm water for a relaxing soak.',
		'Pasado simple': 'Llenó la bañera con agua tibia para un baño relajante.',
		'Past participle': 'The glass was filled to the brim with juice.',
		'Pasado participio': 'El vaso estaba lleno hasta el borde con jugo.',
		Gerund: 'Filling your day with meaningful activities can help improve your mood.',
		Gerundio: 'Llenar tu día con actividades significativas puede ayudar a mejorar tu estado de ánimo.',
	},
	{
		verb: 'To finish',
		verbo: 'terminar',
		'Infinitive present': 'She needs to finish her homework before dinner.',
		'Infinitivo presente': 'Necesita terminar su tarea antes de la cena.',
		'Past tense': 'They finished the project ahead of schedule.',
		'Pasado simple': 'Terminaron el proyecto antes de lo previsto.',
		'Past participle': 'The painting was finished just in time for the art show.',
		'Pasado participio': 'El cuadro fue terminado justo a tiempo para la muestra de arte.',
		Gerund: 'Finishing what you start is an important key to success.',
		Gerundio: 'Terminar lo que empiezas es una clave importante para el éxito.',
	},
	{
		verb: 'To follow',
		verbo: 'seguir',
		'Infinitive present': 'She always follows her daily routine.',
		'Infinitivo presente': 'Siempre sigue su rutina diaria.',
		'Past tense': 'They followed the map to find the hidden treasure.',
		'Pasado simple': 'Siguieron el mapa para encontrar el tesoro escondido.',
		'Past participle': 'The rules were followed to ensure fairness.',
		'Pasado participio': 'Se siguieron las reglas para garantizar la equidad.',
		Gerund: 'Following your passion can lead to a fulfilling career.',
		Gerundio: 'Seguir tu pasión puede llevar a una carrera satisfactoria.',
	},
	{
		verb: 'To help',
		verbo: 'ayudar',
		'Infinitive present': 'He likes to help his neighbors with their yard work.',
		'Infinitivo presente': 'Le gusta ayudar a sus vecinos con su trabajo de jardinería.',
		'Past tense': 'She helped her friend move to a new apartment.',
		'Pasado simple': 'Ayudó a su amiga a mudarse a un nuevo apartamento.',
		'Past participle': 'The injured hiker was helped down the mountain by the rescue team.',
		'Pasado participio': 'El excursionista herido fue ayudado a bajar de la montaña por el equipo de rescate.',
		Gerund: 'Helping others can make you feel good about yourself.',
		Gerundio: 'Ayudar a los demás puede hacerte sentir bien contigo mismo.',
	},
	{
		verb: 'To hurry',
		verbo: 'apresurarse',
		'Infinitive present': 'We need to hurry if we want to catch the train.',
		'Infinitivo presente': 'Necesitamos apurarnos si queremos tomar el tren.',
		'Past tense': 'She hurried to finish her work before the deadline.',
		'Pasado simple': 'Se apresuró a terminar su trabajo antes del plazo.',
		'Past participle': 'The task was hurried due to lack of time.',
		'Pasado participio': 'La tarea se apuró debido a la falta de tiempo.',
		Gerund: "Hurrying can lead to mistakes, so it's important to take your time.",
		Gerundio: 'Apresurarse puede llevar a errores, por lo que es importante tomarse el tiempo necesario.',
	},
	{
		verb: 'To intend',
		verbo: 'tener laintención',
		'Infinitive present': 'She intends to travel around the world someday.',
		'Infinitivo presente': 'Tiene la intención de viajar por el mundo algún día.',
		'Past tense': 'He intended to study law, but changed his mind after taking an art class.',
		'Pasado simple':
			'Tenía la intención de estudiar derecho, pero cambió de opinión después de tomar una clase de arte.',
		'Past participle': 'The message was intended for his boss, but he accidentally sent it to a coworker.',
		'Pasado participio':
			'El mensaje estaba destinado a su jefe, pero accidentalmente lo envió a un compañero de trabajo.',
		Gerund: 'Intending to do something is the first step towards achieving your goals.',
		Gerundio: 'Tener la intención de hacer algo es el primer paso para alcanzar tus metas.',
	},
	{
		verb: 'To jump',
		verbo: 'saltar',
		'Infinitive present': 'He likes to jump rope for exercise.',
		'Infinitivo presente': 'Le gusta saltar la cuerda para hacer ejercicio.',
		'Past tense': 'She jumped over the puddle to avoid getting her shoes wet.',
		'Pasado simple': 'Saltó sobre el charco para evitar mojar sus zapatos.',
		'Past participle': 'The horse jumped over the fence and ran into the field.',
		'Pasado participio': 'El caballo saltó sobre la cerca y corrió hacia el campo.',
		Gerund: 'Jumping is a great way to improve your cardiovascular health.',
		Gerundio: 'Saltar es una excelente manera de mejorar tu salud cardiovascular.',
	},
	{
		verb: 'To learn',
		verbo: 'aprender',
		'Infinitive present': 'She wants to learn how to speak French fluently.',
		'Infinitivo presente': 'Quiere aprender a hablar francés con fluidez.',
		'Past tense': 'He learned how to play the guitar from his father.',
		'Pasado simple': 'Aprendió a tocar la guitarra de su padre.',
		'Past participle': 'The lesson was learned the hard way.',
		'Pasado participio': 'La lección fue aprendida de la manera difícil.',
		Gerund: 'Learning new skills can help you grow and develop as a person.',
		Gerundio: 'Aprender nuevas habilidades puede ayudarte a crecer y desarrollarte como persona.',
	},
	{
		verb: 'To lie',
		verbo: 'mentir',
		'Infinitive present': "He knows it's wrong to lie to his parents.",
		'Infinitivo presente': 'Sabe que es incorrecto mentirle a sus padres.',
		'Past tense': 'She lied about her age to get into the nightclub.',
		'Pasado simple': 'Mintió sobre su edad para entrar en el club nocturno.',
		'Past participle': 'The truth was revealed after he had lied to his boss.',
		'Pasado participio': 'La verdad fue revelada después de que había mentido a su jefe.',
		Gerund: 'Lying can damage relationships and erode trust.',
		Gerundio: 'Mentir puede dañar las relaciones y erosionar la confianza.',
	},
	{
		verb: 'To like',
		verbo: 'gustar',
		'Infinitive present': 'She likes to read books on the beach.',
		'Infinitivo presente': 'Le gusta leer libros en la playa.',
		'Past tense': 'He liked the movie so much that he saw it twice.',
		'Pasado simple': 'Le gustó tanto la película que la vio dos veces.',
		'Past participle': 'The food was liked by everyone at the party.',
		'Pasado participio': 'La comida fue gustada por todos en la fiesta.',
		Gerund: 'Liking something is a matter of personal preference.',
		Gerundio: 'Gustar algo es una cuestión de preferencia personal.',
	},
	{
		verb: 'To listen',
		verbo: 'escuchar',
		'Infinitive present': 'He likes to listen to music while he works.',
		'Infinitivo presente': 'Le gusta escuchar música mientras trabaja.',
		'Past tense': "She listened to her friend's advice and avoided making a mistake.",
		'Pasado simple': 'Escuchó el consejo de su amigo y evitó cometer un error.',
		'Past participle': 'The song was listened to by millions of people around the world.',
		'Pasado participio': 'La canción fue escuchada por millones de personas en todo el mundo.',
		Gerund: 'Listening is an important skill for effective communication.',
		Gerundio: 'Escuchar es una habilidad importante para una comunicación efectiva.',
	},
	{
		verb: 'To live',
		verbo: 'vivir',
		'Infinitive present': 'They live in a small apartment in the city.',
		'Infinitivo presente': 'Viven en un pequeño apartamento en la ciudad.',
		'Past tense': 'She lived in Paris for two years before moving back to the US.',
		'Pasado simple': 'Vivió en París durante dos años antes de regresar a los Estados Unidos.',
		'Past participle': 'The town is well-known for its lively nightlife and vibrant cultural scene.',
		'Pasado participio': 'El pueblo es conocido por su animada vida nocturna y su vibrante escena cultural.',
		Gerund: 'Living life to the fullest means embracing new experiences and taking risks.',
		Gerundio: 'Vivir la vida al máximo significa abrazar nuevas experiencias y tomar riesgos.',
	},
	{
		verb: 'To look',
		verbo: 'mirar',
		'Infinitive present': 'She likes to look at the stars at night.',
		'Infinitivo presente': 'Le gusta mirar las estrellas por la noche.',
		'Past tense': 'He looked out the window and saw the snow falling.',
		'Pasado simple': 'Miró por la ventana y vio la nieve cayendo.',
		'Past participle': 'The painting looked old and worn, but was actually a replica.',
		'Pasado participio': 'El cuadro parecía viejo y desgastado, pero en realidad era una réplica.',
		Gerund: 'Looking for a job can be a challenging and time-consuming process.',
		Gerundio: 'Buscar trabajo puede ser un proceso desafiante y que consume tiempo.',
	},
	{
		verb: 'To love',
		verbo: 'amar',
		'Infinitive present': 'They love spending time together on the weekends.',
		'Infinitivo presente': 'Les encanta pasar tiempo juntos los fines de semana.',
		'Past tense': 'She loved the movie so much that she cried at the end.',
		'Pasado simple': 'Le encantó tanto la película que lloró al final.',
		'Past participle': 'The couple was loved and respected by their community.',
		'Pasado participio': 'La pareja era amada y respetada por su comunidad.',
		Gerund: 'Loving yourself is an important part of living a happy and fulfilling life.',
		Gerundio: 'Amarse a sí mismo es una parte importante de vivir una vida feliz y satisfactoria.',
	},
	{
		verb: 'To miss',
		verbo: 'extrañar',
		'Infinitive present': 'He misses his family who lives in another country.',
		'Infinitivo presente': 'Extraña a su familia que vive en otro país.',
		'Past tense': 'She missed her flight and had to book another one.',
		'Pasado simple': 'Perdió su vuelo y tuvo que reservar otro.',
		'Past participle': 'The opportunity was missed due to lack of preparation.',
		'Pasado participio': 'Se perdió la oportunidad debido a la falta de preparación.',
		Gerund: 'Missing someone can be a difficult feeling to cope with.',
		Gerundio: 'Extrañar a alguien puede ser un sentimiento difícil de sobrellevar.',
	},
	{
		verb: 'To name',
		verbo: 'nombrar',
		'Infinitive present': 'They are going to name their new puppy after their favorite movie character.',
		'Infinitivo presente': 'Van a nombrar a su nuevo cachorro con el nombre de su personaje de película favorito.',
		'Past tense': 'She named her daughter after her grandmother.',
		'Pasado simple': 'Nombró a su hija con el nombre de su abuela.',
		'Past participle': 'The new bridge was named after a local hero.',
		'Pasado participio': 'El nuevo puente fue nombrado en honor a un héroe local.',
		Gerund: 'Naming things is an important part of language and communication.',
		Gerundio: 'Nombrar cosas es una parte importante del lenguaje y la comunicación.',
	},
	{
		verb: 'To need',
		verbo: 'necesitar',
		'Infinitive present': 'He needs a cup of coffee to start his day.',
		'Infinitivo presente': 'Necesita una taza de café para empezar su día.',
		'Past tense': 'She needed a new phone because her old one was broken.',
		'Pasado simple': 'Necesitaba un teléfono nuevo porque el antiguo estaba roto.',
		'Past participle': 'The help was needed to complete the project on time.',
		'Pasado participio': 'Se necesitaba ayuda para completar el proyecto a tiempo.',
		Gerund: 'Needing help is not a sign of weakness, but rather a part of being human.',
		Gerundio: 'Necesitar ayuda no es una señal de debilidad, sino más bien una parte de ser humano.',
	},
	{
		verb: 'To open',
		verbo: 'abrir',
		'Infinitive present': 'She opens the window to let fresh air in.',
		'Infinitivo presente': 'Abre la ventana para dejar entrar el aire fresco.',
		'Past tense': 'He opened the gift and was pleasantly surprised.',
		'Pasado simple': 'Abrió el regalo y se sorprendió gratamente.',
		'Past participle': 'The store was opened early to accommodate customers.',
		'Pasado participio': 'La tienda se abrió temprano para acomodar a los clientes.',
		Gerund: 'Opening your mind to new ideas can lead to personal growth.',
		Gerundio: 'Abrir tu mente a nuevas ideas puede llevarte al crecimiento personal.',
	},
	{
		verb: 'To order',
		verbo: 'ordenar/pedir',
		'Infinitive present': 'They like to order pizza for dinner on Fridays.',
		'Infinitivo presente': 'Les gusta ordenar pizza para la cena los viernes.',
		'Past tense': 'She ordered a salad instead of fries with her meal.',
		'Pasado simple': 'Pidío una ensalada en lugar de papas fritas con su comida.',
		'Past participle': 'The books were ordered online and delivered to his doorstep.',
		'Pasado participio': 'Los libros se ordenaron en línea y se entregaron en su puerta.',
		Gerund: 'Ordering food at a restaurant can be a fun and enjoyable experience.',
		Gerundio: 'Ordenar comida en un restaurante puede ser una experiencia divertida y agradable.',
	},
	{
		verb: 'To plan',
		verbo: 'planificar',
		'Infinitive present': 'He likes to plan his vacations well in advance.',
		'Infinitivo presente': 'Le gusta planificar sus vacaciones con mucha anticipación.',
		'Past tense': 'She planned a surprise birthday party for her friend.',
		'Pasado simple': 'Planificó una fiesta sorpresa de cumpleaños para su amiga.',
		'Past participle': 'The event was planned carefully to ensure its success.',
		'Pasado participio': 'El evento fue planeado cuidadosamente para garantizar su éxito.',
		Gerund: 'Planning your day can help you stay organized and productive.',
		Gerundio: 'Planificar tu día puede ayudarte a mantenerte organizado y productivo.',
	},
	{
		verb: 'To plant',
		verbo: 'plantar',
		'Infinitive present': 'They like to plant flowers in their garden every spring.',
		'Infinitivo presente': 'Les gusta plantar flores en su jardín cada primavera.',
		'Past tense': 'He planted a tree in his backyard last year.',
		'Pasado simple': 'Plantó un árbol en su patio trasero el año pasado.',
		'Past participle': 'The garden was planted with a variety of vegetables and herbs.',
		'Pasado participio': 'El jardín fue plantado con una variedad de verduras y hierbas.',
		Gerund: 'Planting trees can help reduce the carbon footprint and combat climate change.',
		Gerundio: 'Plantar árboles puede ayudar a reducir la huella de carbono y combatir el cambio climático.',
	},
	{
		verb: 'To play',
		verbo: 'jugar',
		'Infinitive present': 'She likes to play tennis with her friends on the weekends.',
		'Infinitivo presente': 'Le gusta jugar tenis con sus amigos los fines de semana.',
		'Past tense': 'He played soccer in high school and was on the varsity team.',
		'Pasado simple': 'Jugó al fútbol en la escuela secundaria y estuvo en el equipo varsity.',
		'Past participle': 'The game was played in the park on a sunny afternoon.',
		'Pasado participio': 'El juego se jugó en el parque en una tarde soleada.',
		Gerund: 'Playing sports can help improve your physical health and mental well-being.',
		Gerundio: 'Jugar deportes puede ayudar a mejorar tu salud física y bienestar mental.',
	},
	{
		verb: 'To point',
		verbo: 'señalar',
		'Infinitive present': 'He likes to point out constellations in the night sky.',
		'Infinitivo presente': 'Le gusta señalar las constelaciones en el cielo nocturno.',
		'Past tense': 'She pointed to the map to show where they were going.',
		'Pasado simple': 'Señaló el mapa para mostrar dónde iban.',
		'Past participle': 'The problem was pointed out during the meeting.',
		'Pasado participio': 'El problema fue señalado durante la reunión.',
		Gerund: 'Pointing out mistakes can be a helpful way to improve performance.',
		Gerundio: 'Señalar errores puede ser una forma útil de mejorar el rendimiento.',
	},
	{
		verb: 'To practice',
		verbo: 'practicar',
		'Infinitive present': 'They practice yoga together every morning.',
		'Infinitivo presente': 'Practican yoga juntos todas las mañanas.',
		'Past tense': 'She practiced the piano for three hours every day.',
		'Pasado simple': 'Practicaba el piano durante tres horas todos los días.',
		'Past participle': 'The routine was practiced until it was perfect.',
		'Pasado participio': 'La rutina se practicó hasta que fuera perfecta.',
		Gerund: 'Practicing a skill can help improve proficiency and mastery.',
		Gerundio: 'Practicar una habilidad puede ayudar a mejorar la competencia y el dominio.',
	},
	{
		verb: 'To push',
		verbo: 'empujar',
		'Infinitive present': 'He pushes the shopping cart while she selects the items.',
		'Infinitivo presente': 'Empuja el carrito de compras mientras ella selecciona los artículos.',
		'Past tense': 'She pushed her way through the crowd to get to the front.',
		'Pasado simple': 'Se abrió camino a empujones entre la multitud para llegar al frente.',
		'Past participle': 'The door was pushed open with great effort.',
		'Pasado participio': 'La puerta se abrió a empujones con gran esfuerzo.',
		Gerund: 'Pushing a heavy object requires strength and effort.',
		Gerundio: 'Empujar un objeto pesado requiere fuerza y esfuerzo.',
	},
	{
		verb: 'To rain',
		verbo: 'llover',
		'Infinitive present': "It's raining outside, so bring an umbrella.",
		'Infinitivo presente': 'Está lloviendo afuera, así que trae un paraguas.',
		'Past tense': 'It rained all weekend, so they stayed indoors.',
		'Pasado simple': 'Llovió todo el fin de semana, así que se quedaron adentro.',
		'Past participle': 'The roads were flooded after heavy rainfall.',
		'Pasado participio': 'Las carreteras estaban inundadas después de una lluvia intensa.',
		Gerund: 'Walking in the rain can be a fun and adventurous experience.',
		Gerundio: 'Caminar bajo la lluvia puede ser una experiencia divertida y aventurera.',
	},
	{
		verb: 'To remember',
		verbo: 'recordar',
		'Infinitive present': 'He always sets a reminder to remember important dates.',
		'Infinitivo presente': 'Siempre establece un recordatorio para recordar las fechas importantes.',
		'Past tense': 'She remembered the song from her childhood and sang it aloud.',
		'Pasado simple': 'Recordó la canción de su infancia y la cantó en voz alta.',
		'Past participle': 'The event was remembered for years to come.',
		'Pasado participio': 'El evento fue recordado durante años.',
		Gerund: 'Remembering to be grateful for what you have can bring happiness and contentment.',
		Gerundio: 'Recordar ser agradecido por lo que tienes puede traer felicidad y satisfacción.',
	},
	{
		verb: 'To rent',
		verbo: 'alquilar',
		'Infinitive present': 'They rent an apartment in the city.',
		'Infinitivo presente': 'Alquilan un apartamento en la ciudad.',
		'Past tense': 'She rented a car for the weekend getaway.',
		'Pasado simple': 'Alquiló un auto para la escapada de fin de semana.',
		'Past participle': 'The house was rented out to vacationers during the summer.',
		'Pasado participio': 'La casa se alquiló a vacacionistas durante el verano.',
		Gerund: 'Renting a movie online is a convenient way to watch it at home.',
		Gerundio: 'Alquilar una película en línea es una forma conveniente de verla en casa.',
	},
	{
		verb: 'To repeat',
		verbo: 'repetir',
		'Infinitive present': 'He likes to repeat the phrases to practice his pronunciation.',
		'Infinitivo presente': 'Le gusta repetir las frases para practicar su pronunciación.',
		'Past tense': 'She repeated the instructions to make sure she understood them.',
		'Pasado simple': 'Repitió las instrucciones para asegurarse de entenderlas.',
		'Past participle': 'The song was repeated several times during the concert.',
		'Pasado participio': 'La canción se repitió varias veces durante el concierto.',
		Gerund: 'Repeating a task can help improve skills and proficiency.',
		Gerundio: 'Repetir una tarea puede ayudar a mejorar habilidades y competencia.',
	},
	{
		verb: 'To resist',
		verbo: 'resistir',
		'Infinitive present': 'They try to resist eating junk food.',
		'Infinitivo presente': 'Intentan resistir comer comida chatarra.',
		'Past tense': 'She resisted the temptation to buy the expensive dress.',
		'Pasado simple': 'Resistió la tentación de comprar el vestido caro.',
		'Past participle': 'The disease is resistant to antibiotics.',
		'Pasado participio': 'La enfermedad es resistente a los antibióticos.',
		Gerund: 'Resisting peer pressure can be a challenging but important part of growing up.',
		Gerundio: 'Resistir la presión de los amigos puede ser una parte desafiante pero importante del crecimiento.',
	},
	{
		verb: 'To show',
		verbo: 'mostrar',
		'Infinitive present': 'He shows pictures of his travels to his friends.',
		'Infinitivo presente': 'Muestra fotos de sus viajes a sus amigos.',
		'Past tense': 'She showed the way to the nearest hospital.',
		'Pasado simple': 'Mostró el camino hacia el hospital más cercano.',
		'Past participle': 'The art exhibition showed works from local artists.',
		'Pasado participio': 'La exposición de arte mostró obras de artistas locales.',
		Gerund: 'Showing appreciation and gratitude can strengthen relationships.',
		Gerundio: 'Mostrar aprecio y gratitud puede fortalecer las relaciones.',
	},
	{
		verb: 'To smoke',
		verbo: 'fumar',
		'Infinitive present': "He doesn't smoke cigarettes anymore.",
		'Infinitivo presente': 'Ya no fuma cigarrillos.',
		'Past tense': 'She smoked a cigar to celebrate her promotion.',
		'Pasado simple': 'Fumó un cigarro para celebrar su ascenso.',
		'Past participle': 'The air in the room was thick with smoke from the fire.',
		'Pasado participio': 'El aire en la habitación estaba espeso con humo del fuego.',
		Gerund: 'Smoking can have negative health effects, such as lung cancer and heart disease.',
		Gerundio: 'Fumar puede tener efectos negativos en la salud, como el cáncer de pulmón y enfermedades cardíacas.',
	},
	{
		verb: 'To start',
		verbo: 'empezar',
		'Infinitive present': 'She starts her day with a cup of coffee.',
		'Infinitivo presente': 'Empieza su día con una taza de café.',
		'Past tense': 'He started his own business last year.',
		'Pasado simple': 'Empezó su propio negocio el año pasado.',
		'Past participle': 'The race had already started when they arrived.',
		'Pasado participio': 'La carrera ya había empezado cuando llegaron.',
		Gerund: 'Starting a new hobby can be a fun and rewarding experience.',
		Gerundio: 'Empezar un nuevo pasatiempo puede ser una experiencia divertida y gratificante.',
	},
	{
		verb: 'To stay',
		verbo: 'quedarse',
		'Infinitive present': 'They like to stay at home on weekends.',
		'Infinitivo presente': 'Les gusta quedarse en casa los fines de semana.',
		'Past tense': 'She stayed in a hotel during her vacation.',
		'Pasado simple': 'Se quedó en un hotel durante sus vacaciones.',
		'Past participle': 'The guests were offered a complimentary stay at the hotel.',
		'Pasado participio': 'A los huéspedes se les ofreció una estancia gratuita en el hotel.',
		Gerund: 'Staying active and healthy can help improve quality of life.',
		Gerundio: 'Quedarse activo y saludable puede ayudar a mejorar la calidad de vida.',
	},
	{
		verb: 'To stop',
		verbo: 'parar',
		'Infinitive present': 'He stops to read the newspaper on his way to work.',
		'Infinitivo presente': 'Se detiene a leer el periódico en su camino al trabajo.',
		'Past tense': 'She stopped eating meat last year.',
		'Pasado simple': 'Dejó de comer carne el año pasado.',
		'Past participle': 'The music had stopped by the time they arrived.',
		'Pasado participio': 'La música había parado cuando llegaron.',
		Gerund: 'Stopping to take breaks can help prevent burnout and increase productivity.',
		Gerundio: 'Parar para tomar descansos puede ayudar a prevenir el agotamiento y aumentar la productividad.',
	},
	{
		verb: 'To study',
		verbo: 'estudiar',
		'Infinitive present': 'They study together at the library.',
		'Infinitivo presente': 'Estudian juntos en la biblioteca.',
		'Past tense': 'He studied biology in college.',
		'Pasado simple': 'Estudió biología en la universidad.',
		'Past participle': 'The research was studied extensively before being published.',
		'Pasado participio': 'La investigación fue estudiada extensamente antes de ser publicada.',
		Gerund: 'Studying for exams can be a challenging but rewarding experience.',
		Gerundio: 'Estudiar para exámenes puede ser una experiencia desafiante pero gratificante.',
	},
	{
		verb: 'To talk',
		verbo: 'hablar',
		'Infinitive present': 'She talks to her family on the phone every day.',
		'Infinitivo presente': 'Habla con su familia por teléfono todos los días.',
		'Past tense': 'He talked to his boss about a raise.',
		'Pasado simple': 'Habló con su jefe sobre un aumento.',
		'Past participle': 'The issue was talked about extensively during the meeting.',
		'Pasado participio': 'El tema se habló extensamente durante la reunión.',
		Gerund: 'Talking about your feelings with a trusted friend can help relieve stress and anxiety.',
		Gerundio: 'Hablar de tus sentimientos con un amigo de confianza puede ayudar a aliviar el estrés y la ansiedad.',
	},
	{
		verb: 'To travel',
		verbo: 'viajar',
		'Infinitive present': 'They love to travel to new places.',
		'Infinitivo presente': 'Les encanta viajar a lugares nuevos.',
		'Past tense': 'She traveled to Europe last summer.',
		'Pasado simple': 'Viajó a Europa el verano pasado.',
		'Past participle': 'The tickets had already been booked for the travel plans.',
		'Pasado participio': 'Los boletos ya habían sido reservados para los planes de viaje.',
		Gerund: 'Traveling can broaden your horizons and expose you to new cultures.',
		Gerundio: 'Viajar puede ampliar tus horizontes y exponerte a nuevas culturas.',
	},
	{
		verb: 'To try',
		verbo: 'intentar',
		'Infinitive present': 'He tries to exercise every day.',
		'Infinitivo presente': 'Intenta hacer ejercicio todos los días.',
		'Past tense': 'She tried a new restaurant last night.',
		'Pasado simple': 'Probó un restaurante nuevo anoche.',
		'Past participle': 'The experiment had been tried several times with varying results.',
		'Pasado participio': 'El experimento había sido intentado varias veces con resultados variables.',
		Gerund: 'Trying new things can be scary but can also lead to personal growth and development.',
		Gerundio: 'Intentar cosas nuevas puede ser aterrador pero también puede conducir al crecimiento y desarrollo personal.',
	},
	{
		verb: 'To turn',
		verbo: 'girar',
		'Infinitive present': 'He turns left at the intersection.',
		'Infinitivo presente': 'Gira a la izquierda en la intersección.',
		'Past tense': 'She turned off the lights before leaving the room.',
		'Pasado simple': 'Apagó las luces antes de salir de la habitación.',
		'Past participle': 'The page had already been turned when he noticed the mistake.',
		'Pasado participio': 'La página ya había sido girada cuando notó el error.',
		Gerund: 'Turning your attention to the present moment can help reduce stress and anxiety.',
		Gerundio: 'Girar tu atención al momento presente puede ayudar a reducir el estrés y la ansiedad.',
	},
	{
		verb: 'To use',
		verbo: 'usar',
		'Infinitive present': 'They use their phones to stay in touch.',
		'Infinitivo presente': 'Usan sus teléfonos para mantenerse en contacto.',
		'Past tense': 'He used a hammer to fix the fence.',
		'Pasado simple': 'Usó un martillo para arreglar la cerca.',
		'Past participle': 'The product is used by many people for its effectiveness.',
		'Pasado participio': 'El producto es usado por muchas personas por su eficacia.',
		Gerund: 'Using technology can make many tasks more efficient and convenient.',
		Gerundio: 'Usar la tecnología puede hacer muchas tareas más eficientes y convenientes.',
	},
	{
		verb: 'To visit',
		verbo: 'visitar',
		'Infinitive present': 'She visits her grandparents every weekend.',
		'Infinitivo presente': 'Visita a sus abuelos todos los fines de semana.',
		'Past tense': 'He visited New York City last year.',
		'Pasado simple': 'Visitó la ciudad de Nueva York el año pasado.',
		'Past participle': 'The museum has been visited by millions of people over the years.',
		'Pasado participio': 'El museo ha sido visitado por millones de personas a lo largo de los años.',
		Gerund: 'Visiting new places can broaden your perspective and open your mind to new ideas.',
		Gerundio: 'Visitar lugares nuevos puede ampliar tu perspectiva y abrir tu mente a nuevas ideas.',
	},
	{
		verb: 'To wait',
		verbo: 'esperar',
		'Infinitive present': 'She is waiting for her friend to arrive.',
		'Infinitivo presente': 'Está esperando a que llegue su amiga.',
		'Past tense': 'He waited in line for two hours to buy tickets.',
		'Pasado simple': 'Esperó en la fila durante dos horas para comprar boletos.',
		'Past participle': 'The package had been waiting for her at the post office.',
		'Pasado participio': 'El paquete había estado esperando por ella en la oficina de correos.',
		Gerund: 'Waiting patiently can be a valuable life skill that can help build resilience and perseverance.',
		Gerundio: 'Esperar pacientemente puede ser una habilidad valiosa en la vida que puede ayudar a construir la resiliencia y la perseverancia.',
	},
	{
		verb: 'To walk',
		verbo: 'caminar',
		'Infinitive present': 'They like to walk in the park on weekends.',
		'Infinitivo presente': 'Les gusta caminar en el parque los fines de semana.',
		'Past tense': 'She walked home from work yesterday.',
		'Pasado simple': 'Caminó a casa desde el trabajo ayer.',
		'Past participle': 'The path had been walked by many hikers before.',
		'Pasado participio': 'El camino había sido caminado por muchos excursionistas antes.',
		Gerund: 'Walking can be a low-impact exercise that can help improve cardiovascular health and overall well-being.',
		Gerundio:
			'Caminar puede ser un ejercicio de bajo impacto que puede ayudar a mejorar la salud cardiovascular y el bienestar general.',
	},
	{
		verb: 'To want',
		verbo: 'querer',
		'Infinitive present': 'He wants a new car for his birthday.',
		'Infinitivo presente': 'Quiere un coche nuevo para su cumpleaños.',
		'Past tense': 'She wanted to be a doctor when she was a child.',
		'Pasado simple': 'Quería ser doctora cuando era niña.',
		'Past participle': 'The book was wanted by many readers for its popularity.',
		'Pasado participio': 'El libro fue querido por muchos lectores por su popularidad.',
		Gerund: 'Wanting more material possessions can lead to a never-ending cycle of desire and dissatisfaction.',
		Gerundio: 'Querer más posesiones materiales puede llevar a un ciclo interminable de deseo y insatisfacción.',
	},
	{
		verb: 'To wash',
		verbo: 'lavar',
		'Infinitive present': 'They wash their clothes every week.',
		'Infinitivo presente': 'Lavan su ropa todas las semanas.',
		'Past tense': 'He washed the dishes after dinner.',
		'Pasado simple': 'Lavó los platos después de la cena.',
		'Past participle': 'The clothes had been washed and dried before being folded.',
		'Pasado participio': 'La ropa había sido lavada y secada antes de ser doblada.',
		Gerund: 'Washing your hands frequently can help prevent the spread of germs and illnesses.',
		Gerundio: 'Lavarse las manos con frecuencia puede ayudar a prevenir la propagación de gérmenes y enfermedades.',
	},
	{
		verb: 'To wish',
		verbo: 'desear',
		'Infinitive present': 'She wishes she could travel more often.',
		'Infinitivo presente': 'Desea poder viajar con más frecuencia.',
		'Past tense': 'He wished he had studied harder for the test.',
		'Pasado simple': 'Deseó haber estudiado más para el examen.',
		'Past participle': 'The wish had been granted by the time she woke up.',
		'Pasado participio': 'El deseo había sido concedido cuando se despertó.',
		Gerund: 'Wishing for a better future can motivate us to work towards our goals.',
		Gerundio: 'Desear un futuro mejor puede motivarnos a trabajar hacia nuestras metas.',
	},
	{
		verb: 'To work',
		verbo: 'trabajar',
		'Infinitive present': 'They work at a restaurant in downtown.',
		'Infinitivo presente': 'Trabajan en un restaurante en el centro.',
		'Past tense': 'She worked overtime to finish the project on time.',
		'Pasado simple': 'Trabajó horas extras para terminar el proyecto a tiempo.',
		'Past participle': 'The report had been worked on by multiple people before being submitted.',
		'Pasado participio': 'El informe había sido trabajado por varias personas antes de ser presentado.',
		Gerund: 'Working collaboratively with others can help generate new ideas and improve problem-solving skills.',
		Gerundio: 'Trabajar colaborativamente con otros puede ayudar a generar nuevas ideas y mejorar las habilidades para resolver problemas.',
	},
];
