export default [
	[
		'Inf. present: 	  accept',
		'I always accept invitations to parties.',
		'Siempre acepto invitaciones a fiestas.',
		// 'Past tense: 	  accepted',
		// 'She accepted the job offer last week.',
		// 'Aceptó la oferta de trabajo la semana pasada.',
		// 'Past participle: 	   accepted',
		// 'The package was accepted by the recipient.',
		// 'El paquete fue aceptado por el destinatario.',
		// 'Gerund: 	   accepting',
		// 'He is not used to accepting help from others.',
		// 'No está acostumbrado a aceptar ayuda de otros.',
		'Inf. present: 	  accept',
		'I want to accept the invitation to the party.',
		'Quiero aceptar la invitación a la fiesta.',
		'Inf. present: 	  accepts',
		'She accepts the job offer last week and now works there.',
		'Ella acepta la oferta de trabajo la semana pasada y ahora trabaja allí.',
		// 'Past tense: 	  accepted',
		// 'He accepted the award for Best Actor at the ceremony last night.',
		// 'Él aceptó el premio al Mejor Actor en la ceremonia de anoche.',
		// 'Past participle: 	   accepted',
		// 'I have accepted the terms of the contract.',
		// 'He aceptado los términos del contrato.',
		// 'Gerund: 	   accepting',
		// 'She is not used to accepting help from others.',
		// 'Ella no está acostumbrada a aceptar ayuda de otros.',
	],
	[
		'Inf. present: 	  answer',
		'They never answer their phones during meetings.',
		'Nunca responden sus teléfonos durante reuniones.',
		// 'Past tense: 	  answered',
		// 'She answered all the questions correctly on the exam.',
		// 'Respondió todas las preguntas correctamente en el examen.',
		// 'Past participle: 	   answered',
		// 'The letter has not been answered yet.',
		// 'La carta aún no ha sido respondida.',
		// 'Gerund: 	   answering',
		// 'He is good at answering emails promptly.',
		// 'Es bueno en responder correos electrónicos rápidamente.',
		'Inf. present: 	  answer',
		'He needs to answer the phone.',
		'Él necesita responder el teléfono.',
		'Inf. present: 	  answers',
		'She always answers my questions.',
		'Ella siempre responde mis preguntas.',
		// 'Past tense: 	  answered',
		// "He answered the interviewer's questions with confidence.",
		// 'Él respondió las preguntas del entrevistador con confianza.',
		// 'Past participle: 	   answered',
		// 'I have answered all of the questions on the quiz.',
		// 'He respondido todas las preguntas del cuestionario.',
		// 'Gerund: 	   answering',
		// 'She is used to answering emails every day.',
		// 'Ella está acostumbrada a responder correos electrónicos todos los días.',
	],
	[
		'Inf. present: 	  arrive',
		'They usually arrive at the office at 9 am.',
		'Por lo general llegan a la oficina a las 9 am.',
		// 'Past tense: 	  arrived',
		// 'We arrived at the airport two hours before the flight.',
		// 'Llegamos al aeropuerto dos horas antes del vuelo.',
		// 'Past participle: 	   arrived',
		// 'The package had already arrived when we got home.',
		// 'El paquete ya había llegado cuando llegamos a casa.',
		// 'Gerund: 	   arriving',
		// 'She hates arriving late to meetings.',
		// 'Odia llegar tarde a las reuniones.',
		'Inf. present: 	  arrive',
		'We plan to arrive at the airport two hours before our flight.',
		'Planeamos llegar al aeropuerto dos horas antes de nuestro vuelo.',
		'Inf. present: 	  arrives',
		'The train arrives at the station in five minutes.',
		'El tren llega a la estación en cinco minutos.',
		// 'Past tense: 	  arrived',
		// 'I arrived at the party late because of traffic.',
		// 'Llegué tarde a la fiesta por el tráfico.',
		// 'Past participle: 	   arrived',
		// 'She has just arrived home from work.',
		// 'Ella acaba de llegar a casa del trabajo.',
		// 'Gerund: 	   arriving',
		// 'He enjoys arriving early to avoid the crowds.',
		// 'A él le gusta llegar temprano para evitar las multitudes.',
	],
	[
		'Inf. present: 	  asks',
		'He always asks a lot of questions in class.',
		'Siempre hace muchas preguntas en clase.',
		// 'Past tense: 	  asked',
		// 'She asked me to help her with her homework.',
		// 'Me pidió que la ayudara con su tarea.',
		// 'Past participle: 	   asked',
		// 'He has never been asked to speak in public before.',
		// 'Nunca le han pedido que hable en público antes.',
		// 'Gerund: 	   asking',
		// 'They are not used to asking for help.',
		// 'No están acostumbrados a pedir ayuda.',
		'Inf. present: 	  ask',
		'I need to ask him a question.',
		'Necesito hacerle una pregunta.',
		'Inf. present: 	  asks',
		'She asks a lot of questions in class.',
		'Ella hace muchas preguntas en clase.',
		// 'Past tense: 	  asked',
		// 'He asked her out on a date last night.',
		// 'Anoche él la invitó a salir en una cita.',
		// 'Past participle: 	   asked',
		// 'I have asked for help, but no one seems to be available.',
		// 'He pedido ayuda, pero parece que nadie está disponible.',
		// 'Gerund: 	   Asking',
		// 'Asking for a raise can be intimidating.',
		// 'Pedir un aumento puede ser intimidante.',
	],
	[
		'Inf. present: 	  belongs',
		'The book belongs on the top shelf.',
		'El libro pertenece al estante superior.',
		// 'Past tense: 	  belonged',
		// 'The necklace belonged to her grandmother.',
		// 'El collar pertenecía a su abuela.',
		// 'Past participle: 	   belonged',
		// 'I have belonged to that club for five years.',
		// 'He pertenecido a ese club durante cinco años.',
		// 'Gerund: 	   belonging',
		// 'She enjoys belonging to a community group.',
		// 'Disfruta pertenecer a un grupo comunitario.',
		'Inf. present: 	  belongs',
		'The book belongs on the shelf.',
		'El libro pertenece a la estantería.',
		'belong',
		'The keys belong to the blue car.',
		'Las llaves pertenecen al coche azul.',
		// 'Past tense: 	  belonged',
		// 'She belonged to the drama club in high school.',
		// 'Ella pertenecía al club de teatro en la escuela secundaria.',
		// 'Past participle: 	   belongs',
		// 'This book belongs to me.',
		// 'Este libro me pertenece a mí.',
		// 'Gerund: 	   Belonging',
		// 'Belonging to a community can be very fulfilling.',
		// 'Pertenecer a una comunidad puede ser muy gratificante.',
	],
	[
		'Inf. present: 	  bother',
		"Please don't bother me while I'm working.",
		'Por favor, no me molestes mientras estoy trabajando.',
		// 'Past tense: 	  bothered',
		// 'He bothered his sister all day with his constant talking.',
		// 'Molesto a su hermana todo el día con su charla constante.',
		// 'Past participle: 	   bothered',
		// 'I was bothered by the loud noise outside my window.',
		// 'Me molestaba el ruido fuerte fuera de mi ventana.',
		// 'Gerund: 	   bothering',
		// 'Stop bothering me with all these questions.',
		// 'Deja de molestarme con todas estas preguntas.',
		'Inf. present: 	  bother',
		"Don't bother him, he's busy.",
		'No le molestes, está ocupado.',
		'Inf. present: 	  bothers',
		"Her loud music bothers me when I'm trying to work.",
		'Su música alta me molesta cuando estoy tratando de trabajar.',
		// 'Past tense: 	  bothered',
		// 'He bothered to read the instructions before starting the project.',
		// 'Se molestó en leer las instrucciones antes de empezar el proyecto.',
		// 'Past participle: 	   bother',
		// "I'm sorry to bother you, but do you have a minute to talk?",
		// 'Lo siento por molestarte, ¿tienes un minuto para hablar?',
		// 'Gerund: 	   Bothering',
		// 'Bothering others is not a good way to make friends.',
		// 'Molestar a los demás no es una buena manera de hacer amigos.',
	],
	[
		'Inf. present: 	  change',
		'She wants to change her hairstyle for the new year.',
		'Quiere cambiar su peinado para el nuevo año.',
		// 'Past tense: 	  changed',
		// 'They changed their plans at the last minute.',
		// 'Cambiaron sus planes en el último minuto.',
		// 'Past participle: 	   changed',
		// 'The company has changed its policy on vacation time.',
		// 'La empresa ha cambiado su política sobre el tiempo de vacaciones.',
		// 'Gerund: 	   changing',
		// 'He is considering changing his major in college.',
		// 'Está considerando cambiar su especialización en la universidad.',
		'Inf. present: 	  change',
		'I want to change my hairstyle.',
		'Quiero cambiar mi peinado.',
		'Inf. present: 	  changes',
		'He changes his mind a lot.',
		'Él cambia de opinión muchas veces.',
		// 'Past tense: 	  changed',
		// 'She changed her phone number last month.',
		// 'Ella cambió su número de teléfono el mes pasado.',
		// 'Past participle: 	   changed',
		// 'I have changed my password for security reasons.',
		// 'He cambiado mi contraseña por motivos de seguridad.',
		// 'Gerund: 	   Changing',
		// 'Changing your diet can have a big impact on your health.',
		// 'Cambiar tu dieta puede tener un gran impacto en tu salud.',
	],
	[
		'Inf. present: 	  cleans',
		'She cleans the kitchen every night after dinner.',
		'Limpia la cocina todas las noches después de la cena.',
		// 'Past tense: 	  cleaned',
		// 'He cleaned the garage on Saturday morning.',
		// 'Limpió el garaje el sábado por la mañana.',
		// 'Past participle: 	   cleaned',
		// 'The house was cleaned from top to bottom before the guests arrived.',
		// 'La casa fue limpiada de arriba abajo antes de que llegaran los invitados.',
		// 'Gerund: 	   cleaning',
		// "She is always cleaning her house, even though it's already spotless.",
		// 'Siempre está limpiando su casa, aunque ya esté impecable.',
		'Inf. present: 	  clean',
		'We need to clean the house before the guests arrive.',
		'Necesitamos limpiar la casa antes de que lleguen los invitados.',
		'Inf. present: 	  cleans',
		'She cleans the kitchen every night after dinner.',
		'Ella limpia la cocina todas las noches después de cenar.',
		// 'Past tense: 	  cleaned',
		// 'He cleaned his car last weekend.',
		// 'Limpió su coche el fin de semana pasado.',
		// 'Past participle: 	   cleaned',
		// "I have cleaned the bathroom, so it's ready for guests.",
		// 'He limpiado el baño, así que está listo para los invitados.',
		// 'Gerund: 	   Cleaning',
		// 'Cleaning up after a party is never fun.',
		// 'Limpiar después de una fiesta nunca es divertido.',
	],
	[
		'Inf. present: 	  climb',
		'They like to climb mountains in their free time.',
		'Les gusta escalar montañas en su tiempo libre.',
		// 'Past tense: 	  climbed',
		// 'He climbed the tree to get a better view of the park.',
		// 'Escaló el árbol para tener una mejor vista del parque.',
		// 'Past participle: 	   climbed',
		// 'She has climbed the highest peak in the state.',
		// 'Ha escalado la cumbre más alta del estado.',
		// 'Gerund: 	   Climbing',
		// 'Climbing is his favorite hobby.',
		// 'Escalar es su pasatiempo favorito.',
		'Inf. present: 	  climb',
		'We plan to climb the mountain next summer.',
		'Planeamos escalar la montaña el próximo verano.',
		'Inf. present: 	  climbs',
		'He climbs the stairs instead of taking the elevator.',
		'Él sube las escaleras en lugar de tomar el ascensor.',
		// 'Past tense: 	  climbed',
		// 'They climbed to the top of the tower and took some amazing photos.',
		// 'Escalaron hasta la cima de la torre y tomaron algunas fotos increíbles.',
		// 'Past participle: 	   climbed',
		// "I have climbed this mountain before, and it's not easy.",
		// 'He escalado esta montaña antes, y no es fácil.',
		// 'Gerund: 	   Climbing',
		// 'Climbing a tree can be a fun activity for kids.',
		// 'Escalar un árbol puede ser una actividad divertida para los niños.',
	],
	[
		'Inf. present: 	  close',
		'Please close the door when you leave.',
		'Por favor, cierra la puerta cuando salgas.',
		// 'Past tense: 	  closed',
		// 'He closed the window before going to bed.',
		// 'Cerró la ventana antes de acostarse.',
		// 'Past participle: 	   closed',
		// 'The store was closed for renovations.',
		// 'La tienda estaba cerrada por renovaciones.',
		// 'Gerund: 	   Closing',
		// 'Closing the deal took longer than expected.',
		// 'Cerrar el trato llevó más tiempo de lo esperado.',
		'Inf. present: 	  close',
		'Please close the door behind you.',
		'Por favor, cierra la puerta detrás de ti.',
		'Inf. present: 	  closes',
		'The store closes at 9 pm every day.',
		'La tienda cierra a las 9 pm todos los días.',
		// 'Past tense: 	  closed',
		// 'He closed his laptop and went to bed.',
		// 'Cerró su laptop y se fue a dormir.',
		// 'Past participle: 	   closed',
		// 'I have closed the deal, and we are now partners.',
		// 'He cerrado el trato, y ahora somos socios.',
		// 'Gerund: 	   Closing',
		// 'Closing the door quietly, she left the room.',
		// 'Cerrando la puerta suavemente, ella salió de la habitación.',
	],
	[
		'Inf. present: 	  considering',
		'She is considering a job offer from another company.',
		'Está considerando una oferta de trabajo de otra empresa.',
		// 'Past tense: 	  considered',
		// 'We considered all the options before making a decision.',
		// 'Consideramos todas las opciones antes de tomar una decisión.',
		// 'Past participle: 	   considered',
		// 'He was considered the best candidate for the position.',
		// 'Fue considerado el mejor candidato para el puesto.',
		// 'Gerund: 	   Considering',
		// 'Considering the circumstances, he made the best choice.',
		// 'Considerando las circunstancias, tomó la mejor decisión.',
		'Inf. present: 	  consider',
		'I need to consider my options before making a decision.',
		'Necesito considerar mis opciones antes de tomar una decisión.',
		'Inf. present: 	  considers',
		'He considers himself lucky to have such a supportive family.',
		'Se considera afortunado de tener una familia tan solidaria.',
		// 'Past tense: 	  considered',
		// 'They considered several candidates before choosing the right person for the job.',
		// 'Consideraron varios candidatos antes de elegir a la persona adecuada para el trabajo.',
		// 'Past participle: 	   considered',
		// 'I have considered quitting my job and traveling the world.',
		// 'He considerado renunciar a mi trabajo y viajar por el mundo.',
		// 'Gerund: 	   Considering',
		// 'Considering the circumstances, I think we did the best we could.',
		// 'Considerando las circunstancias, creo que hicimos lo mejor que pudimos.',
	],
	[
		'Inf. present: 	  cook',
		'He likes to cook dinner for his family.',
		'Le gusta cocinar la cena para su familia.',
		// 'Past tense: 	  cooked',
		// 'She cooked a delicious meal for her guests.',
		// 'Cocinó una comida deliciosa para sus invitados.',
		// 'Past participle: 	   cooked',
		// 'The food was cooked to perfection.',
		// 'La comida fue cocinada a la perfección.',
		// 'Gerund: 	   Cooking',
		// 'Cooking is a great way to unwind after a long day.',
		// 'Cocinar es una gran manera de relajarse después de un largo día.',
		'Inf. present: 	  cook',
		'I love to cook Italian food.',
		'Me encanta cocinar comida italiana.',
		'Inf. present: 	  cooks',
		'She cooks dinner for her family every night.',
		'Cocina la cena para su familia todas las noches.',
		// 'Past tense: 	  cooked',
		// "He cooked a delicious meal for his girlfriend's birthday.",
		// 'Cocinó una comida deliciosa para el cumpleaños de su novia.',
		// 'Past participle: 	   cooked',
		// 'I have cooked this recipe before, and it always turns out well.',
		// 'He cocinado esta receta antes, y siempre queda bien.',
		// 'Gerund: 	   Cooking',
		// 'Cooking together can be a fun date night activity.',
		// 'Cocinar juntos puede ser una actividad divertida para una noche de cita.',
	],
	[
		'Inf. present: 	  count',
		'Can you count to ten in Spanish?',
		'¿Puedes contar hasta diez en español?',
		// 'Past tense: 	  counted',
		// 'She counted the money twice to make sure it was correct.',
		// 'Contó el dinero dos veces para asegurarse de que era correcto.',
		// 'Past participle: 	   counted',
		// 'The votes were counted and the winner was announced.',
		// 'Los votos fueron contados y el ganador fue anunciado.',
		// 'Gerund: 	   Counting',
		// 'Counting the number of stars in the sky is impossible.',
		// 'Contar el número de estrellas en el cielo es imposible.',
		'Inf. present: 	  count',
		'You can always count on me to help you.',
		'Siempre puedes contar conmigo para ayudarte.',
		'Inf. present: 	  counts',
		'He counts his blessings every day.',
		'Cuenta sus bendiciones todos los días.',
		// 'Past tense: 	  counted',
		// 'They counted the votes and announced the winner.',
		// 'Contaron los votos y anunciaron el ganador.',
		// 'Past participle: 	   counted',
		// 'I have counted the days until my vacation for months.',
		// 'He ha contado los días hasta mis vacaciones durante meses.',
		// 'Gerund: 	   Counting',
		// 'Counting sheep is a popular method to help you fall asleep.',
		// 'Contar ovejas es un método popular para ayudarte a dormir.',
	],
	[
		'Inf. present: 	  dance',
		'They love to dance at weddings.',
		'Les encanta bailar en las bodas.',
		// 'Past tense: 	  danced',
		// 'She danced with her father at her quinceañera.',
		// 'Bailó con su padre en su quinceañera.',
		// 'Past participle: 	   dance',
		// 'The dance floor was cleared for the performance.',
		// 'La pista de baile fue despejada para la presentación.',
		// 'Gerund: 	   Dancing',
		// 'Dancing is a fun way to stay active and healthy.',
		// 'Bailar es una manera divertida de mantenerse activo y saludable.',
		'Inf. present: 	  dance',
		'I want to learn how to dance salsa.',
		'Quiero aprender a bailar salsa.',
		'Inf. present: 	  dances',
		'She dances every Saturday night at the local club.',
		'Baila todos los sábados por la noche en el club local.',
		// 'Past tense: 	  danced',
		// 'We danced for hours at the wedding reception.',
		// 'Bailamos durante horas en la recepción de la boda.',
		// 'Past participle: 	   danced',
		// 'I have danced in many different countries around the world.',
		// 'He bailado en muchos países diferentes alrededor del mundo.',
		// 'Gerund: 	   Dancing',
		// 'Dancing is a great way to exercise and have fun at the same time.',
		// 'Bailar es una excelente manera de hacer ejercicio y divertirse al mismo tiempo.',
	],
	[
		'Inf. present: 	  dare',
		"He doesn't dare to jump off the diving board.",
		'No se atreve a saltar del trampolín.',
		// 'Past tense: 	  red',
		// 'She dared him to eat the spicy chili pepper.',
		// 'Le desafió a comer el chile picante.',
		// 'Past participle: 	   daring',
		// 'The stunt was daring and impressive.',
		// 'La acrobacia fue atrevida e impresionante.',
		// 'Gerund: 	   Daring',
		// 'Daring to dream big can lead to great things.',
		// 'Atreverse a soñar en grande puede llevar a grandes cosas.',
		'Inf. present: 	  dare',
		"I didn't dare to speak to him because he seemed angry.",
		'No me atreví a hablarle porque parecía enojado.',
		'Inf. present: 	  dares',
		'She dares to speak her mind even when others disagree with her.',
		'Se atreve a decir lo que piensa incluso cuando los demás no están de acuerdo con ella.',
		// 'Past tense: 	  dared',
		// 'He dared to climb the mountain even though it was dangerous.',
		// 'Se atrevió a subir la montaña aunque era peligroso.',
		// 'Past participle: 	   dared',
		// 'I have never dared to skydive, but maybe one day I will.',
		// 'Nunca me he atrevido a hacer paracaidismo, pero tal vez algún día lo haga.',
		// 'Gerund: 	   Daring',
		// 'Daring to take risks is an important part of personal growth.',
		// 'Atreverse a tomar riesgos es una parte importante del crecimiento personal.',
	],
	[
		'Inf. present: 	  dating',
		'She is dating her coworker.',
		'Sale con su compañero de trabajo.',
		// 'Past tense: 	  dated',
		// 'They dated for two years before getting married.',
		// 'Salieron durante dos años antes de casarse.',
		// 'Past participle: 	   dated',
		// 'The letter was dated April 1st.',
		// 'La carta estaba fechada el 1 de abril.',
		// 'Gerund: 	   Dating',
		// 'Dating can be a fun and exciting way to meet new people.',
		// 'Salir con alguien puede ser una forma divertida y emocionante de conocer gente nueva.',
		'Inf. present: 	  date',
		'She wants to date someone who shares her interests.',
		'Quiere salir con alguien que comparta sus intereses.',
		'Inf. present: 	  dates',
		'He dates a different person every week.',
		'Sale con una persona diferente cada semana.',
		// 'Past tense: 	  dated',
		// 'We dated for three years before getting married.',
		// 'Salimos juntos durante tres años antes de casarnos.',
		// 'Past participle: 	   dated',
		// 'I have dated people from many different cultures and backgrounds.',
		// 'He salido con personas de muchas culturas y antecedentes diferentes.',
		// 'Gerund: 	   Dating',
		// 'Dating can be a fun way to get to know someone new.',
		// 'Salir con alguien puede ser una forma divertida de conocer a alguien nuevo.',
	],
	[
		'Inf. present: 	  delivers',
		'The postman delivers mail to our house every day.',
		'El cartero entrega el correo a nuestra casa todos los días.',
		// 'Past tense: 	  delivered',
		// 'She delivered the package to the correct address.',
		// 'Entregó el paquete a la dirección correcta.',
		// 'Past participle: 	   delivered',
		// 'The speech was delivered with passion and enthusiasm.',
		// 'El discurso fue entregado con pasión y entusiasmo.',
		// 'Gerund: 	   Delivering',
		// 'Delivering food to those in need is a rewarding experience.',
		// 'Entregar comida a aquellos que la necesitan es una experiencia gratificante.',
		'Inf. present: 	  deliver',
		'I need to deliver this package before noon.',
		'Necesito entregar este paquete antes del mediodía.',
		'Inf. present: 	  delivers',
		'He delivers the newspaper to our house every morning.',
		'Entrega el periódico a nuestra casa todas las mañanas.',
		// 'Past tense: 	  delivered',
		// 'We delivered the project on time and under budget.',
		// 'Entregamos el proyecto a tiempo y dentro del presupuesto.',
		// 'Past participle: 	   delivered',
		// 'I have delivered many speeches in my career as a public speaker.',
		// 'He dado muchos discursos en mi carrera como orador público.',
		// 'Gerund: 	   Delivering',
		// "Delivering bad news is never easy, but it's part of the job.",
		// 'Entregar malas noticias nunca es fácil, pero es parte del trabajo.',
	],
	[
		'Inf. present: 	  dresses',
		'He always dresses in casual clothes on weekends.',
		'Siempre se viste con ropa casual los fines de semana.',
		// 'Past tense: 	  dressed',
		// 'She dressed up in a fancy gown for the formal event.',
		// 'Se vistió con un vestido elegante para el evento formal.',
		// 'Past participle: 	   dressed',
		// 'The man was well-dressed in a suit and tie.',
		// 'El hombre estaba bien vestido con traje y corbata.',
		// 'Gerund: 	   Dressing',
		// 'Dressing for success can help boost confidence and motivation.',
		// 'Vestirse para el éxito puede ayudar a aumentar la confianza y la motivación.',
		'Inf. present: 	  dress',
		"I don't know how to dress for this occasion.",
		'No sé cómo vestirme para esta ocasión.',
		'Inf. present: 	  dresses',
		'She dresses very elegantly for work.',
		'Se viste muy elegantemente para el trabajo.',
		// 'Past tense: 	  dressed',
		// 'We dressed up as superheroes for Halloween.',
		// 'Nos disfrazamos de superhéroes para Halloween.',
		// 'Past participle: 	   dressed',
		// 'I have dressed in many different styles over the years.',
		// 'Me he vestido con muchos estilos diferentes a lo largo de los años.',
		// 'Gerund: 	   Dressing',
		// 'Dressing well can give you confidence and make you feel good about yourself.',
		// 'Vestir bien puede darte confianza y hacerte sentir bien contigo mismo.',
	],
	[
		'Inf. present: 	  end',
		'We need to end this meeting soon.',
		'Necesitamos terminar esta reunión pronto.',
		// 'Past tense: 	  ended',
		// 'The party ended at midnight.',
		// 'La fiesta terminó a medianoche.',
		// 'Past participle: 	   ended',
		// 'The book ended with a surprising twist.',
		// 'El libro terminó con un giro sorprendente.',
		// 'Gerund: 	   Ending',
		// 'Ending a relationship can be difficult but necessary.',
		// 'Terminar una relación puede ser difícil pero necesario.',
		'Inf. present: 	  end',
		'I hope this meeting will end soon.',
		'Espero que esta reunión termine pronto.',
		'Inf. present: 	  ends',
		'The concert ends at 10 pm.',
		'El concierto termina a las 10 pm.',
		// 'Past tense: 	  ended',
		// 'We ended our relationship because we had different goals.',
		// 'Terminamos nuestra relación porque teníamos metas diferentes.',
		// 'Past participle: 	   ended',
		// 'I have ended friendships that were toxic or unhealthy for me.',
		// 'He terminado amistades que eran tóxicas o poco saludables para mí.',
		// 'Gerund: 	   Ending',
		// "Ending a relationship is never easy, but sometimes it's necessary.",
		// 'Terminar una relación nunca es fácil, pero a veces es necesario.',
	],
	[
		'Inf. present: 	  enjoys',
		'She enjoys reading books on a lazy afternoon.',
		'Disfruta leyendo libros en una tarde tranquila.',
		// 'Past tense: 	  enjoyed',
		// 'We enjoyed our vacation at the beach.',
		// 'Disfrutamos nuestras vacaciones en la playa.',
		// 'Past participle: 	   enjoyed',
		// 'The enjoyed the concert so much that they went to see the band again the next night.',
		// 'Disfrutaron tanto del concierto que fueron a ver a la banda nuevamente la noche siguiente.',
		// 'Gerund: 	   Enjoying',
		// 'Enjoying the simple things in life can bring great happiness.',
		// 'Disfrutar de las cosas simples de la vida puede traer gran felicidad.',
		'Inf. present: 	  enjoy',
		'I enjoy spending time with my family.',
		'Disfruto pasar tiempo con mi familia.',
		'Inf. present: 	  enjoys',
		'She enjoys listening to music while she works.',
		'Disfruta escuchar música mientras trabaja.',
		// 'Past tense: 	  enjoyed',
		// 'We enjoyed our vacation in Hawaii last year.',
		// 'Disfrutamos nuestras vacaciones en Hawái el año pasado.',
		// 'Past participle: 	   enjoyed',
		// 'I have enjoyed reading books since I was a child.',
		// 'He disfrutado leyendo libros desde que era niño.',
		// 'Gerund: 	   Enjoying',
		// 'Enjoying the simple things in life can bring you a lot of happiness.',
		// 'Disfrutar de las cosas simples de la vida puede traerte mucha felicidad.',
	],
	[
		'Inf. present: 	  erases',
		'He erases mistakes on the chalkboard during class.',
		'Borra errores en la pizarra durante la clase.',
		// 'Past tense: 	  erased',
		// 'She erased the message she had written on the whiteboard.',
		// 'Borró el mensaje que había escrito en la pizarra blanca.',
		// 'Past participle: 	   erased',
		// 'The file was erased from the computer by accident.',
		// 'El archivo fue borrado accidentalmente de la computadora.',
		// 'Gerund: 	   Erasing',
		// "Erasing bad memories can be difficult, but it's important to focus on the present.",
		// 'Borrar malos recuerdos puede ser difícil, pero es importante centrarse en el presente.',
		'Inf. present: 	  erase',
		'Can you erase this mistake on the whiteboard?',
		'¿Puedes borrar este error del pizarrón?',
		'Inf. present: 	  erases',
		'She erases all of her text messages after she reads them.',
		'Borra todos sus mensajes de texto después de leerlos.',
		// 'Past tense: 	  erased',
		// 'We erased the whiteboard before the next class started.',
		// 'Borramos el pizarrón antes de que empezara la siguiente clase.',
		// 'Past participle: 	   erased',
		// 'I have erased all of my old emails from my inbox.',
		// 'He borrado todos mis correos electrónicos antiguos de mi bandeja de entrada.',
		// 'Gerund: 	   Erasing',
		// 'Erasing a mistake can be a simple way to correct it.',
		// 'Borrar un error puede ser una manera simple de corregirlo.',
	],
	[
		'Inf. present: 	  expect',
		'They expect to arrive at the airport on time.',
		'Esperan llegar al aeropuerto a tiempo.',
		// 'Past tense: 	  expected',
		// "She expected to receive a promotion at work, but it didn't happen.",
		// 'Esperaba recibir una promoción en el trabajo, pero no sucedió.',
		// 'Past participle: 	   expected',
		// 'The guests were expected to arrive at 7 pm.',
		// 'Se esperaba que los invitados llegaran a las 7 pm.',
		// 'Gerund: 	   Expecting',
		// 'Expecting too much from others can lead to disappointment.',
		// 'Esperar demasiado de los demás puede llevar a la decepción.',
		"Inf. present: 	  I don't expect any problems during the trip.",
		'No espero ningún problema durante el viaje.',
		'Inf. present: 	  expects',
		'He expects to graduate from college next year.',
		'Espera graduarse de la universidad el próximo año.',
		'expect',
		"Past tense: 	  We didn't expect so many people to show up for the party.",
		'No esperábamos que tanta gente viniera a la fiesta.',
		'expected',
		'Past participle: 	   I have expected more from people and been disappointed.',
		'He esperado más de las personas y he quedado decepcionado.',
		'Expecting',
		'Gerund: 	   Expecting the unexpected can help you prepare for the worst.',
		'Esperar lo inesperado puede ayudarte a prepararte para lo peor.',
	],
	[
		'Inf. present: 	  fills',
		'He fills his water bottle every morning before going to work.',
		'Llena su botella de agua todas las mañanas antes de ir al trabajo.',
		// 'Past tense: 	  filled',
		// 'She filled the bathtub with warm water for a relaxing soak.',
		// 'Llenó la bañera con agua tibia para un baño relajante.',
		// 'Past participle: 	   filled',
		// 'The glass was filled to the brim with juice.',
		// 'El vaso estaba lleno hasta el borde con jugo.',
		// 'Gerund: 	   Filling',
		// 'Filling your day with meaningful activities can help improve your mood.',
		// 'Llenar tu día con actividades significativas puede ayudar a mejorar tu estado de ánimo.',
		'Inf. present: 	  fill',
		'Can you fill this glass with water?',
		'¿Puedes llenar este vaso con agua?',
		'Inf. present: 	  fills',
		'She fills out her timesheet every week.',
		'Completa su hoja de horas todas las semanas.',
		// 'Past tense: 	  filled',
		// 'We filled the car up with gas before we hit the road.',
		// 'Llenamos el auto con gasolina antes de salir a la carretera.',
		// 'Past participle: 	   filled',
		// 'I have filled out the form and submitted it.',
		// 'He llenado el formulario y lo he enviado.',
		// 'Gerund: 	   Filling',
		// 'Filling the gaps in your knowledge can help you learn more.',
		// 'Completar las lagunas en su conocimiento puede ayudarle a aprender más.',
	],
	[
		'Inf. present: 	  finish',
		'She needs to finish her homework before dinner.',
		'Necesita terminar su tarea antes de la cena.',
		// 'Past tense: 	  finished',
		// 'They finished the project ahead of schedule.',
		// 'Terminaron el proyecto antes de lo previsto.',
		// 'Past participle: 	   finished',
		// 'The painting was finished just in time for the art show.',
		// 'El cuadro fue terminado justo a tiempo para la muestra de arte.',
		// 'Gerund: 	   Finishing',
		// 'Finishing what you start is an important key to success.',
		// 'Terminar lo que empiezas es una clave importante para el éxito.',
		'Inf. present: 	  finish',
		'I need to finish this report by the end of the day.',
		'Necesito terminar este informe para el final del día.',
		'Inf. present: 	  finishes',
		'He finishes work at 6pm every day.',
		'Termina su trabajo a las 6 pm todos los días.',
		// 'Past tense: 	  finished',
		// 'We finished our meal and left the restaurant.',
		// 'Terminamos nuestra comida y salimos del restaurante.',
		// 'Past participle: 	   finished',
		// 'She has finished reading the book already.',
		// 'Ya ha terminado de leer el libro.',
		// 'Gerund: 	   Finishing',
		// 'Finishing the project ahead of schedule will impress the boss.',
		// 'Terminar el proyecto antes de lo previsto impresionará al jefe.',
	],
	[
		'Inf. present: 	  follows',
		'She always follows her daily routine.',
		'Siempre sigue su rutina diaria.',
		// 'Past tense: 	  followed',
		// 'They followed the map to find the hidden treasure.',
		// 'Siguieron el mapa para encontrar el tesoro escondido.',
		// 'Past participle: 	   followed',
		// 'The rules were followed to ensure fairness.',
		// 'Se siguieron las reglas para garantizar la equidad.',
		// 'Gerund: 	   Following',
		// 'Following your passion can lead to a fulfilling career.',
		// 'Seguir tu pasión puede llevar a una carrera satisfactoria.',
		'Inf. present: 	  follow',
		'I always follow my dreams, no matter what.',
		'Siempre sigo mis sueños, pase lo que pase.',
		'Inf. present: 	  follows',
		'She follows the instructions carefully.',
		'Sigue las instrucciones con cuidado.',
		// 'Past tense: 	  followed',
		// 'They followed the directions on the map to get to the beach.',
		// 'Siguen las indicaciones del mapa para llegar a la playa.',
		// 'Past participle: 	   followed',
		// "He has followed in his father's footsteps and become a doctor.",
		// 'Ha seguido los pasos de su padre y se ha convertido en médico.',
		// 'Gerund: 	   Following',
		// 'Following your heart is the key to a happy life.',
		// 'Seguir tu corazón es la clave de una vida feliz.',
	],
	[
		'Inf. present: 	  help',
		'He likes to help his neighbors with their yard work.',
		'Le gusta ayudar a sus vecinos con su trabajo de jardinería.',
		// 'Past tense: 	  helped',
		// 'She helped her friend move to a new apartment.',
		// 'Ayudó a su amiga a mudarse a un nuevo apartamento.',
		// 'Past participle: 	   helped',
		// 'The injured hiker was helped down the mountain by the rescue team.',
		// 'El excursionista herido fue ayudado a bajar de la montaña por el equipo de rescate.',
		// 'Gerund: 	   Helping',
		// 'Helping others can make you feel good about yourself.',
		// 'Ayudar a los demás puede hacerte sentir bien contigo mismo.',
		'Inf. present: 	  help',
		'Can you help me carry this box upstairs?',
		'¿Puedes ayudarme a subir esta caja por las escaleras?',
		'Inf. present: 	  helps',
		'She helps her colleagues with their work when they need it.',
		'Ayuda a sus colegas con su trabajo cuando lo necesitan.',
		// 'Past tense: 	  helped',
		// 'We helped our neighbor fix his car yesterday.',
		// 'Ayer ayudamos a nuestro vecino a arreglar su coche.',
		// 'Past participle: 	   helped',
		// 'He has helped many people in need throughout his life.',
		// 'Ha ayudado a muchas personas necesitadas a lo largo de su vida.',
		// 'Gerund: 	   Helping',
		// 'Helping others can be very rewarding.',
		// 'Ayudar a los demás puede ser muy gratificante.',
	],
	[
		'Inf. present: 	  hurry',
		'We need to hurry if we want to catch the train.',
		'Necesitamos apurarnos si queremos tomar el tren.',
		// 'Past tense: 	  hurried',
		// 'She hurried to finish her work before the deadline.',
		// 'Se apresuró a terminar su trabajo antes del plazo.',
		// 'Past participle: 	   hurried',
		// 'The task was hurried due to lack of time.',
		// 'La tarea se apuró debido a la falta de tiempo.',
		// 'Gerund: 	   Hurrying',
		// "Hurrying can lead to mistakes, so it's important to take your time.",
		// 'Apresurarse puede llevar a errores, por lo que es importante tomarse el tiempo necesario.',
		'Inf. present: 	  hurry',
		'We need to hurry if we want to catch the train.',
		'Tenemos que apurarnos si queremos tomar el tren.',
		'Inf. present: 	  hurries',
		'She hurries to finish her work before the deadline.',
		'Se apresura a terminar su trabajo antes de la fecha límite.',
		// 'Past tense: 	  hurried',
		// 'They hurried to get to the airport on time.',
		// 'Se apresuraron para llegar al aeropuerto a tiempo.',
		// 'Past participle: 	   hurried',
		// 'He has hurried through life, never stopping to enjoy the little things.',
		// 'Se ha apresurado a través de la vida, nunca deteniéndose a disfrutar las pequeñas cosas.',
		// 'Gerund: 	   Hurrying',
		// 'Hurrying is not always the best solution.',
		// 'Apresurarse no siempre es la mejor solución.',
	],
	[
		'Inf. present: 	  intends',
		'She intends to travel around the world someday.',
		'Tiene la intención de viajar por el mundo algún día.',
		// 'Past tense: 	  intended',
		// 'He intended to study law, but changed his mind after taking an art class.',
		// 'Tenía la intención de estudiar derecho, pero cambió de opinión después de tomar una clase de arte.',
		// 'Past participle: 	   intended',
		// 'The message was intended for his boss, but he accidentally sent it to a coworker.',
		// 'El mensaje estaba destinado a su jefe, pero accidentalmente lo envió a un compañero de trabajo.',
		// 'Gerund: 	   Intending',
		// 'Intending to do something is the first step towards achieving your goals.',
		// 'Tener la intención de hacer algo es el primer paso para alcanzar tus metas.',
		'Inf. present: 	  intend',
		'I intend to finish this project by the end of the week.',
		'Tengo la intención de terminar este proyecto para el final de la semana.',
		'Inf. present: 	  intends',
		'He intends to apply for the job before the deadline.',
		'Tiene la intención de solicitar el trabajo antes de la fecha límite.',
		// 'Past tense: 	  intended',
		// 'We intended to go to the party, but we got stuck in traffic.',
		// 'Teníamos la intención de ir a la fiesta, pero nos quedamos atrapados en el tráfico.',
		// 'Past participle: 	   intended',
		// 'She has always intended to travel the world.',
		// 'Siempre ha tenido la intención de viajar por el mundo.',
		// 'Gerund: 	   Intending',
		// 'Intending to do something is not the same as actually doing it.',
		// 'Tener la intención de hacer algo no es lo mismo que hacerlo realmente.',
	],
	[
		'Inf. present: 	  jump',
		'He likes to jump rope for exercise.',
		'Le gusta saltar la cuerda para hacer ejercicio.',
		// 'Past tense: 	  jumped',
		// 'She jumped over the puddle to avoid getting her shoes wet.',
		// 'Saltó sobre el charco para evitar mojar sus zapatos.',
		// 'Past participle: 	   jumped',
		// 'The horse jumped over the fence and ran into the field.',
		// 'El caballo saltó sobre la cerca y corrió hacia el campo.',
		// 'Gerund: 	   Jumping',
		// 'Jumping is a great way to improve your cardiovascular health.',
		// 'Saltar es una excelente manera de mejorar tu salud cardiovascular.',
		'Inf. present: 	  jump',
		'She can jump over the fence with ease.',
		'Ella puede saltar por encima de la cerca con facilidad.',
		'Inf. present: 	  jumps',
		'He jumps up and down when he gets excited.',
		'Salta arriba y abajo cuando se emociona.',
		// 'Past tense: 	  jumped',
		// 'They jumped over the puddle to avoid getting their shoes wet.',
		// 'Saltaron sobre el charco para evitar mojarse los zapatos.',
		// 'Past participle: 	   jumped',
		// 'She has jumped out of an airplane before.',
		// 'Ha saltado de un avión antes.',
		// 'Gerund: 	   Jumping',
		// 'Jumping on the bed is not allowed!',
		// '¡No se permite saltar en la cama!',
	],
	[
		'Inf. present: 	  learn',
		'She wants to learn how to speak French fluently.',
		'Quiere aprender a hablar francés con fluidez.',
		// 'Past tense: 	  learned',
		// 'He learned how to play the guitar from his father.',
		// 'Aprendió a tocar la guitarra de su padre.',
		// 'Past participle: 	   learned',
		// 'The lesson was learned the hard way.',
		// 'La lección fue aprendida de la manera difícil.',
		// 'Gerund: 	   Learning',
		// 'Learning new skills can help you grow and develop as a person.',
		// 'Aprender nuevas habilidades puede ayudarte a crecer y desarrollarte como persona.',
		'Inf. present: 	  learn',
		'I want to learn how to play the guitar.',
		'Quiero aprender a tocar la guitarra.',
		'Inf. present: 	  learns',
		'She learns quickly and easily.',
		'Aprende rápido y fácilmente.',
		// 'Past tense: 	  learned',
		// 'He learned how to swim when he was a child.',
		// 'Aprendió a nadar cuando era niño.',
		// 'Past participle: 	   learned',
		// 'She has learned a lot from her mistakes.',
		// 'Ha aprendido mucho de sus errores.',
		// 'Gerund: 	   Learning',
		// 'Learning a new language can be challenging but rewarding.',
		// 'Aprender un nuevo idioma puede ser desafiante pero gratificante.',
	],
	[
		'Inf. present: 	  lie',
		"He knows it's wrong to lie to his parents.",
		'Sabe que es incorrecto mentirle a sus padres.',
		// 'Past tense: 	  lied',
		// 'She lied about her age to get into the nightclub.',
		// 'Mintió sobre su edad para entrar en el club nocturno.',
		// 'Past participle: 	   lied',
		// 'The truth was revealed after he had lied to his boss.',
		// 'La verdad fue revelada después de que había mentido a su jefe.',
		// 'Gerund: 	   Lying',
		// 'Lying can damage relationships and erode trust.',
		// 'Mentir puede dañar las relaciones y erosionar la confianza.',
		'Inf. present: 	  lies',
		'He lies to his parents about his grades.',
		'Les miente a sus padres sobre sus calificaciones.',
		'Inf. present: 	  lies',
		'She lies about her age to get into clubs.',
		'Miente sobre su edad para entrar en clubs.',
		// 'Past tense: 	  lied',
		// 'They lied to the police about their whereabouts on the night of the crime.',
		// 'Mintieron a la policía sobre su paradero la noche del crimen.',
		// 'Past participle: 	   lied',
		// 'He has lied to his best friend about borrowing money.',
		// 'Le ha mentido a su mejor amigo sobre pedir dinero prestado.',
		// 'Gerund: 	   Lying',
		// 'Lying is not a good habit to have.',
		// 'Mentir no es un buen hábito para tener.',
	],
	[
		'Inf. present: 	  likes',
		'She likes to read books on the beach.',
		'Le gusta leer libros en la playa.',
		// 'Past tense: 	  liked',
		// 'He liked the movie so much that he saw it twice.',
		// 'Le gustó tanto la película que la vio dos veces.',
		// 'Past participle: 	   liked',
		// 'The food was liked by everyone at the party.',
		// 'La comida fue gustada por todos en la fiesta.',
		// 'Gerund: 	   Liking',
		// 'Liking something is a matter of personal preference.',
		// 'Gustar algo es una cuestión de preferencia personal.',
		'Inf. present: 	  likes',
		'She likes to read books in her free time.',
		'Le gusta leer libros en su tiempo libre.',
		'Inf. present: 	  likes',
		'He likes to watch movies on the weekends.',
		'Le gusta ver películas los fines de semana.',
		// 'Past tense: 	  liked',
		// 'They liked the restaurant so much that they went back the next day.',
		// 'Les gustó tanto el restaurante que volvieron al día siguiente.',
		// 'Past participle: 	   liked',
		// 'She has always liked the color blue.',
		// 'Siempre le ha gustado el color azul.',
		// 'Gerund: 	   Liking',
		// 'Liking something is not the same as loving it.',
		// 'Gustar algo no es lo mismo que amarlo.',
	],
	[
		'Inf. present: 	  listen',
		'He likes to listen to music while he works.',
		'Le gusta escuchar música mientras trabaja.',
		// 'Past tense: 	  listened',
		// "She listened to her friend's advice and avoided making a mistake.",
		// 'Escuchó el consejo de su amigo y evitó cometer un error.',
		// 'Past participle: 	   listened',
		// 'The song was listened to by millions of people around the world.',
		// 'La canción fue escuchada por millones de personas en todo el mundo.',
		// 'Gerund: 	   Listening',
		// 'Listening is an important skill for effective communication.',
		// 'Escuchar es una habilidad importante para una comunicación efectiva.',
		'Inf. present: 	  listen',
		'I like to listen to music while I work.',
		'Me gusta escuchar música mientras trabajo.',
		'Inf. present: 	  listens',
		'She listens to her favorite podcast every morning.',
		'Escucha su podcast favorito todas las mañanas.',
		// 'Past tense: 	  listened',
		// "They listened to their grandfather's stories with rapt attention.",
		// 'Escucharon las historias de su abuelo con atención total.',
		// 'Past participle: 	   listened',
		// 'He has listened to this song so many times that he knows every word by heart.',
		// 'Ha escuchado esta canción tantas veces que se sabe todas las letras de memoria.',
		// 'Gerund: 	   Listening',
		// 'Listening to others is an important part of communication.',
		// 'Escuchar a los demás es una parte importante de la comunicación.',
	],
	[
		'Inf. present: 	  live',
		'They live in a small apartment in the city.',
		'Viven en un pequeño apartamento en la ciudad.',
		// 'Past tense: 	  lived',
		// 'She lived in Paris for two years before moving back to the US.',
		// 'Vivió en París durante dos años antes de regresar a los Estados Unidos.',
		// 'Past participle: 	   lively',
		// 'The town is well-known for its lively nightlife and vibrant cultural scene.',
		// 'El pueblo es conocido por su animada vida nocturna y su vibrante escena cultural.',
		// 'Gerund: 	   Living',
		// 'Living life to the fullest means embracing new experiences and taking risks.',
		// 'Vivir la vida al máximo significa abrazar nuevas experiencias y tomar riesgos.',
		'Inf. present: 	  lives',
		'She lives in a small apartment in the city.',
		'Vive en un pequeño apartamento en la ciudad.',
		'Inf. present: 	  lives',
		'He lives with his parents while he saves money to buy a house.',
		'Vive con sus padres mientras ahorra para comprar una casa.',
		// 'Past tense: 	  lived',
		// 'They lived in Paris for three years before moving back to the US.',
		// 'Vivieron en París durante tres años antes de regresar a los Estados Unidos.',
		// 'Past participle: 	   lived',
		// 'She has lived a long and fulfilling life.',
		// 'Ha vivido una vida larga y satisfactoria.',
		// 'Gerund: 	   Living',
		// 'Living in the moment is a good way to reduce stress and anxiety.',
		// 'Vivir el momento es una buena manera de reducir el estrés y la ansiedad.',
	],
	[
		'Inf. present: 	  look',
		'She likes to look at the stars at night.',
		'Le gusta mirar las estrellas por la noche.',
		// 'Past tense: 	  looked',
		// 'He looked out the window and saw the snow falling.',
		// 'Miró por la ventana y vio la nieve cayendo.',
		// 'Past participle: 	   looked',
		// 'The painting looked old and worn, but was actually a replica.',
		// 'El cuadro parecía viejo y desgastado, pero en realidad era una réplica.',
		// 'Gerund: 	   Looking',
		// 'Looking for a job can be a challenging and time-consuming process.',
		// 'Buscar trabajo puede ser un proceso desafiante y que consume tiempo.',
		'Inf. present: 	  looks',
		'He looks tired today.',
		'Se ve cansado hoy.',
		'Inf. present: 	  looks',
		'She looks beautiful in that dress.',
		'Se ve hermosa con ese vestido.',
		// 'Past tense: 	  looked',
		// 'They looked for their lost dog all night.',
		// 'Buscaban a su perro perdido toda la noche.',
		// 'Past participle: 	   looked',
		// "He has looked everywhere for his keys but can't find them.",
		// 'Ha buscado por todas partes sus llaves pero no las encuentra.',
		// 'Gerund: 	   Looking',
		// 'Looking both ways before crossing the street is a good habit to have.',
		// 'Mirar a ambos lados antes de cruzar la calle es un buen hábito para tener.',
	],
	[
		'Inf. present: 	  love',
		'They love spending time together on the weekends.',
		'Les encanta pasar tiempo juntos los fines de semana.',
		// 'Past tense: 	  loved',
		// 'She loved the movie so much that she cried at the end.',
		// 'Le encantó tanto la película que lloró al final.',
		// 'Past participle: 	   loved',
		// 'The couple was loved and respected by their community.',
		// 'La pareja era amada y respetada por su comunidad.',
		// 'Gerund: 	   Loving',
		// 'Loving yourself is an important part of living a happy and fulfilling life.',
		// 'Amarse a sí mismo es una parte importante de vivir una vida feliz y satisfactoria.',
		'Inf. present: 	  love',
		'I love spending time with my family.',
		'Me encanta pasar tiempo con mi familia.',
		'Inf. present: 	  loves',
		'He loves to read before going to bed.',
		'Le encanta leer antes de ir a la cama.',
		// 'Past tense: 	  loved',
		// 'They loved their trip to Europe last summer.',
		// 'Les encantó su viaje a Europa el verano pasado.',
		// 'Past participle: 	   loved',
		// 'She has loved him since the day they met.',
		// 'Lo ha amado desde el día en que se conocieron.',
		// 'Gerund: 	   Loving',
		// 'Loving someone means accepting them for who they are.',
		// 'Amar a alguien significa aceptarlo por lo que es.',
	],
	[
		'Inf. present: 	  misses',
		'He misses his family who lives in another country.',
		'Extraña a su familia que vive en otro país.',
		// 'Past tense: 	  missed',
		// 'She missed her flight and had to book another one.',
		// 'Perdió su vuelo y tuvo que reservar otro.',
		// 'Past participle: 	   missed',
		// 'The opportunity was missed due to lack of preparation.',
		// 'Se perdió la oportunidad debido a la falta de preparación.',
		// 'Gerund: 	   Missing',
		// 'Missing someone can be a difficult feeling to cope with.',
		// 'Extrañar a alguien puede ser un sentimiento difícil de sobrellevar.',
		'Inf. present: 	  miss',
		"I miss my family when I'm away from home.",
		'Extraño a mi familia cuando estoy lejos de casa.',
		'Inf. present: 	  misses',
		'She misses her old job sometimes, but she loves her new one too.',
		'A veces extraña su antiguo trabajo, pero también ama el nuevo.',
		// 'Past tense: 	  missed',
		// 'They missed their flight and had to book another one.',
		// 'Perdieron su vuelo y tuvieron que reservar otro.',
		// 'Past participle: 	   missed',
		// 'He has missed several important events because of work.',
		// 'Se ha perdido varios eventos importantes debido al trabajo.',
		// 'Gerund: 	   Missing',
		// 'Missing someone can be a painful experience.',
		// 'Extrañar a alguien puede ser una experiencia dolorosa.',
	],
	[
		'Inf. present: 	  name',
		'They are going to name their new puppy after their favorite movie character.',
		'Van a nombrar a su nuevo cachorro con el nombre de su personaje de película favorito.',
		// 'Past tense: 	  named',
		// 'She named her daughter after her grandmother.',
		// 'Nombró a su hija con el nombre de su abuela.',
		// 'Past participle: 	   named',
		// 'The new bridge was named after a local hero.',
		// 'El nuevo puente fue nombrado en honor a un héroe local.',
		// 'Gerund: 	   Naming',
		// 'Naming things is an important part of language and communication.',
		// 'Nombrar cosas es una parte importante del lenguaje y la comunicación.',
		'Inf. present: 	  named',
		'She named her dog after her favorite character in a book.',
		'Nombró a su perro en honor a su personaje favorito de un libro.',
		'Inf. present: 	  names',
		'He names all of his plants after famous artists.',
		'Nombra todas sus plantas en honor a artistas famosos.',
		// 'Past tense: 	  named',
		// 'They named their first child after their grandparents.',
		// 'Nombraron a su primer hijo en honor a sus abuelos.',
		// 'Past participle: 	   named',
		// 'She has named over 50 species of insects during her career.',
		// 'Ha nombrado más de 50 especies de insectos durante su carrera.',
		// 'Gerund: 	   Naming',
		// 'Naming a new product can be a challenging process.',
		// 'Nombrar un nuevo producto puede ser un proceso desafiante.',
	],
	[
		'Inf. present: 	  needs',
		'He needs a cup of coffee to start his day.',
		'Necesita una taza de café para empezar su día.',
		// 'Past tense: 	  needed',
		// 'She needed a new phone because her old one was broken.',
		// 'Necesitaba un teléfono nuevo porque el antiguo estaba roto.',
		// 'Past participle: 	   needed',
		// 'The help was needed to complete the project on time.',
		// 'Se necesitaba ayuda para completar el proyecto a tiempo.',
		// 'Gerund: 	   Needing',
		// 'Needing help is not a sign of weakness, but rather a part of being human.',
		// 'Necesitar ayuda no es una señal de debilidad, sino más bien una parte de ser humano.',
		'Inf. present: 	  need',
		'I need to finish this project before the deadline.',
		'Necesito terminar este proyecto antes de la fecha límite.',
		'Inf. present: 	  needs',
		'He needs a cup of coffee to start his day.',
		'Necesita una taza de café para empezar su día.',
		// 'Past tense: 	  needed',
		// 'They needed extra help to complete the task on time.',
		// 'Necesitaban ayuda extra para completar la tarea a tiempo.',
		// 'Past participle: 	   needed',
		// 'She has needed to take a break from work for a while.',
		// 'Ha necesitado tomar un descanso del trabajo por un tiempo.',
		// 'Gerund: 	   Needing',
		// 'Needing assistance is not a sign of weakness.',
		// 'Necesitar ayuda no es una señal de debilidad.',
	],
	[
		'Inf. present: 	  opens',
		'She opens the window to let fresh air in.',
		'Abre la ventana para dejar entrar el aire fresco.',
		// 'Past tense: 	  opened',
		// 'He opened the gift and was pleasantly surprised.',
		// 'Abrió el regalo y se sorprendió gratamente.',
		// 'Past participle: 	   opened',
		// 'The store was opened early to accommodate customers.',
		// 'La tienda se abrió temprano para acomodar a los clientes.',
		// 'Gerund: 	   Opening',
		// 'Opening your mind to new ideas can lead to personal growth.',
		// 'Abrir tu mente a nuevas ideas puede llevarte al crecimiento personal.',
		'Inf. present: 	  open',
		'Can you open the window, please?',
		'¿Puedes abrir la ventana, por favor?',
		'Inf. present: 	  opens',
		'He opens the door for his clients as a sign of respect.',
		'Abre la puerta para sus clientes como muestra de respeto.',
		// 'Past tense: 	  opened',
		// 'They opened a new branch of their business in a different city.',
		// 'Abrieron una nueva sucursal de su negocio en una ciudad diferente.',
		// 'Past participle: 	   opened',
		// 'She has opened up about her struggles with mental health.',
		// 'Ha hablado abiertamente sobre sus luchas con la salud mental.',
		// 'Gerund: 	   Opening',
		// 'Opening up to someone can be a difficult but rewarding experience.',
		// 'Abrirse a alguien puede ser una experiencia difícil pero gratificante.',
	],
	[
		'Inf. present: 	  order',
		'They like to order pizza for dinner on Fridays.',
		'Les gusta ordenar pizza para la cena los viernes.',
		// 'Past tense: 	  ordered',
		// 'She ordered a salad instead of fries with her meal.',
		// 'Pidío una ensalada en lugar de papas fritas con su comida.',
		// 'Past participle: 	   ordered',
		// 'The books were ordered online and delivered to his doorstep.',
		// 'Los libros se ordenaron en línea y se entregaron en su puerta.',
		// 'Gerund: 	   Ordering',
		// 'Ordering food at a restaurant can be a fun and enjoyable experience.',
		// 'Ordenar comida en un restaurante puede ser una experiencia divertida y agradable.',
		'Inf. present: 	  order',
		"I always order pizza when I don't feel like cooking.",
		'Siempre pido pizza cuando no tengo ganas de cocinar.',
		'Inf. present: 	  orders',
		'He orders the same thing every time he goes to that restaurant.',
		'Siempre pide lo mismo cada vez que va a ese restaurante.',
		// 'Past tense: 	  ordered',
		// 'They ordered a bottle of wine to celebrate their anniversary.',
		// 'Pidieron una botella de vino para celebrar su aniversario.',
		// 'Past participle: 	   ordered',
		// 'She has ordered a book online and is waiting for it to arrive.',
		// 'Ha pedido un libro en línea y está esperando a que llegue.',
		// 'Gerund: 	   Ordering',
		// 'Ordering food delivery has become more popular in recent years.',
		// 'Pedir comida a domicilio se ha vuelto más popular en los últimos años.',
	],
	[
		'Inf. present: 	  plan',
		'He likes to plan his vacations well in advance.',
		'Le gusta planificar sus vacaciones con mucha anticipación.',
		// 'Past tense: 	  planned',
		// 'She planned a surprise birthday party for her friend.',
		// 'Planificó una fiesta sorpresa de cumpleaños para su amiga.',
		// 'Past participle: 	   planned',
		// 'The event was planned carefully to ensure its success.',
		// 'El evento fue planeado cuidadosamente para garantizar su éxito.',
		// 'Gerund: 	   Planning',
		// 'Planning your day can help you stay organized and productive.',
		// 'Planificar tu día puede ayudarte a mantenerte organizado y productivo.',
		'Inf. present: 	  plan',
		'We need to plan our vacation in advance.',
		'Necesitamos planear nuestras vacaciones con anticipación.',
		'Inf. present: 	  plans',
		'He plans his day the night before to be more productive.',
		'Planea su día la noche anterior para ser más productivo.',
		// 'Past tense: 	  planned',
		// "They planned a surprise party for their friend's birthday.",
		// 'Planearon una fiesta sorpresa para el cumpleaños de su amigo.',
		// 'Past participle: 	   planned',
		// 'She has planned every detail of the project to ensure its success.',
		// 'Ha planeado cada detalle del proyecto para asegurar su éxito.',
		// 'Gerund: 	   Planning',
		// 'Planning ahead can save you time and money.',
		// 'Planificar con anticipación puede ahorrarle tiempo y dinero.',
	],
	[
		'Inf. present: 	  plant',
		'They like to plant flowers in their garden every spring.',
		'Les gusta plantar flores en su jardín cada primavera.',
		// 'Past tense: 	  planted',
		// 'He planted a tree in his backyard last year.',
		// 'Plantó un árbol en su patio trasero el año pasado.',
		// 'Past participle: 	   planted',
		// 'The garden was planted with a variety of vegetables and herbs.',
		// 'El jardín fue plantado con una variedad de verduras y hierbas.',
		// 'Gerund: 	   Planting',
		// 'Planting trees can help reduce the carbon footprint and combat climate change.',
		// 'Plantar árboles puede ayudar a reducir la huella de carbono y combatir el cambio climático.',
		'Inf. present: 	  planting',
		'She loves planting flowers in her garden.',
		'Le encanta plantar flores en su jardín.',
		'Inf. present: 	  plants',
		'He plants a tree every year on Earth Day.',
		'Planta un árbol cada año en el Día de la Tierra.',
		// 'Past tense: 	  planted',
		// 'They planted a vegetable garden in their backyard.',
		// 'Plantaron un huerto en su patio trasero.',
		// 'Past participle: 	   planted',
		// 'She has planted a variety of herbs in her kitchen window.',
		// 'Ha plantado una variedad de hierbas en la ventana de su cocina.',
		// 'Gerund: 	   Planting',
		// 'Planting trees helps to reduce air pollution and combat climate change.',
		// 'Plantar árboles ayuda a reducir la contaminación del aire y combatir el cambio climático.',
	],
	[
		'Inf. present: 	  play',
		'She likes to play tennis with her friends on the weekends.',
		'Le gusta jugar tenis con sus amigos los fines de semana.',
		// 'Past tense: 	  played',
		// 'He played soccer in high school and was on the varsity team.',
		// 'Jugó al fútbol en la escuela secundaria y estuvo en el equipo varsity.',
		// 'Past participle: 	   played',
		// 'The game was played in the park on a sunny afternoon.',
		// 'El juego se jugó en el parque en una tarde soleada.',
		// 'Gerund: 	   Playing',
		// 'Playing sports can help improve your physical health and mental well-being.',
		// 'Jugar deportes puede ayudar a mejorar tu salud física y bienestar mental.',
		'Inf. present: 	  play',
		'They like to play board games on rainy days.',
		'Les gusta jugar juegos de mesa en días lluviosos.',
		'Inf. present: 	  plays',
		'He plays basketball with his friends every weekend.',
		'Juega baloncesto con sus amigos todos los fines de semana.',
		// 'Past tense: 	  played',
		// 'They played soccer in high school and won many championships.',
		// 'Jugaron fútbol en la escuela secundaria y ganaron muchos campeonatos.',
		// 'Past participle: 	   played',
		// 'She has played the guitar since she was a teenager.',
		// 'Ha tocado la guitarra desde que era adolescente.',
		// 'Gerund: 	   Playing',
		// 'Playing video games can be a fun way to relax after a long day.',
		// 'Jugar videojuegos puede ser una forma divertida de relajarse después de un día largo.',
	],
	[
		'Inf. present: 	  point',
		'He likes to point out constellations in the night sky.',
		'Le gusta señalar las constelaciones en el cielo nocturno.',
		// 'Past tense: 	  pointed',
		// 'She pointed to the map to show where they were going.',
		// 'Señaló el mapa para mostrar dónde iban.',
		// 'Past participle: 	   pointed',
		// 'The problem was pointed out during the meeting.',
		// 'El problema fue señalado durante la reunión.',
		// 'Gerund: 	   Pointing',
		// 'Pointing out mistakes can be a helpful way to improve performance.',
		// 'Señalar errores puede ser una forma útil de mejorar el rendimiento.',
		'Inf. present: 	  pointed',
		'He pointed out the mistake in my calculations.',
		'Señaló el error en mis cálculos.',
		'Inf. present: 	  points',
		'She points to the map to show where we are.',
		'Señala el mapa para mostrar dónde estamos.',
		// 'Past tense: 	  pointed',
		// 'They pointed their fingers at the suspect, accusing him of the crime.',
		// 'Apuntaron con el dedo al sospechoso, acusándolo del crimen.',
		// 'Past participle: 	   pointed',
		// 'He has pointed to the need for more funding for education.',
		// 'Ha señalado la necesidad de más financiamiento para la educación.',
		// 'Gerund: 	   Pointing',
		// 'Pointing out mistakes can help us learn and improve.',
		// 'Señalar errores puede ayudarnos a aprender y mejorar.',
	],
	[
		'Inf. present: 	  practice',
		'They practice yoga together every morning.',
		'Practican yoga juntos todas las mañanas.',
		// 'Past tense: 	  practiced',
		// 'She practiced the piano for three hours every day.',
		// 'Practicaba el piano durante tres horas todos los días.',
		// 'Past participle: 	   practiced',
		// 'The routine was practiced until it was perfect.',
		// 'La rutina se practicó hasta que fuera perfecta.',
		// 'Gerund: 	   Practicing',
		// 'Practicing a skill can help improve proficiency and mastery.',
		// 'Practicar una habilidad puede ayudar a mejorar la competencia y el dominio.',
		'Inf. present: 	  practices',
		'She practices yoga every morning to start her day off right.',
		'Practica yoga todas las mañanas para empezar bien el día.',
		'Inf. present: 	  practices',
		'He practices his guitar skills for an hour every day.',
		'Practica sus habilidades con la guitarra durante una hora todos los días.',
		// 'Past tense: 	  practiced',
		// 'They practiced their lines for the play until they had them memorized.',
		// 'Practicaron sus líneas para la obra hasta que las memorizaron.',
		// 'Past participle: 	   practiced',
		// 'She has practiced meditation for years and finds it very beneficial.',
		// 'Ha practicado meditación durante años y encuentra que es muy beneficiosa.',
		// 'Gerund: 	   Practicing',
		// 'Practicing a skill regularly can lead to mastery and success.',
		// 'Practicar una habilidad regularmente puede llevar a la maestría y el éxito.',
	],
	[
		'Inf. present: 	  pushes',
		'He pushes the shopping cart while she selects the items.',
		'Empuja el carrito de compras mientras ella selecciona los artículos.',
		// 'Past tense: 	  pushed',
		// 'She pushed her way through the crowd to get to the front.',
		// 'Se abrió camino a empujones entre la multitud para llegar al frente.',
		// 'Past participle: 	   pushed',
		// 'The door was pushed open with great effort.',
		// 'La puerta se abrió a empujones con gran esfuerzo.',
		// 'Gerund: 	   Pushing',
		// 'Pushing a heavy object requires strength and effort.',
		// 'Empujar un objeto pesado requiere fuerza y esfuerzo.',
		'Inf. present: 	  pushed',
		'He pushed the door open with his foot because his hands were full.',
		'Empujó la puerta con el pie porque tenía las manos ocupadas.',
		'Inf. present: 	  pushes',
		'She pushes herself to be the best she can be in everything she does.',
		'Se esfuerza por ser lo mejor que pueda ser en todo lo que hace.',
		// 'Past tense: 	  pushed',
		// 'They pushed their car to the gas station when it ran out of fuel.',
		// 'Empujaron su auto hasta la gasolinera cuando se quedó sin combustible.',
		// 'Past participle: 	   pushed',
		// 'He has pushed through difficult times by staying positive and focused.',
		// 'Ha superado tiempos difíciles manteniéndose positivo y enfocado.',
		// 'Gerund: 	   Pushing',
		// 'Pushing yourself to try new things can lead to personal growth and development.',
		// 'Empujarse a sí mismo para probar cosas nuevas puede conducir al crecimiento y desarrollo personal.',
	],
	[
		'Inf. present: 	  raining',
		"It's raining outside, so bring an umbrella.",
		'Está lloviendo afuera, así que trae un paraguas.',
		// 'Past tense: 	  rained',
		// 'It rained all weekend, so they stayed indoors.',
		// 'Llovió todo el fin de semana, así que se quedaron adentro.',
		// 'Past participle: 	   rainfall',
		// 'The roads were flooded after heavy rainfall.',
		// 'Las carreteras estaban inundadas después de una lluvia intensa.',
		// 'Gerund: 	   rain',
		// 'Walking in the rain can be a fun and adventurous experience.',
		// 'Caminar bajo la lluvia puede ser una experiencia divertida y aventurera.',
		'Inf. present: 	  rain',
		'It started to rain just as we left the house.',
		'Empezó a llover justo cuando salimos de la casa.',
		'Inf. present: 	  rains',
		'It often rains in this part of the country.',
		'A menudo llueve en esta parte del país.',
		// 'Past tense: 	  rained',
		// 'It rained all day yesterday, so we stayed indoors.',
		// 'Llovió todo el día de ayer, así que nos quedamos adentro.',
		// 'Past participle: 	   rain',
		// 'The roads were flooded after the heavy rain we had last night.',
		// 'Las carreteras estaban inundadas después de la fuerte lluvia que tuvimos anoche.',
		// 'Gerund: 	   raining',
		// "It's raining outside, so we'll need an umbrella to go out.",
		// 'Está lloviendo afuera, así que necesitaremos un paraguas para salir.',
	],
	[
		'Inf. present: 	  remember',
		'He always sets a reminder to remember important dates.',
		'Siempre establece un recordatorio para recordar las fechas importantes.',
		// 'Past tense: 	  remembered',
		// 'She remembered the song from her childhood and sang it aloud.',
		// 'Recordó la canción de su infancia y la cantó en voz alta.',
		// 'Past participle: 	   remembered',
		// 'The event was remembered for years to come.',
		// 'El evento fue recordado durante años.',
		// 'Gerund: 	   Remembering',
		// 'Remembering to be grateful for what you have can bring happiness and contentment.',
		// 'Recordar ser agradecido por lo que tienes puede traer felicidad y satisfacción.',
		'Inf. present: 	  remember',
		'I always remember to lock the door before I leave the house.',
		'Siempre recuerdo cerrar la puerta con llave antes de salir de la casa.',
		'Inf. present: 	  remembers',
		'She remembers her childhood fondly, especially the summers she spent at the beach.',
		'Recuerda con cariño su infancia, especialmente los veranos que pasó en la playa.',
		// 'Past tense: 	  remembered',
		// 'I remembered to bring my umbrella, and I was glad I did when it started raining.',
		// 'Recordé traer mi paraguas, y me alegré de haberlo hecho cuando empezó a llover.',
		// 'Past participle: 	   remembered',
		// 'He has always remembered the lessons his father taught him.',
		// 'Siempre ha recordado las lecciones que su padre le enseñó.',
		// 'Gerund: 	   Remembering',
		// 'Remembering to stay calm in stressful situations can be a challenge.',
		// 'Recordar mantener la calma en situaciones estresantes puede ser un desafío.',
	],
	[
		'Inf. present: 	  rent',
		'They rent an apartment in the city.',
		'Alquilan un apartamento en la ciudad.',
		// 'Past tense: 	  rented',
		// 'She rented a car for the weekend getaway.',
		// 'Alquiló un auto para la escapada de fin de semana.',
		// 'Past participle: 	   rented',
		// 'The house was rented out to vacationers during the summer.',
		// 'La casa se alquiló a vacacionistas durante el verano.',
		// 'Gerund: 	   Renting',
		// 'Renting a movie online is a convenient way to watch it at home.',
		// 'Alquilar una película en línea es una forma conveniente de verla en casa.',
		'Inf. present: 	  rent',
		'They decided to rent a car for their road trip across the country.',
		'Decidieron alquilar un coche para su viaje por carretera a través del país.',
		'renting',
		"We're currently renting an apartment until we can afford to buy a house.",
		'Actualmente estamos alquilando un apartamento hasta que podamos permitirnos comprar una casa.',
		// 'Past tense: 	  rented',
		// 'They rented a beach house for a week and had a wonderful time.',
		// 'Alquilaron una casa de playa durante una semana y lo pasaron genial.',
		// 'Past participle: 	   rented',
		// 'She has rented out her spare room to a student for the past year.',
		// 'Ha alquilado su habitación libre a un estudiante durante el último año.',
		// 'Gerund: 	   Renting',
		// 'Renting furniture is a great option for people who move frequently.',
		// 'Alquilar muebles es una gran opción para personas que se mudan con frecuencia.',
	],
	[
		'Inf. present: 	  repeat',
		'He likes to repeat the phrases to practice his pronunciation.',
		'Le gusta repetir las frases para practicar su pronunciación.',
		// 'Past tense: 	  repeated',
		// 'She repeated the instructions to make sure she understood them.',
		// 'Repitió las instrucciones para asegurarse de entenderlas.',
		// 'Past participle: 	   repeated',
		// 'The song was repeated several times during the concert.',
		// 'La canción se repitió varias veces durante el concierto.',
		// 'Gerund: 	   Repeating',
		// 'Repeating a task can help improve skills and proficiency.',
		// 'Repetir una tarea puede ayudar a mejorar habilidades y competencia.',
		'Inf. present: 	  repeat',
		'He wants to repeat the course next semester.',
		'Quiere repetir el curso el próximo semestre.',
		'repeat',
		"I repeat this mantra to calm myself down when I'm stressed.",
		'Repito este mantra para calmarme cuando estoy estresado.',
		// 'Past tense: 	  repeated',
		// 'They repeated the same mistake over and over again.',
		// 'Repetían el mismo error una y otra vez.',
		// 'Past participle: 	   repeated',
		// 'She has repeated that story so many times, I could recite it myself.',
		// 'Ha repetido esa historia tantas veces que yo mismo podría recitarla.',
		// 'Gerund: 	   Repeating',
		// 'Repeating a task several times can help with memorization.',
		// 'Repetir una tarea varias veces puede ayudar con la memorización.',
	],
	[
		'Inf. present: 	  resist',
		'They try to resist eating junk food.',
		'Intentan resistir comer comida chatarra.',
		// 'Past tense: 	  resisted',
		// 'She resisted the temptation to buy the expensive dress.',
		// 'Resistió la tentación de comprar el vestido caro.',
		// 'Past participle: 	   resistant',
		// 'The disease is resistant to antibiotics.',
		// 'La enfermedad es resistente a los antibióticos.',
		// 'Gerund: 	   Resisting',
		// 'Resisting peer pressure can be a challenging but important part of growing up.',
		// 'Resistir la presión de los amigos puede ser una parte desafiante pero importante del crecimiento.',
		'Inf. present: 	  resist',
		'She tries to resist the urge to check her phone during class.',
		'Intenta resistir la tentación de revisar su teléfono durante la clase.',
		'Inf. present: 	  resists',
		"He resists the temptation to eat junk food, even when he's craving it.",
		'Resiste la tentación de comer comida chatarra, incluso cuando lo está deseando.',
		// 'Past tense: 	  resisted',
		// 'They resisted the pressure to conform and stuck to their own beliefs.',
		// 'Resistieron la presión para conformarse y se aferraron a sus propias creencias.',
		// 'Past participle: 	   resisted',
		// "She has resisted change for so long that she's now stuck in her ways.",
		// 'Ha resistido el cambio durante tanto tiempo que ahora está atrapada en sus formas.',
		// 'Gerund: 	   Resisting',
		// 'Resisting temptation is a key part of building self-discipline.',
		// 'Resistir la tentación es una parte clave para desarrollar la autodisciplina.',
	],
	[
		'Inf. present: 	  shows',
		'He shows pictures of his travels to his friends.',
		'Muestra fotos de sus viajes a sus amigos.',
		// 'Past tense: 	  showed',
		// 'She showed the way to the nearest hospital.',
		// 'Mostró el camino hacia el hospital más cercano.',
		// 'Past participle: 	   showed',
		// 'The art exhibition showed works from local artists.',
		// 'La exposición de arte mostró obras de artistas locales.',
		// 'Gerund: 	   Showing',
		// 'Showing appreciation and gratitude can strengthen relationships.',
		// 'Mostrar aprecio y gratitud puede fortalecer las relaciones.',
		'Inf. present: 	  show',
		"He wants to show his parents how much he's improved since starting school.",
		'Quiere mostrarle a sus padres cuánto ha mejorado desde que empezó la escuela.',
		'Inf. present: 	  shows',
		'She shows a lot of potential in her new job.',
		'Muestra mucho potencial en su nuevo trabajo.',
		// 'Past tense: 	  showed',
		// 'They showed up late to the meeting because of traffic.',
		// 'Llegaron tarde a la reunión debido al tráfico.',
		// 'Past participle: 	   shown',
		// 'She has shown great leadership skills in her role as manager.',
		// 'Ha mostrado grandes habilidades de liderazgo en su papel como gerente.',
		// 'Gerund: 	   Showing',
		// 'Showing appreciation for your coworkers can improve team morale.',
		// 'Mostrar aprecio por tus compañeros de trabajo puede mejorar la moral del equipo.',
	],
	[
		'Inf. present: 	  smoke',
		"He doesn't smoke cigarettes anymore.",
		'Ya no fuma cigarrillos.',
		// 'Past tense: 	  smoked',
		// 'She smoked a cigar to celebrate her promotion.',
		// 'Fumó un cigarro para celebrar su ascenso.',
		// 'Past participle: 	   smoke',
		// 'The air in the room was thick with smoke from the fire.',
		// 'El aire en la habitación estaba espeso con humo del fuego.',
		// 'Gerund: 	   Smoking',
		// 'Smoking can have negative health effects, such as lung cancer and heart disease.',
		// 'Fumar puede tener efectos negativos en la salud, como el cáncer de pulmón y enfermedades cardíacas.',
		'Inf. present: 	  smoke',
		"He doesn't smoke anymore, he quit last year.",
		'Ya no fuma, lo dejó el año pasado.',
		'Inf. present: 	  smokes',
		'She smokes a pack a day and is trying to quit.',
		'Fuma una cajetilla al día y está tratando de dejarlo.',
		// 'Past tense: 	  smoked',
		// 'He smoked for many years before he finally quit.',
		// 'Fumó durante muchos años antes de dejarlo finalmente.',
		// 'Past participle: 	   smoke',
		// 'The air was thick with smoke from the burning building.',
		// 'El aire estaba espeso con humo del edificio en llamas.',
		// 'Gerund: 	   Smoking',
		// 'Smoking is harmful to your health and can cause many diseases.',
		// 'Fumar es perjudicial para la salud y puede causar muchas enfermedades.',
	],
	[
		'Inf. present: 	  starts',
		'She starts her day with a cup of coffee.',
		'Empieza su día con una taza de café.',
		// 'Past tense: 	  started',
		// 'He started his own business last year.',
		// 'Empezó su propio negocio el año pasado.',
		// 'Past participle: 	   started',
		// 'The race had already started when they arrived.',
		// 'La carrera ya había empezado cuando llegaron.',
		// 'Gerund: 	   Starting',
		// 'Starting a new hobby can be a fun and rewarding experience.',
		// 'Empezar un nuevo pasatiempo puede ser una experiencia divertida y gratificante.',
		'Inf. present: 	  start',
		'He wants to start a business of his own.',
		'Quiere iniciar su propio negocio.',
		'Inf. present: 	  starts',
		'She starts work at 9am every day.',
		'Empieza a trabajar a las 9 de la mañana todos los días.',
		// 'Past tense: 	  started',
		// 'He started his career as a teacher and later became a writer.',
		// 'Comenzó su carrera como profesor y más tarde se convirtió en escritor.',
		// 'Past participle: 	   started',
		// 'The engine started after a few tries.',
		// 'El motor arrancó después de algunos intentos.',
		// 'Gerund: 	   Starting',
		// 'Starting a new project can be both exciting and challenging.',
		// 'Comenzar un nuevo proyecto puede ser emocionante y desafiante.',
	],
	[
		'Inf. present: 	  stay',
		'They like to stay at home on weekends.',
		'Les gusta quedarse en casa los fines de semana.',
		// 'Past tense: 	  stayed',
		// 'She stayed in a hotel during her vacation.',
		// 'Se quedó en un hotel durante sus vacaciones.',
		// 'Past participle: 	   stay',
		// 'The guests were offered a complimentary stay at the hotel.',
		// 'A los huéspedes se les ofreció una estancia gratuita en el hotel.',
		// 'Gerund: 	   Staying',
		// 'Staying active and healthy can help improve quality of life.',
		// 'Quedarse activo y saludable puede ayudar a mejorar la calidad de vida.',
		'Inf. present: 	  stay',
		'She decided to stay home and watch a movie.',
		'Decidió quedarse en casa y ver una película.',
		'stay',
		'They stay at a different hotel every time they travel.',
		'Se quedan en un hotel diferente cada vez que viajan.',
		// 'Past tense: 	  stayed',
		// 'He stayed in Paris for a week and visited all the major tourist attractions.',
		// 'Se quedó en París durante una semana y visitó todas las principales atracciones turísticas.',
		// 'Past participle: 	   stay',
		// 'The hotel offers a stay of three nights for the price of two.',
		// 'El hotel ofrece una estadía de tres noches por el precio de dos.',
		// 'Gerund: 	   Staying',
		// 'Staying active is important for maintaining good health.',
		// 'Mantenerse activo es importante para mantener una buena salud.',
	],
	[
		'Inf. present: 	  stops',
		'He stops to read the newspaper on his way to work.',
		'Se detiene a leer el periódico en su camino al trabajo.',
		// 'Past tense: 	  stopped',
		// 'She stopped eating meat last year.',
		// 'Dejó de comer carne el año pasado.',
		// 'Past participle: 	   stopped',
		// 'The music had stopped by the time they arrived.',
		// 'La música había parado cuando llegaron.',
		// 'Gerund: 	   Stopping',
		// 'Stopping to take breaks can help prevent burnout and increase productivity.',
		// 'Parar para tomar descansos puede ayudar a prevenir el agotamiento y aumentar la productividad.',
		'Inf. present: 	  stopped',
		'He stopped to catch his breath after running for so long.',
		'Se detuvo para recuperar el aliento después de correr por tanto tiempo.',
		'stop',
		'I stop by the coffee shop every morning for a latte.',
		'Paso por la cafetería todas las mañanas para tomar un latte.',
		// 'Past tense: 	  stopped',
		// 'The police officer stopped the car for speeding.',
		// 'El oficial de policía detuvo el coche por exceso de velocidad.',
		// 'Past participle: 	   stopped',
		// 'She has stopped eating red meat for health reasons.',
		// 'Ha dejado de comer carne roja por razones de salud.',
		// 'Gerund: 	   Stopping',
		// 'Stopping to rest during a hike can be very refreshing.',
		// 'Detenerse a descansar durante una caminata puede ser muy refrescante.',
	],
	[
		'Inf. present: 	  study',
		'They study together at the library.',
		'Estudian juntos en la biblioteca.',
		// 'Past tense: 	  studied',
		// 'He studied biology in college.',
		// 'Estudió biología en la universidad.',
		// 'Past participle: 	   studied',
		// 'The research was studied extensively before being published.',
		// 'La investigación fue estudiada extensamente antes de ser publicada.',
		// 'Gerund: 	   Studying',
		// 'Studying for exams can be a challenging but rewarding experience.',
		// 'Estudiar para exámenes puede ser una experiencia desafiante pero gratificante.',
		'Inf. present: 	  study',
		'He wants to study architecture in college.',
		'Quiere estudiar arquitectura en la universidad.',
		'Inf. present: 	  studies',
		'She studies for her exams for hours every day.',
		'Estudia para sus exámenes durante horas todos los días.',
		// 'Past tense: 	  studied',
		// 'He studied abroad in Spain for a semester in college.',
		// 'Estudió en el extranjero en España durante un semestre en la universidad.',
		// 'Past participle: 	   studied',
		// 'She has studied French for several years and is fluent.',
		// 'Ha estudiado francés durante varios años y es fluida.',
		// 'Gerund: 	   Studying',
		// 'Studying different cultures can be a fascinating experience.',
		// 'Estudiar diferentes culturas puede ser una experiencia fascinante.',
	],
	[
		'Inf. present: 	  talks',
		'She talks to her family on the phone every day.',
		'Habla con su familia por teléfono todos los días.',
		// 'Past tense: 	  talked',
		// 'He talked to his boss about a raise.',
		// 'Habló con su jefe sobre un aumento.',
		// 'Past participle: 	   talked',
		// 'The issue was talked about extensively during the meeting.',
		// 'El tema se habló extensamente durante la reunión.',
		// 'Gerund: 	   Talking',
		// 'Talking about your feelings with a trusted friend can help relieve stress and anxiety.',
		// 'Hablar de tus sentimientos con un amigo de confianza puede ayudar a aliviar el estrés y la ansiedad.',
		'Inf. present: 	  talk',
		'We need to talk about the upcoming project and make a plan.',
		'Tenemos que hablar sobre el próximo proyecto y hacer un plan.',
		'Inf. present: 	  talks',
		'She talks on the phone with her sister every day.',
		'Habla por teléfono con su hermana todos los días.',
		// 'Past tense: 	  talked',
		// 'He talked to the manager about getting a promotion.',
		// 'Habló con el gerente sobre obtener un ascenso.',
		// 'Past participle: 	   talked',
		// 'She has talked to her boss about taking time off for a vacation.',
		// 'Ha hablado con su jefe sobre tomarse un tiempo libre para unas vacaciones.',
		// 'Gerund: 	   Talking',
		// 'Talking to strangers can sometimes be intimidating.',
		// 'Hablar con desconocidos a veces puede ser intimidante.',
	],
	[
		'Inf. present: 	  travel',
		'They love to travel to new places.',
		'Les encanta viajar a lugares nuevos.',
		// 'Past tense: 	  traveled',
		// 'She traveled to Europe last summer.',
		// 'Viajó a Europa el verano pasado.',
		// 'Past participle: 	   travel',
		// 'The tickets had already been booked for the travel plans.',
		// 'Los boletos ya habían sido reservados para los planes de viaje.',
		// 'Gerund: 	   Traveling',
		// 'Traveling can broaden your horizons and expose you to new cultures.',
		// 'Viajar puede ampliar tus horizontes y exponerte a nuevas culturas.',
		'Inf. present: 	  travel',
		'I want to travel the world and experience different cultures.',
		'Quiero viajar por el mundo y experimentar diferentes culturas.',
		'Inf. present: 	  travels',
		'She travels for work almost every week.',
		'Viaja por trabajo casi todas las semanas.',
		// 'Past tense: 	  traveled',
		// 'We traveled to Europe last summer and had an amazing time.',
		// 'Viajamos a Europa el verano pasado y la pasamos increíble.',
		// 'Past participle: 	   traveled',
		// 'He has traveled to over 20 countries in his lifetime.',
		// 'Ha viajado a más de 20 países en su vida.',
		// 'Gerund: 	   Traveling',
		// 'Traveling can broaden your horizons and help you grow as a person.',
		// 'Viajar puede ampliar tus horizontes y ayudarte a crecer como persona.',
	],
	[
		'Inf. present: 	  tries',
		'He tries to exercise every day.',
		'Intenta hacer ejercicio todos los días.',
		// 'Past tense: 	  tried',
		// 'She tried a new restaurant last night.',
		// 'Probó un restaurante nuevo anoche.',
		// 'Past participle: 	   tried',
		// 'The experiment had been tried several times with varying results.',
		// 'El experimento había sido intentado varias veces con resultados variables.',
		// 'Gerund: 	   Trying',
		// 'Trying new things can be scary but can also lead to personal growth and development.',
		// 'Intentar cosas nuevas puede ser aterrador pero también puede conducir al crecimiento y desarrollo personal.',
		'Inf. present: 	  try',
		'I will try my best to finish the project on time.',
		'Haré todo lo posible para terminar el proyecto a tiempo.',
		'Inf. present: 	  tries',
		'She tries to eat healthy and exercise regularly.',
		'Intenta comer saludable y hacer ejercicio regularmente.',
		// 'Past tense: 	  tried',
		// 'He tried to fix the car himself, but ended up making it worse.',
		// 'Intentó arreglar el auto por sí mismo, pero terminó empeorando la situación.',
		// 'Past participle: 	   tried',
		// "Have you ever tried sushi? It's delicious!",
		// '¿Alguna vez has probado sushi? ¡Es delicioso!',
		// 'Gerund: 	   Trying',
		// 'Trying new things can be scary, but it can also lead to growth and new opportunities.',
		// 'Probar cosas nuevas puede ser aterrador, pero también puede conducir al crecimiento y nuevas oportunidades.',
	],
	[
		'Inf. present: 	  turns',
		'He turns left at the intersection.',
		'Gira a la izquierda en la intersección.',
		// 'Past tense: 	  turned',
		// 'She turned off the lights before leaving the room.',
		// 'Apagó las luces antes de salir de la habitación.',
		// 'Past participle: 	   turned',
		// 'The page had already been turned when he noticed the mistake.',
		// 'La página ya había sido girada cuando notó el error.',
		// 'Gerund: 	   Turning',
		// 'Turning your attention to the present moment can help reduce stress and anxiety.',
		// 'Girar tu atención al momento presente puede ayudar a reducir el estrés y la ansiedad.',
		'Inf. present: 	  turn',
		"Don't forget to turn off the lights before you leave.",
		'No olvides apagar las luces antes de irte.',
		'Inf. present: 	  turns',
		'He turns the music down when he needs to focus.',
		'Baja el volumen de la música cuando necesita concentrarse.',
		// 'Past tense: 	  turned',
		// 'They turned the corner and saw the most beautiful sunset they had ever seen.',
		// 'Doblaron la esquina y vieron la puesta de sol más hermosa que habían visto.',
		// 'Past participle: 	   turned',
		// 'The company has turned a profit every year since it was founded.',
		// 'La empresa ha obtenido beneficios todos los años desde que fue fundada.',
		// 'Gerund: 	   Turning',
		// 'Turning your passion into a career can lead to a fulfilling and rewarding life.',
		// 'Convertir tu pasión en una carrera puede llevar a una vida gratificante y satisfactoria.',
	],
	[
		'Inf. present: 	  use',
		'They use their phones to stay in touch.',
		'Usan sus teléfonos para mantenerse en contacto.',
		// 'Past tense: 	  used',
		// 'He used a hammer to fix the fence.',
		// 'Usó un martillo para arreglar la cerca.',
		// 'Past participle: 	   used',
		// 'The product is used by many people for its effectiveness.',
		// 'El producto es usado por muchas personas por su eficacia.',
		// 'Gerund: 	   Using',
		// 'Using technology can make many tasks more efficient and convenient.',
		// 'Usar la tecnología puede hacer muchas tareas más eficientes y convenientes.',
		'Inf. present: 	  use',
		'I need to use the restroom.',
		'Necesito usar el baño.',
		'Inf. present: 	  uses',
		'She uses her laptop for work every day.',
		'Ella usa su laptop para el trabajo todos los días.',
		// 'Past tense: 	  used',
		// 'He used to play basketball in high school.',
		// 'Solía jugar baloncesto en la escuela secundaria.',
		// 'Past participle: 	   used',
		// 'The company has used this marketing strategy before.',
		// 'La empresa ha utilizado esta estrategia de marketing antes.',
		// 'Gerund: 	   Using',
		// 'Using a computer can make many tasks easier.',
		// 'Usar una computadora puede hacer muchas tareas más fáciles.',
	],
	[
		'Inf. present: 	  visits',
		'She visits her grandparents every weekend.',
		'Visita a sus abuelos todos los fines de semana.',
		// 'Past tense: 	  visited',
		// 'He visited New York City last year.',
		// 'Visitó la ciudad de Nueva York el año pasado.',
		// 'Past participle: 	   visited',
		// 'The museum has been visited by millions of people over the years.',
		// 'El museo ha sido visitado por millones de personas a lo largo de los años.',
		// 'Gerund: 	   Visiting',
		// 'Visiting new places can broaden your perspective and open your mind to new ideas.',
		// 'Visitar lugares nuevos puede ampliar tu perspectiva y abrir tu mente a nuevas ideas.',
		'Inf. present: 	  visit',
		'I want to visit my grandmother in the hospital.',
		'Quiero visitar a mi abuela en el hospital.',
		'Inf. present: 	  visits',
		'She visits her parents every weekend.',
		'Ella visita a sus padres todos los fines de semana.',
		// 'Past tense: 	  visited',
		// 'We visited several museums during our trip to Europe.',
		// 'Visitamos varios museos durante nuestro viaje a Europa.',
		// 'Past participle: 	   visited',
		// 'He has visited many countries in his lifetime.',
		// 'Ha visitado muchos países en su vida.',
		// 'Gerund: 	   Visiting',
		// 'Visiting new places can broaden your perspective.',
		// 'Visitar lugares nuevos puede ampliar tu perspectiva.',
	],
	[
		'Inf. present: 	  waiting',
		'She is waiting for her friend to arrive.',
		'Está esperando a que llegue su amiga.',
		// 'Past tense: 	  waited',
		// 'He waited in line for two hours to buy tickets.',
		// 'Esperó en la fila durante dos horas para comprar boletos.',
		// 'Past participle: 	   waiting',
		// 'The package had been waiting for her at the post office.',
		// 'El paquete había estado esperando por ella en la oficina de correos.',
		// 'Gerund: 	   Waiting',
		// 'Waiting patiently can be a valuable life skill that can help build resilience and perseverance.',
		// 'Esperar pacientemente puede ser una habilidad valiosa en la vida que puede ayudar a construir la resiliencia y la perseverancia.',
		'Inf. present: 	  wait',
		"I can't wait to see the new movie.",
		'No puedo esperar para ver la nueva película.',
		'Inf. present: 	  waits',
		'She waits patiently for her turn in line.',
		'Ella espera pacientemente su turno en la fila.',
		// 'Past tense: 	  waited',
		// 'We waited for hours to get tickets to the concert.',
		// 'Esperamos durante horas para conseguir boletos para el concierto.',
		// 'Past participle: 	   waited',
		// 'He has waited a long time for this opportunity.',
		// 'Ha esperado mucho tiempo por esta oportunidad.',
		// 'Gerund: 	   Waiting',
		// "Waiting in line can be boring, but it's often necessary.",
		// 'Esperar en la fila puede ser aburrido, pero a menudo es necesario.',
	],
	[
		'Inf. present: 	  walk',
		'They like to walk in the park on weekends.',
		'Les gusta caminar en el parque los fines de semana.',
		// 'Past tense: 	  walked',
		// 'She walked home from work yesterday.',
		// 'Caminó a casa desde el trabajo ayer.',
		// 'Past participle: 	   walked',
		// 'The path had been walked by many hikers before.',
		// 'El camino había sido caminado por muchos excursionistas antes.',
		// 'Gerund: 	   Walking',
		// 'Walking can be a low-impact exercise that can help improve cardiovascular health and overall well-being.',
		// 'Caminar puede ser un ejercicio de bajo impacto que puede ayudar a mejorar la salud cardiovascular y el bienestar general.',
		'Inf. present: 	  walks',
		'She walks to work every day instead of driving.',
		'Ella camina al trabajo todos los días en lugar de conducir.',
		'Inf. present: 	  walk',
		'I walk my dog in the park every morning.',
		'Paseo a mi perro en el parque todas las mañanas.',
		// 'Past tense: 	  walked',
		// "He walked home after the party since he didn't want to drive.",
		// 'Caminó a casa después de la fiesta ya que no quería conducir.',
		// 'Past participle: 	   walked',
		// 'She has walked the entire Camino de Santiago pilgrimage route.',
		// 'Ha caminado toda la ruta del peregrinaje del Camino de Santiago.',
		// 'Gerund: 	   Walking',
		// 'Walking is a great form of exercise and can improve overall health.',
		// 'Caminar es una excelente forma de ejercicio y puede mejorar la salud en general.',
	],
	[
		'Inf. present: 	  wants',
		'He wants a new car for his birthday.',
		'Quiere un coche nuevo para su cumpleaños.',
		// 'Past tense: 	  wanted',
		// 'She wanted to be a doctor when she was a child.',
		// 'Quería ser doctora cuando era niña.',
		// 'Past participle: 	   wanted',
		// 'The book was wanted by many readers for its popularity.',
		// 'El libro fue querido por muchos lectores por su popularidad.',
		// 'Gerund: 	   Wanting',
		// 'Wanting more material possessions can lead to a never-ending cycle of desire and dissatisfaction.',
		// 'Querer más posesiones materiales puede llevar a un ciclo interminable de deseo y insatisfacción.',
		'Inf. present: 	  wants',
		'She wants to learn how to play the guitar.',
		'Ella quiere aprender a tocar la guitarra.',
		'Inf. present: 	  want',
		'I want a cup of coffee to wake me up.',
		'Quiero una taza de café para despertarme.',
		// 'Past tense: 	  wanted',
		// 'He wanted to go to the party but had to work late.',
		// 'Quería ir a la fiesta pero tuvo que trabajar hasta tarde.',
		// 'Past participle: 	   wanted',
		// 'She has always wanted to visit Paris.',
		// 'Siempre ha querido visitar París.',
		// 'Gerund: 	   Wanting',
		// 'Wanting something can drive motivation and action.',
		// 'Querer algo puede impulsar la motivación y la acción.',
	],
	[
		'Inf. present: 	  wash',
		'They wash their clothes every week.',
		'Lavan su ropa todas las semanas.',
		// 'Past tense: 	  washed',
		// 'He washed the dishes after dinner.',
		// 'Lavó los platos después de la cena.',
		// 'Past participle: 	   washed',
		// 'The clothes had been washed and dried before being folded.',
		// 'La ropa había sido lavada y secada antes de ser doblada.',
		// 'Gerund: 	   Washing',
		// 'Washing your hands frequently can help prevent the spread of germs and illnesses.',
		// 'Lavarse las manos con frecuencia puede ayudar a prevenir la propagación de gérmenes y enfermedades.',
		'Inf. present: 	  wash',
		'She needs to wash the dishes before she goes to bed.',
		'Necesita lavar los platos antes de acostarse.',
		'Inf. present: 	  wash',
		'I wash my car every Saturday morning.',
		'Lavo mi auto todos los sábados por la mañana.',
		// 'Past tense: 	  washed',
		// 'He washed his clothes at the laundromat because his washing machine was broken.',
		// 'Lavó su ropa en la lavandería porque su lavadora estaba rota.',
		// 'Past participle: 	   washed',
		// 'She has washed the windows and they look so much cleaner now.',
		// 'Ha lavado las ventanas y ahora se ven mucho más limpias.',
		// 'Gerund: 	   Washing',
		// 'Washing your hands regularly is important for preventing the spread of germs.',
		// 'Lavarse las manos regularmente es importante para prevenir la propagación de gérmenes.',
	],
	[
		'Inf. present: 	  wishes',
		'She wishes she could travel more often.',
		'Desea poder viajar con más frecuencia.',
		// 'Past tense: 	  wished',
		// 'He wished he had studied harder for the test.',
		// 'Deseó haber estudiado más para el examen.',
		// 'Past participle: 	   wish',
		// 'The wish had been granted by the time she woke up.',
		// 'El deseo había sido concedido cuando se despertó.',
		// 'Gerund: 	   Wishing',
		// 'Wishing for a better future can motivate us to work towards our goals.',
		// 'Desear un futuro mejor puede motivarnos a trabajar hacia nuestras metas.',
		'Inf. present: 	  wishes',
		'She wishes to travel to Japan someday.',
		'Ella desea viajar a Japón algún día.',
		'Inf. present: 	  wishes',
		'He wishes he had more time to spend with his family.',
		'Él desearía tener más tiempo para pasar con su familia.',
		// 'Past tense: 	  wished',
		// 'I wished for a new bicycle every year when I was a child.',
		// 'Deseaba una bicicleta nueva cada año cuando era niño.',
		// 'Past participle: 	   wished',
		// 'She has wished for peace in the world since she was young.',
		// 'Ha deseado paz en el mundo desde que era joven.',
		// 'Gerund: 	   Wishing',
		// 'Wishing for things can sometimes distract us from enjoying what we have.',
		// 'Desear cosas a veces nos puede distraer de disfrutar lo que tenemos.',
	],
	[
		'Inf. present: 	  work',
		'They work at a restaurant in downtown.',
		'Trabajan en un restaurante en el centro.',
		// 'Past tense: 	  worked',
		// 'She worked overtime to finish the project on time.',
		// 'Trabajó horas extras para terminar el proyecto a tiempo.',
		// 'Past participle: 	   worked',
		// 'The report had been worked on by multiple people before being submitted.',
		// 'El informe había sido trabajado por varias personas antes de ser presentado.',
		// 'Gerund: 	   Working',
		// 'Working collaboratively with others can help generate new ideas and improve problem-solving skills.',
		// 'Trabajar colaborativamente con otros puede ayudar a generar nuevas ideas y mejorar las habilidades para resolver problemas.',
		'Inf. present: 	  work',
		'I work as a teacher at a local school.',
		'Trabajo como maestro en una escuela local.',
		'Inf. present: 	  works',
		'He works long hours at his job to provide for his family.',
		'Trabaja largas horas en su trabajo para proveer a su familia.',
		// 'Past tense: 	  worked',
		// 'I worked in retail for several years before changing careers.',
		// 'Trabajé en venta al por menor durante varios años antes de cambiar de carrera.',
		// 'Past participle: 	   worked',
		// 'She has worked hard to become a successful entrepreneur.',
		// 'Ha trabajado duro para convertirse en una emprendedora exitosa.',
		// 'Gerund: 	   Working',
		// 'Working on a project with a team can be both challenging and rewarding.',
		// 'Trabajar en un proyecto con un equipo puede ser desafiante y gratificante.',
	],
];
