export default [
	[
		'Inf. present: 	  accept',
		'I want to accept the invitation to the party.',
		'Quiero aceptar la invitación a la fiesta.',
		'Inf. present: 	  accepts',
		'She accepts the job offer last week and now works there.',
		'Ella acepta la oferta de trabajo la semana pasada y ahora trabaja allí.',
		'Past tense: 	  accepted',
		'She accepted the job offer last week.',
		'Aceptó la oferta de trabajo la semana pasada.',
		'Past participle: 	   accepted',
		'I have accepted the terms of the contract.',
		'He aceptado los términos del contrato.',
		'Gerund: 	   accepting',
		'He is not used to accepting help from others.',
		'No está acostumbrado a aceptar ayuda de otros.',
	],
	[
		'Inf. present: 	  answer',
		'He needs to answer the phone.',
		'Él necesita responder el teléfono.',
		'Inf. present: 	  answers',
		'She always answers my questions.',
		'Ella siempre responde mis preguntas.',
		'Past tense: 	  answered',
		'She answered all the questions correctly on the exam.',
		'Respondió todas las preguntas correctamente en el examen.',
		'Past participle: 	   answered',
		'The letter has not been answered yet.',
		'La carta aún no ha sido respondida.',
		'Gerund: 	   answering',
		'She is used to answering emails every day.',
		'Ella está acostumbrada a responder correos electrónicos todos los días.',
	],
	[
		'Inf. present: 	  arrive',
		'They usually arrive at the office at 9 am.',
		'Por lo general llegan a la oficina a las 9 am.',
		'Inf. present: 	  arrives',
		'The train arrives at the station in five minutes.',
		'El tren llega a la estación en cinco minutos.',
		'Past tense: 	  arrived',
		'I arrived at the party late because of traffic.',
		'Llegué tarde a la fiesta por el tráfico.',
		'Past participle: 	   arrived',
		'She has just arrived home from work.',
		'Ella acaba de llegar a casa del trabajo.',
		'Gerund: 	   arriving',
		'He enjoys arriving early to avoid the crowds.',
		'A él le gusta llegar temprano para evitar las multitudes.',
	],
	[
		'Inf. present: 	  ask',
		'I need to ask him a question.',
		'Necesito hacerle una pregunta.',
		'Inf. present: 	  asks',
		'She asks a lot of questions in class.',
		'Ella hace muchas preguntas en clase.',
		'Past tense: 	  asked',
		'She asked me to help her with her homework.',
		'Me pidió que la ayudara con su tarea.',
		'Past participle: 	   asked',
		'He has never been asked to speak in public before.',
		'Nunca le han pedido que hable en público antes.',
		'Gerund: 	   asking',
		'They are not used to asking for help.',
		'No están acostumbrados a pedir ayuda.',
	],
	[
		'Inf. present: 	  belongs',
		'The book belongs on the shelf.',
		'El libro pertenece a la estantería.',
		'belong',
		'The keys belong to the blue car.',
		'Las llaves pertenecen al coche azul.',
		'Past tense: 	  belonged',
		'The necklace belonged to her grandmother.',
		'El collar pertenecía a su abuela.',
		'Past participle: 	   belongs',
		'This book belongs to me.',
		'Este libro me pertenece a mí.',
		'Gerund: 	   belonging',
		'She enjoys belonging to a community group.',
		'Disfruta pertenecer a un grupo comunitario.',
	],
	[
		'Inf. present: 	  bother',
		"Don't bother him, he's busy.",
		'No le molestes, está ocupado.',
		'Inf. present: 	  bothers',
		"Her loud music bothers me when I'm trying to work.",
		'Su música alta me molesta cuando estoy tratando de trabajar.',
		'Past tense: 	  bothered',
		'He bothered to read the instructions before starting the project.',
		'Se molestó en leer las instrucciones antes de empezar el proyecto.',
		'Past participle: 	   bothered',
		'I was bothered by the loud noise outside my window.',
		'Me molestaba el ruido fuerte fuera de mi ventana.',
		'Gerund: 	   bothering',
		'Stop bothering me with all these questions.',
		'Deja de molestarme con todas estas preguntas.',
	],
	[
		'Inf. present: 	  change',
		'I want to change my hairstyle.',
		'Quiero cambiar mi peinado.',
		'Inf. present: 	  changes',
		'He changes his mind a lot.',
		'Él cambia de opinión muchas veces.',
		'Past tense: 	  changed',
		'They changed their plans at the last minute.',
		'Cambiaron sus planes en el último minuto.',
		'Past participle: 	   changed',
		'The company has changed its policy on vacation time.',
		'La empresa ha cambiado su política sobre el tiempo de vacaciones.',
		'Gerund: 	   changing',
		'He is considering changing his major in college.',
		'Está considerando cambiar su especialización en la universidad.',
	],
	[
		'Inf. present: 	  cleans',
		'She cleans the kitchen every night after dinner.',
		'Limpia la cocina todas las noches después de la cena.',
		'Inf. present: 	  clean',
		'We need to clean the house before the guests arrive.',
		'Necesitamos limpiar la casa antes de que lleguen los invitados.',
		'Past tense: 	  cleaned',
		'He cleaned his car last weekend.',
		'Limpió su coche el fin de semana pasado.',
		'Past participle: 	   cleaned',
		"I have cleaned the bathroom, so it's ready for guests.",
		'He limpiado el baño, así que está listo para los invitados.',
		'Gerund: 	   Cleaning',
		'Cleaning up after a party is never fun.',
		'Limpiar después de una fiesta nunca es divertido.',
	],
	[
		'Inf. present: 	  climb',
		'They like to climb mountains in their free time.',
		'Les gusta escalar montañas en su tiempo libre.',
		'Inf. present: 	  climbs',
		'He climbs the stairs instead of taking the elevator.',
		'Él sube las escaleras en lugar de tomar el ascensor.',
		'Past tense: 	  climbed',
		'He climbed the tree to get a better view of the park.',
		'Escaló el árbol para tener una mejor vista del parque.',
		'Past participle: 	   climbed',
		'She has climbed the highest peak in the state.',
		'Ha escalado la cumbre más alta del estado.',
		'Gerund: 	   Climbing',
		'Climbing is his favorite hobby.',
		'Escalar es su pasatiempo favorito.',
	],
	[
		'Inf. present: 	  close',
		'Please close the door behind you.',
		'Por favor, cierra la puerta detrás de ti.',
		'Inf. present: 	  closes',
		'The store closes at 9 pm every day.',
		'La tienda cierra a las 9 pm todos los días.',
		'Past tense: 	  closed',
		'He closed the window before going to bed.',
		'Cerró la ventana antes de acostarse.',
		'Past participle: 	   closed',
		'The store was closed for renovations.',
		'La tienda estaba cerrada por renovaciones.',
		'Gerund: 	   Closing',
		'Closing the deal took longer than expected.',
		'Cerrar el trato llevó más tiempo de lo esperado.',
	],
	[
		'Inf. present: 	  considering',
		'She is considering a job offer from another company.',
		'Está considerando una oferta de trabajo de otra empresa.',
		'Inf. present: 	  considers',
		'He considers himself lucky to have such a supportive family.',
		'Se considera afortunado de tener una familia tan solidaria.',
		'Past tense: 	  considered',
		'We considered all the options before making a decision.',
		'Consideramos todas las opciones antes de tomar una decisión.',
		'Past participle: 	   considered',
		'I have considered quitting my job and traveling the world.',
		'He considerado renunciar a mi trabajo y viajar por el mundo.',
		'Gerund: 	   Considering',
		'Considering the circumstances, he made the best choice.',
		'Considerando las circunstancias, tomó la mejor decisión.',
	],
	[
		'Inf. present: 	  cook',
		'I love to cook Italian food.',
		'Me encanta cocinar comida italiana.',
		'Inf. present: 	  cooks',
		'She cooks dinner for her family every night.',
		'Cocina la cena para su familia todas las noches.',
		'Past tense: 	  cooked',
		'She cooked a delicious meal for her guests.',
		'Cocinó una comida deliciosa para sus invitados.',
		'Past participle: 	   cooked',
		'I have cooked this recipe before, and it always turns out well.',
		'He cocinado esta receta antes, y siempre queda bien.',
		'Gerund: 	   Cooking',
		'Cooking together can be a fun date night activity.',
		'Cocinar juntos puede ser una actividad divertida para una noche de cita.',
	],
	[
		'Inf. present: 	  count',
		'Can you count to ten in Spanish?',
		'¿Puedes contar hasta diez en español?',
		'Inf. present: 	  counts',
		'He counts his blessings every day.',
		'Cuenta sus bendiciones todos los días.',
		'Past tense: 	  counted',
		'They counted the votes and announced the winner.',
		'Contaron los votos y anunciaron el ganador.',
		'Past participle: 	   counted',
		'The votes were counted and the winner was announced.',
		'Los votos fueron contados y el ganador fue anunciado.',
		'Gerund: 	   Counting',
		'Counting sheep is a popular method to help you fall asleep.',
		'Contar ovejas es un método popular para ayudarte a dormir.',
	],
	[
		'Inf. present: 	  dance',
		'They love to dance at weddings.',
		'Les encanta bailar en las bodas.',
		'Inf. present: 	  dances',
		'She dances every Saturday night at the local club.',
		'Baila todos los sábados por la noche en el club local.',
		'Past tense: 	  danced',
		'We danced for hours at the wedding reception.',
		'Bailamos durante horas en la recepción de la boda.',
		'Past participle: 	   dance',
		'The dance floor was cleared for the performance.',
		'La pista de baile fue despejada para la presentación.',
		'Gerund: 	   Dancing',
		'Dancing is a fun way to stay active and healthy.',
		'Bailar es una manera divertida de mantenerse activo y saludable.',
	],
	[
		'Inf. present: 	  dare',
		"He doesn't dare to jump off the diving board.",
		'No se atreve a saltar del trampolín.',
		'Inf. present: 	  dares',
		'She dares to speak her mind even when others disagree with her.',
		'Se atreve a decir lo que piensa incluso cuando los demás no están de acuerdo con ella.',
		'Past tense: 	  dared',
		'He dared to climb the mountain even though it was dangerous.',
		'Se atrevió a subir la montaña aunque era peligroso.',
		'Past participle: 	   daring',
		'The stunt was daring and impressive.',
		'La acrobacia fue atrevida e impresionante.',
		'Gerund: 	   Daring',
		'Daring to dream big can lead to great things.',
		'Atreverse a soñar en grande puede llevar a grandes cosas.',
	],
	[
		'Inf. present: 	  date',
		'She wants to date someone who shares her interests.',
		'Quiere salir con alguien que comparta sus intereses.',
		'Inf. present: 	  dates',
		'He dates a different person every week.',
		'Sale con una persona diferente cada semana.',
		'Past tense: 	  dated',
		'They dated for two years before getting married.',
		'Salieron durante dos años antes de casarse.',
		'Past participle: 	   dated',
		'The letter was dated April 1st.',
		'La carta estaba fechada el 1 de abril.',
		'Gerund: 	   Dating',
		'Dating can be a fun way to get to know someone new.',
		'Salir con alguien puede ser una forma divertida de conocer a alguien nuevo.',
	],
	[
		'Inf. present: 	  deliver',
		'I need to deliver this package before noon.',
		'Necesito entregar este paquete antes del mediodía.',
		'Inf. present: 	  delivers',
		'He delivers the newspaper to our house every morning.',
		'Entrega el periódico a nuestra casa todas las mañanas.',
		'Past tense: 	  delivered',
		'She delivered the package to the correct address.',
		'Entregó el paquete a la dirección correcta.',
		'Past participle: 	   delivered',
		'The speech was delivered with passion and enthusiasm.',
		'El discurso fue entregado con pasión y entusiasmo.',
		'Gerund: 	   Delivering',
		'Delivering food to those in need is a rewarding experience.',
		'Entregar comida a aquellos que la necesitan es una experiencia gratificante.',
	],
	[
		'Inf. present: 	  dress',
		"I don't know how to dress for this occasion.",
		'No sé cómo vestirme para esta ocasión.',
		'Inf. present: 	  dresses',
		'She dresses very elegantly for work.',
		'Se viste muy elegantemente para el trabajo.',
		'Past tense: 	  dressed',
		'We dressed up as superheroes for Halloween.',
		'Nos disfrazamos de superhéroes para Halloween.',
		'Past participle: 	   dressed',
		'I have dressed in many different styles over the years.',
		'Me he vestido con muchos estilos diferentes a lo largo de los años.',
		'Gerund: 	   Dressing',
		'Dressing for success can help boost confidence and motivation.',
		'Vestirse para el éxito puede ayudar a aumentar la confianza y la motivación.',
	],
	[
		'Inf. present: 	  end',
		'We need to end this meeting soon.',
		'Necesitamos terminar esta reunión pronto.',
		'Inf. present: 	  ends',
		'The concert ends at 10 pm.',
		'El concierto termina a las 10 pm.',
		'Past tense: 	  ended',
		'The party ended at midnight.',
		'La fiesta terminó a medianoche.',
		'Past participle: 	   ended',
		'The book ended with a surprising twist.',
		'El libro terminó con un giro sorprendente.',
		'Gerund: 	   Ending',
		'Ending a relationship can be difficult but necessary.',
		'Terminar una relación puede ser difícil pero necesario.',
	],
	[
		'Inf. present: 	  enjoy',
		'I enjoy spending time with my family.',
		'Disfruto pasar tiempo con mi familia.',
		'Inf. present: 	  enjoys',
		'She enjoys listening to music while she works.',
		'Disfruta escuchar música mientras trabaja.',
		'Past tense: 	  enjoyed',
		'We enjoyed our vacation at the beach.',
		'Disfrutamos nuestras vacaciones en la playa.',
		'Past participle: 	   enjoyed',
		'I have enjoyed reading books since I was a child.',
		'He disfrutado leyendo libros desde que era niño.',
		'Gerund: 	   Enjoying',
		'Enjoying the simple things in life can bring great happiness.',
		'Disfrutar de las cosas simples de la vida puede traer gran felicidad.',
	],
	[
		'Inf. present: 	  erase',
		'Can you erase this mistake on the whiteboard?',
		'¿Puedes borrar este error del pizarrón?',
		'Inf. present: 	  erases',
		'He erases mistakes on the chalkboard during class.',
		'Borra errores en la pizarra durante la clase.',
		'Past tense: 	  erased',
		'We erased the whiteboard before the next class started.',
		'Borramos el pizarrón antes de que empezara la siguiente clase.',
		'Past participle: 	   erased',
		'The file was erased from the computer by accident.',
		'El archivo fue borrado accidentalmente de la computadora.',
		'Gerund: 	   Erasing',
		'Erasing a mistake can be a simple way to correct it.',
		'Borrar un error puede ser una manera simple de corregirlo.',
	],
	[
		'Inf. present: 	  expect',
		'They expect to arrive at the airport on time.',
		'Esperan llegar al aeropuerto a tiempo.',
		'Inf. present: 	  expects',
		'He expects to graduate from college next year.',
		'Espera graduarse de la universidad el próximo año.',
		'Past tense: 	  expected',
		"She expected to receive a promotion at work, but it didn't happen.",
		'Esperaba recibir una promoción en el trabajo, pero no sucedió.',
		'Past participle: 	   expected',
		'The guests were expected to arrive at 7 pm.',
		'Se esperaba que los invitados llegaran a las 7 pm.',
		'Gerund: 	   Expecting',
		'Expecting too much from others can lead to disappointment.',
		'Esperar demasiado de los demás puede llevar a la decepción.',
	],
	[
		'Inf. present: 	  fill',
		'Can you fill this glass with water?',
		'¿Puedes llenar este vaso con agua?',
		'Inf. present: 	  fills',
		'She fills out her timesheet every week.',
		'Completa su hoja de horas todas las semanas.',
		'Past tense: 	  filled',
		'We filled the car up with gas before we hit the road.',
		'Llenamos el auto con gasolina antes de salir a la carretera.',
		'Past participle: 	   filled',
		'I have filled out the form and submitted it.',
		'He llenado el formulario y lo he enviado.',
		'Gerund: 	   Filling',
		'Filling the gaps in your knowledge can help you learn more.',
		'Completar las lagunas en su conocimiento puede ayudarle a aprender más.',
	],
	[
		'Inf. present: 	  finish',
		'I need to finish this report by the end of the day.',
		'Necesito terminar este informe para el final del día.',
		'Inf. present: 	  finishes',
		'He finishes work at 6pm every day.',
		'Termina su trabajo a las 6 pm todos los días.',
		'Past tense: 	  finished',
		'They finished the project ahead of schedule.',
		'Terminaron el proyecto antes de lo previsto.',
		'Past participle: 	   finished',
		'She has finished reading the book already.',
		'Ya ha terminado de leer el libro.',
		'Gerund: 	   Finishing',
		'Finishing what you start is an important key to success.',
		'Terminar lo que empiezas es una clave importante para el éxito.',
	],
	[
		'Inf. present: 	  follow',
		'I always follow my dreams, no matter what.',
		'Siempre sigo mis sueños, pase lo que pase.',
		'Inf. present: 	  follows',
		'She always follows her daily routine.',
		'Siempre sigue su rutina diaria.',
		'Past tense: 	  followed',
		'They followed the map to find the hidden treasure.',
		'Siguieron el mapa para encontrar el tesoro escondido.',
		'Past participle: 	   followed',
		'The rules were followed to ensure fairness.',
		'Se siguieron las reglas para garantizar la equidad.',
		'Gerund: 	   Following',
		'Following your heart is the key to a happy life.',
		'Seguir tu corazón es la clave de una vida feliz.',
	],
	[
		'Inf. present: 	  help',
		'He likes to help his neighbors with their yard work.',
		'Le gusta ayudar a sus vecinos con su trabajo de jardinería.',
		'Inf. present: 	  helps',
		'She helps her colleagues with their work when they need it.',
		'Ayuda a sus colegas con su trabajo cuando lo necesitan.',
		'Past tense: 	  helped',
		'We helped our neighbor fix his car yesterday.',
		'Ayer ayudamos a nuestro vecino a arreglar su coche.',
		'Past participle: 	   helped',
		'He has helped many people in need throughout his life.',
		'Ha ayudado a muchas personas necesitadas a lo largo de su vida.',
		'Gerund: 	   Helping',
		'Helping others can be very rewarding.',
		'Ayudar a los demás puede ser muy gratificante.',
	],
	[
		'Inf. present: 	  hurry',
		'We need to hurry if we want to catch the train.',
		'Tenemos que apurarnos si queremos tomar el tren.',
		'Inf. present: 	  hurries',
		'She hurries to finish her work before the deadline.',
		'Se apresura a terminar su trabajo antes de la fecha límite.',
		'Past tense: 	  hurried',
		'She hurried to finish her work before the deadline.',
		'Se apresuró a terminar su trabajo antes del plazo.',
		'Past participle: 	   hurried',
		'He has hurried through life, never stopping to enjoy the little things.',
		'Se ha apresurado a través de la vida, nunca deteniéndose a disfrutar las pequeñas cosas.',
		'Gerund: 	   Hurrying',
		'Hurrying is not always the best solution.',
		'Apresurarse no siempre es la mejor solución.',
	],
	[
		'Inf. present: 	  intend',
		'I intend to finish this project by the end of the week.',
		'Tengo la intención de terminar este proyecto para el final de la semana.',
		'Inf. present: 	  intends',
		'She intends to travel around the world someday.',
		'Tiene la intención de viajar por el mundo algún día.',
		'Past tense: 	  intended',
		'He intended to study law, but changed his mind after taking an art class.',
		'Tenía la intención de estudiar derecho, pero cambió de opinión después de tomar una clase de arte.',
		'Past participle: 	   intended',
		'She has always intended to travel the world.',
		'Siempre ha tenido la intención de viajar por el mundo.',
		'Gerund: 	   Intending',
		'Intending to do something is not the same as actually doing it.',
		'Tener la intención de hacer algo no es lo mismo que hacerlo realmente.',
	],
	[
		'Inf. present: 	  jump',
		'He likes to jump rope for exercise.',
		'Le gusta saltar la cuerda para hacer ejercicio.',
		'Inf. present: 	  jumps',
		'He jumps up and down when he gets excited.',
		'Salta arriba y abajo cuando se emociona.',
		'Past tense: 	  jumped',
		'She jumped over the puddle to avoid getting her shoes wet.',
		'Saltó sobre el charco para evitar mojar sus zapatos.',
		'Past participle: 	   jumped',
		'She has jumped out of an airplane before.',
		'Ha saltado de un avión antes.',
		'Gerund: 	   Jumping',
		'Jumping on the bed is not allowed!',
		'¡No se permite saltar en la cama!',
	],
	[
		'Inf. present: 	  learn',
		'I want to learn how to play the guitar.',
		'Quiero aprender a tocar la guitarra.',
		'Inf. present: 	  learns',
		'She learns quickly and easily.',
		'Aprende rápido y fácilmente.',
		'Past tense: 	  learned',
		'He learned how to swim when he was a child.',
		'Aprendió a nadar cuando era niño.',
		'Past participle: 	   learned',
		'She has learned a lot from her mistakes.',
		'Ha aprendido mucho de sus errores.',
		'Gerund: 	   Learning',
		'Learning new skills can help you grow and develop as a person.',
		'Aprender nuevas habilidades puede ayudarte a crecer y desarrollarte como persona.',
	],
	[
		'Inf. present: 	  lies',
		'He lies to his parents about his grades.',
		'Les miente a sus padres sobre sus calificaciones.',
		'Inf. present: 	  lies',
		'She lies about her age to get into clubs.',
		'Miente sobre su edad para entrar en clubs.',
		'Past tense: 	  lied',
		'She lied about her age to get into the nightclub.',
		'Mintió sobre su edad para entrar en el club nocturno.',
		'Past participle: 	   lied',
		'The truth was revealed after he had lied to his boss.',
		'La verdad fue revelada después de que había mentido a su jefe.',
		'Gerund: 	   Lying',
		'Lying is not a good habit to have.',
		'Mentir no es un buen hábito para tener.',
	],
	[
		'Inf. present: 	  likes',
		'She likes to read books on the beach.',
		'Le gusta leer libros en la playa.',
		'Past tense: 	  liked',
		'He liked the movie so much that he saw it twice.',
		'Le gustó tanto la película que la vio dos veces.',
		'Past participle: 	   liked',
		'She has always liked the color blue.',
		'Siempre le ha gustado el color azul.',
		'Gerund: 	   Liking',
		'Liking something is not the same as loving it.',
		'Gustar algo no es lo mismo que amarlo.',
	],
	[
		'Inf. present: 	  listen',
		'I like to listen to music while I work.',
		'Me gusta escuchar música mientras trabajo.',
		'Inf. present: 	  listens',
		'She listens to her favorite podcast every morning.',
		'Escucha su podcast favorito todas las mañanas.',
		'Past tense: 	  listened',
		"She listened to her friend's advice and avoided making a mistake.",
		'Escuchó el consejo de su amigo y evitó cometer un error.',
		'Past participle: 	   listened',
		'The song was listened to by millions of people around the world.',
		'La canción fue escuchada por millones de personas en todo el mundo.',
		'Gerund: 	   Listening',
		'Listening is an important skill for effective communication.',
		'Escuchar es una habilidad importante para una comunicación efectiva.',
	],
	[
		'Inf. present: 	  live',
		'They live in a small apartment in the city.',
		'Viven en un pequeño apartamento en la ciudad.',
		'Inf. present: 	  lives',
		'She lives in a small apartment in the city.',
		'Vive en un pequeño apartamento en la ciudad.',
		'Past tense: 	  lived',
		'She lived in Paris for two years before moving back to the US.',
		'Vivió en París durante dos años antes de regresar a los Estados Unidos.',
		'Past participle: 	   lived',
		'She has lived a long and fulfilling life.',
		'Ha vivido una vida larga y satisfactoria.',
		'Gerund: 	   Living',
		'Living in the moment is a good way to reduce stress and anxiety.',
		'Vivir el momento es una buena manera de reducir el estrés y la ansiedad.',
	],
	[
		'Inf. present: 	  looks',
		'He looks tired today.',
		'Se ve cansado hoy.',
		'Inf. present: 	  looks',
		'She looks beautiful in that dress.',
		'Se ve hermosa con ese vestido.',
		'Past tense: 	  looked',
		'They looked for their lost dog all night.',
		'Buscaban a su perro perdido toda la noche.',
		'Past participle: 	   looked',
		"He has looked everywhere for his keys but can't find them.",
		'Ha buscado por todas partes sus llaves pero no las encuentra.',
		'Gerund: 	   Looking',
		'Looking for a job can be a challenging and time-consuming process.',
		'Buscar trabajo puede ser un proceso desafiante y que consume tiempo.',
	],
	[
		'Inf. present: 	  love',
		'I love spending time with my family.',
		'Me encanta pasar tiempo con mi familia.',
		'Inf. present: 	  loves',
		'He loves to read before going to bed.',
		'Le encanta leer antes de ir a la cama.',
		'Past tense: 	  loved',
		'They loved their trip to Europe last summer.',
		'Les encantó su viaje a Europa el verano pasado.',
		'Past participle: 	   loved',
		'She has loved him since the day they met.',
		'Lo ha amado desde el día en que se conocieron.',
		'Gerund: 	   Loving',
		'Loving someone means accepting them for who they are.',
		'Amar a alguien significa aceptarlo por lo que es.',
	],
	[
		'Inf. present: 	  misses',
		'He misses his family who lives in another country.',
		'Extraña a su familia que vive en otro país.',
		'Inf. present: 	  miss',
		"I miss my family when I'm away from home.",
		'Extraño a mi familia cuando estoy lejos de casa.',
		'Past tense: 	  missed',
		'She missed her flight and had to book another one.',
		'Perdió su vuelo y tuvo que reservar otro.',
		'Past participle: 	   missed',
		'He has missed several important events because of work.',
		'Se ha perdido varios eventos importantes debido al trabajo.',
		'Gerund: 	   Missing',
		'Missing someone can be a painful experience.',
		'Extrañar a alguien puede ser una experiencia dolorosa.',
	],
	[
		'Inf. present: 	  name',
		'They are going to name their new puppy after their favorite movie character.',
		'Van a nombrar a su nuevo cachorro con el nombre de su personaje de película favorito.',
		'Inf. present: 	  names',
		'He names all of his plants after famous artists.',
		'Nombra todas sus plantas en honor a artistas famosos.',
		'Past tense: 	  named',
		'She named her daughter after her grandmother.',
		'Nombró a su hija con el nombre de su abuela.',
		'Past participle: 	   named',
		'The new bridge was named after a local hero.',
		'El nuevo puente fue nombrado en honor a un héroe local.',
		'Gerund: 	   Naming',
		'Naming a new product can be a challenging process.',
		'Nombrar un nuevo producto puede ser un proceso desafiante.',
	],
	[
		'Inf. present: 	  needs',
		'He needs a cup of coffee to start his day.',
		'Necesita una taza de café para empezar su día.',
		'Inf. present: 	  need',
		'I need to finish this project before the deadline.',
		'Necesito terminar este proyecto antes de la fecha límite.',
		'Past tense: 	  needed',
		'They needed extra help to complete the task on time.',
		'Necesitaban ayuda extra para completar la tarea a tiempo.',
		'Past participle: 	   needed',
		'She has needed to take a break from work for a while.',
		'Ha necesitado tomar un descanso del trabajo por un tiempo.',
		'Gerund: 	   Needing',
		'Needing assistance is not a sign of weakness.',
		'Necesitar ayuda no es una señal de debilidad.',
	],
	[
		'Inf. present: 	  open',
		'Can you open the window, please?',
		'¿Puedes abrir la ventana, por favor?',
		'Inf. present: 	  opens',
		'She opens the window to let fresh air in.',
		'Abre la ventana para dejar entrar el aire fresco.',
		'Past tense: 	  opened',
		'He opened the gift and was pleasantly surprised.',
		'Abrió el regalo y se sorprendió gratamente.',
		'Past participle: 	   opened',
		'She has opened up about her struggles with mental health.',
		'Ha hablado abiertamente sobre sus luchas con la salud mental.',
		'Gerund: 	   Opening',
		'Opening your mind to new ideas can lead to personal growth.',
		'Abrir tu mente a nuevas ideas puede llevarte al crecimiento personal.',
	],
	[
		'Inf. present: 	  order',
		"I always order pizza when I don't feel like cooking.",
		'Siempre pido pizza cuando no tengo ganas de cocinar.',
		'Inf. present: 	  order',
		'They like to order pizza for dinner on Fridays.',
		'Les gusta ordenar pizza para la cena los viernes.',
		'Past tense: 	  ordered',
		'She ordered a salad instead of fries with her meal.',
		'Pidío una ensalada en lugar de papas fritas con su comida.',
		'Past participle: 	   ordered',
		'She has ordered a book online and is waiting for it to arrive.',
		'Ha pedido un libro en línea y está esperando a que llegue.',
		'Gerund: 	   Ordering',
		'Ordering food delivery has become more popular in recent years.',
		'Pedir comida a domicilio se ha vuelto más popular en los últimos años.',
	],
	[
		'Inf. present: 	  plan',
		'He likes to plan his vacations well in advance.',
		'Le gusta planificar sus vacaciones con mucha anticipación.',
		'Inf. present: 	  plans',
		'He plans his day the night before to be more productive.',
		'Planea su día la noche anterior para ser más productivo.',
		'Past tense: 	  planned',
		"They planned a surprise party for their friend's birthday.",
		'Planearon una fiesta sorpresa para el cumpleaños de su amigo.',
		'Past participle: 	   planned',
		'The event was planned carefully to ensure its success.',
		'El evento fue planeado cuidadosamente para garantizar su éxito.',
		'Gerund: 	   Planning',
		'Planning ahead can save you time and money.',
		'Planificar con anticipación puede ahorrarle tiempo y dinero.',
	],
	[
		'Inf. present: 	  plant',
		'They like to plant flowers in their garden every spring.',
		'Les gusta plantar flores en su jardín cada primavera.',
		'Inf. present: 	  plants',
		'He plants a tree every year on Earth Day.',
		'Planta un árbol cada año en el Día de la Tierra.',
		'Past tense: 	  planted',
		'He planted a tree in his backyard last year.',
		'Plantó un árbol en su patio trasero el año pasado.',
		'Past participle: 	   planted',
		'She has planted a variety of herbs in her kitchen window.',
		'Ha plantado una variedad de hierbas en la ventana de su cocina.',
		'Gerund: 	  planting',
		'She loves planting flowers in her garden.',
		'Le encanta plantar flores en su jardín.',
	],
	[
		'Inf. present: 	  play',
		'She likes to play tennis with her friends on the weekends.',
		'Le gusta jugar tenis con sus amigos los fines de semana.',
		'Inf. present: 	  plays',
		'He plays basketball with his friends every weekend.',
		'Juega baloncesto con sus amigos todos los fines de semana.',
		'Past tense: 	  played',
		'They played soccer in high school and won many championships.',
		'Jugaron fútbol en la escuela secundaria y ganaron muchos campeonatos.',
		'Past participle: 	   played',
		'She has played the guitar since she was a teenager.',
		'Ha tocado la guitarra desde que era adolescente.',
		'Gerund: 	   Playing',
		'Playing video games can be a fun way to relax after a long day.',
		'Jugar videojuegos puede ser una forma divertida de relajarse después de un día largo.',
	],
	[
		'Inf. present: 	  point',
		'He likes to point out constellations in the night sky.',
		'Le gusta señalar las constelaciones en el cielo nocturno.',
		'Inf. present: 	  points',
		'She points to the map to show where we are.',
		'Señala el mapa para mostrar dónde estamos.',
		'Past tense: 	  pointed',
		'She pointed to the map to show where they were going.',
		'Señaló el mapa para mostrar dónde iban.',
		'Past participle: 	   pointed',
		'He has pointed to the need for more funding for education.',
		'Ha señalado la necesidad de más financiamiento para la educación.',
		'Gerund: 	   Pointing',
		'Pointing out mistakes can help us learn and improve.',
		'Señalar errores puede ayudarnos a aprender y mejorar.',
	],
	[
		'Inf. present: 	  practice',
		'They practice yoga together every morning.',
		'Practican yoga juntos todas las mañanas.',
		'Inf. present: 	  practices',
		'She practices yoga every morning to start her day off right.',
		'Practica yoga todas las mañanas para empezar bien el día.',
		'Past tense: 	  practiced',
		'They practiced their lines for the play until they had them memorized.',
		'Practicaron sus líneas para la obra hasta que las memorizaron.',
		'Past participle: 	   practiced',
		'The routine was practiced until it was perfect.',
		'La rutina se practicó hasta que fuera perfecta.',
		'Gerund: 	   Practicing',
		'Practicing a skill can help improve proficiency and mastery.',
		'Practicar una habilidad puede ayudar a mejorar la competencia y el dominio.',
	],
	[
		'Inf. present: 	  pushes',
		'He pushes the shopping cart while she selects the items.',
		'Empuja el carrito de compras mientras ella selecciona los artículos.',
		'Inf. present: 	  pushes',
		'She pushes herself to be the best she can be in everything she does.',
		'Se esfuerza por ser lo mejor que pueda ser en todo lo que hace.',
		'Past tense: 	  pushed',
		'She pushed her way through the crowd to get to the front.',
		'Se abrió camino a empujones entre la multitud para llegar al frente.',
		'Past participle: 	   pushed',
		'He has pushed through difficult times by staying positive and focused.',
		'Ha superado tiempos difíciles manteniéndose positivo y enfocado.',
		'Gerund: 	   Pushing',
		'Pushing a heavy object requires strength and effort.',
		'Empujar un objeto pesado requiere fuerza y esfuerzo.',
	],
	[
		'Inf. present: 	  rain',
		'It started to rain just as we left the house.',
		'Empezó a llover justo cuando salimos de la casa.',
		'Inf. present: 	  rains',
		'It often rains in this part of the country.',
		'A menudo llueve en esta parte del país.',
		'Past tense: 	  rained',
		'It rained all weekend, so they stayed indoors.',
		'Llovió todo el fin de semana, así que se quedaron adentro.',
		'Past participle: 	   rained',
		'It had rained all night, so the roads were wet in the morning.',
		'Había llovido toda la noche, así que las carreteras estaban mojadas por la mañana.',
		'Gerund: 	   rain',
		'Walking in the rain can be a fun and adventurous experience.',
		'Caminar bajo la lluvia puede ser una experiencia divertida y aventurera.',
	],
	[
		'Inf. present: 	  remember',
		'I always remember to lock the door before I leave the house.',
		'Siempre recuerdo cerrar la puerta con llave antes de salir de la casa.',
		'Inf. present: 	  remembers',
		'She remembers her childhood fondly, especially the summers she spent at the beach.',
		'Recuerda con cariño su infancia, especialmente los veranos que pasó en la playa.',
		'Past tense: 	  remembered',
		'I remembered to bring my umbrella, and I was glad I did when it started raining.',
		'Recordé traer mi paraguas, y me alegré de haberlo hecho cuando empezó a llover.',
		'Past participle: 	   remembered',
		'The event was remembered for years to come.',
		'El evento fue recordado durante años.',
		'Gerund: 	   Remembering',
		'Remembering to stay calm in stressful situations can be a challenge.',
		'Recordar mantener la calma en situaciones estresantes puede ser un desafío.',
	],
	[
		'Inf. present: 	  rent',
		'They rent an apartment in the city.',
		'Alquilan un apartamento en la ciudad.',
		'Past tense: 	  rented',
		'She rented a car for the weekend getaway.',
		'Alquiló un auto para la escapada de fin de semana.',
		'Past participle: 	   rented',
		'The house was rented out to vacationers during the summer.',
		'La casa se alquiló a vacacionistas durante el verano.',
		'Gerund: 	   Renting',
		'Renting a movie online is a convenient way to watch it at home.',
		'Alquilar una película en línea es una forma conveniente de verla en casa.',
	],
	[
		'Inf. present: 	  repeat',
		'He likes to repeat the phrases to practice his pronunciation.',
		'Le gusta repetir las frases para practicar su pronunciación.',
		'Past tense: 	  repeated',
		'They repeated the same mistake over and over again.',
		'Repetían el mismo error una y otra vez.',
		'Past participle: 	   repeated',
		'The song was repeated several times during the concert.',
		'La canción se repitió varias veces durante el concierto.',
		'Gerund: 	   Repeating',
		'Repeating a task can help improve skills and proficiency.',
		'Repetir una tarea puede ayudar a mejorar habilidades y competencia.',
	],
	[
		'Inf. present: 	  resist',
		'They try to resist eating junk food.',
		'Intentan resistir comer comida chatarra.',
		'Inf. present: 	  resists',
		"He resists the temptation to eat junk food, even when he's craving it.",
		'Resiste la tentación de comer comida chatarra, incluso cuando lo está deseando.',
		'Past tense: 	  resisted',
		'She resisted the temptation to buy the expensive dress.',
		'Resistió la tentación de comprar el vestido caro.',
		'Past participle: 	   resisted',
		"She has resisted change for so long that she's now stuck in her ways.",
		'Ha resistido el cambio durante tanto tiempo que ahora está atrapada en sus formas.',
		'Gerund: 	   Resisting',
		'Resisting temptation is a key part of building self-discipline.',
		'Resistir la tentación es una parte clave para desarrollar la autodisciplina.',
	],
	[
		'Inf. present: 	  shows',
		'He shows pictures of his travels to his friends.',
		'Muestra fotos de sus viajes a sus amigos.',
		'Inf. present: 	  shows',
		'She shows a lot of potential in her new job.',
		'Muestra mucho potencial en su nuevo trabajo.',
		'Past tense: 	  showed',
		'They showed up late to the meeting because of traffic.',
		'Llegaron tarde a la reunión debido al tráfico.',
		'Past participle: 	   showed',
		'The art exhibition showed works from local artists.',
		'La exposición de arte mostró obras de artistas locales.',
		'Gerund: 	   Showing',
		'Showing appreciation and gratitude can strengthen relationships.',
		'Mostrar aprecio y gratitud puede fortalecer las relaciones.',
	],
	[
		'Inf. present: 	  smoke',
		"He doesn't smoke cigarettes anymore.",
		'Ya no fuma cigarrillos.',
		'Inf. present: 	  smokes',
		'She smokes a pack a day and is trying to quit.',
		'Fuma una cajetilla al día y está tratando de dejarlo.',
		'Past tense: 	  smoked',
		'She smoked a cigar to celebrate her promotion.',
		'Fumó un cigarro para celebrar su ascenso.',
		'Past participle: 	   smoked',
		'He had smoked a cigarette before the meeting started.',
		'Había fumado un cigarrillo antes de que empezara la reunión.',
		'Gerund: 	   Smoking',
		'Smoking is harmful to your health and can cause many diseases.',
		'Fumar es perjudicial para la salud y puede causar muchas enfermedades.',
	],
	[
		'Inf. present: 	  start',
		'He wants to start a business of his own.',
		'Quiere iniciar su propio negocio.',
		'Inf. present: 	  starts',
		'She starts her day with a cup of coffee.',
		'Empieza su día con una taza de café.',
		'Past tense: 	  started',
		'He started his own business last year.',
		'Empezó su propio negocio el año pasado.',
		'Past participle: 	   started',
		'The race had already started when they arrived.',
		'La carrera ya había empezado cuando llegaron.',
		'Gerund: 	   Starting',
		'Starting a new project can be both exciting and challenging.',
		'Comenzar un nuevo proyecto puede ser emocionante y desafiante.',
	],
	[
		'Inf. present: 	  stay',
		'They like to stay at home on weekends.',
		'Les gusta quedarse en casa los fines de semana.',
		'Past tense: 	  stayed',
		'She stayed in a hotel during her vacation.',
		'Se quedó en un hotel durante sus vacaciones.',
		'Past participle: 	   stay',
		'I have stayed at that hotel before, and it was very nice.',
		'He estado alojado en ese hotel antes, y fue muy agradable.',
		'Gerund: 	   Staying',
		'Staying active and healthy can help improve quality of life.',
		'Quedarse activo y saludable puede ayudar a mejorar la calidad de vida.',
	],
	[
		'Inf. present: 	  stop',
		'I stop by the coffee shop every morning for a latte.',
		'Paso por la cafetería todas las mañanas para tomar un latte.',
		'Inf. present: 	  stops',
		'He stops to read the newspaper on his way to work.',
		'Se detiene a leer el periódico en su camino al trabajo.',
		'Past tense: 	  stopped',
		'She stopped eating meat last year.',
		'Dejó de comer carne el año pasado.',
		'Past participle: 	   stopped',
		'The music had stopped by the time they arrived.',
		'La música había parado cuando llegaron.',
		'Gerund: 	   Stopping',
		'Stopping to rest during a hike can be very refreshing.',
		'Detenerse a descansar durante una caminata puede ser muy refrescante.',
	],
	[
		'Inf. present: 	  study',
		'They study together at the library.',
		'Estudian juntos en la biblioteca.',
		'Inf. present: 	  studies',
		'She studies for her exams for hours every day.',
		'Estudia para sus exámenes durante horas todos los días.',
		'Past tense: 	  studied',
		'He studied biology in college.',
		'Estudió biología en la universidad.',
		'Past participle: 	   studied',
		'She has studied French for several years and is fluent.',
		'Ha estudiado francés durante varios años y es fluida.',
		'Gerund: 	   Studying',
		'Studying different cultures can be a fascinating experience.',
		'Estudiar diferentes culturas puede ser una experiencia fascinante.',
	],
	[
		'Inf. present: 	  talk',
		'We need to talk about the upcoming project and make a plan.',
		'Tenemos que hablar sobre el próximo proyecto y hacer un plan.',
		'Inf. present: 	  talks',
		'She talks on the phone with her sister every day.',
		'Habla por teléfono con su hermana todos los días.',
		'Past tense: 	  talked',
		'He talked to his boss about a raise.',
		'Habló con su jefe sobre un aumento.',
		'Past participle: 	   talked',
		'The issue was talked about extensively during the meeting.',
		'El tema se habló extensamente durante la reunión.',
		'Gerund: 	   Talking',
		'Talking to strangers can sometimes be intimidating.',
		'Hablar con desconocidos a veces puede ser intimidante.',
	],
	[
		'Inf. present: 	  travel',
		'They love to travel to new places.',
		'Les encanta viajar a lugares nuevos.',
		'Inf. present: 	  travels',
		'She travels for work almost every week.',
		'Viaja por trabajo casi todas las semanas.',
		'Past tense: 	  traveled',
		'She traveled to Europe last summer.',
		'Viajó a Europa el verano pasado.',
		'Past participle: 	   traveled',
		'He has traveled to over 20 countries in his lifetime.',
		'Ha viajado a más de 20 países en su vida.',
		'Gerund: 	   Traveling',
		'Traveling can broaden your horizons and help you grow as a person.',
		'Viajar puede ampliar tus horizontes y ayudarte a crecer como persona.',
	],
	[
		'Inf. present: 	  try',
		'I will try my best to finish the project on time.',
		'Haré todo lo posible para terminar el proyecto a tiempo.',
		'Inf. present: 	  tries',
		'He tries to exercise every day.',
		'Intenta hacer ejercicio todos los días.',
		'Past tense: 	  tried',
		'She tried a new restaurant last night.',
		'Probó un restaurante nuevo anoche.',
		'Past participle: 	   tried',
		"Have you ever tried sushi? It's delicious!",
		'¿Alguna vez has probado sushi? ¡Es delicioso!',
		'Gerund: 	   Trying',
		'Trying new things can be scary but can also lead to personal growth and development.',
		'Intentar cosas nuevas puede ser aterrador pero también puede conducir al crecimiento y desarrollo personal.',
	],
	[
		'Inf. present: 	  turns',
		'He turns left at the intersection.',
		'Gira a la izquierda en la intersección.',
		'Inf. present: 	  turns',
		'He turns the music down when he needs to focus.',
		'Baja el volumen de la música cuando necesita concentrarse.',
		'Past tense: 	  turned',
		'She turned off the lights before leaving the room.',
		'Apagó las luces antes de salir de la habitación.',
		'Past participle: 	   turned',
		'The page had already been turned when he noticed the mistake.',
		'La página ya había sido girada cuando notó el error.',
		'Gerund: 	   Turning',
		'Turning your attention to the present moment can help reduce stress and anxiety.',
		'Girar tu atención al momento presente puede ayudar a reducir el estrés y la ansiedad.',
	],
	[
		'Inf. present: 	  use',
		'I need to use the restroom.',
		'Necesito usar el baño.',
		'Inf. present: 	  uses',
		'She uses her laptop for work every day.',
		'Ella usa su laptop para el trabajo todos los días.',
		'Past participle: 	   used',
		'The company has used this marketing strategy before.',
		'La empresa ha utilizado esta estrategia de marketing antes.',
		'Past tense: 	  used',
		'He used to play basketball in high school.',
		'Solía jugar baloncesto en la escuela secundaria.',
		'Gerund: 	   Using',
		'Using a computer can make many tasks easier.',
		'Usar una computadora puede hacer muchas tareas más fáciles.',
	],
	[
		'Inf. present: 	  visit',
		'I want to visit my grandmother in the hospital.',
		'Quiero visitar a mi abuela en el hospital.',
		'Inf. present: 	  visits',
		'She visits her parents every weekend.',
		'Ella visita a sus padres todos los fines de semana.',
		'Past tense: 	  visited',
		'He visited New York City last year.',
		'Visitó la ciudad de Nueva York el año pasado.',
		'Past participle: 	   visited',
		'He has visited many countries in his lifetime.',
		'Ha visitado muchos países en su vida.',
		'Gerund: 	   Visiting',
		'Visiting new places can broaden your perspective.',
		'Visitar lugares nuevos puede ampliar tu perspectiva.',
	],
	[
		'Inf. present: 	  wait',
		"I can't wait to see the new movie.",
		'No puedo esperar para ver la nueva película.',
		'Inf. present: 	  waits',
		'She waits patiently for her turn in line.',
		'Ella espera pacientemente su turno en la fila.',
		'Past tense: 	  waited',
		'He waited in line for two hours to buy tickets.',
		'Esperó en la fila durante dos horas para comprar boletos.',
		'Past participle: 	   waited',
		'He has waited a long time for this opportunity.',
		'Ha esperado mucho tiempo por esta oportunidad.',
		'Gerund: 	   waiting',
		'She is waiting for her friend to arrive.',
		'Está esperando a que llegue su amiga.',
	],
	[
		'Inf. present: 	  walk',
		'They like to walk in the park on weekends.',
		'Les gusta caminar en el parque los fines de semana.',
		'Inf. present: 	  walks',
		'She walks to work every day instead of driving.',
		'Ella camina al trabajo todos los días en lugar de conducir.',
		'Past tense: 	  walked',
		'She walked home from work yesterday.',
		'Caminó a casa desde el trabajo ayer.',
		'Past participle: 	   walked',
		'The path had been walked by many hikers before.',
		'El camino había sido caminado por muchos excursionistas antes.',
		'Gerund: 	   Walking',
		'Walking is a great form of exercise and can improve overall health.',
		'Caminar es una excelente forma de ejercicio y puede mejorar la salud en general.',
	],
	[
		'Inf. present: 	  want',
		'I want a cup of coffee to wake me up.',
		'Quiero una taza de café para despertarme.',
		'Inf. present: 	  wants',
		'She wants to learn how to play the guitar.',
		'Ella quiere aprender a tocar la guitarra.',
		'Past tense: 	  wanted',
		'He wanted to go to the party but had to work late.',
		'Quería ir a la fiesta pero tuvo que trabajar hasta tarde.',
		'Past participle: 	   wanted',
		'She has always wanted to visit Paris.',
		'Siempre ha querido visitar París.',
		'Gerund: 	   Wanting',
		'Wanting something can drive motivation and action.',
		'Querer algo puede impulsar la motivación y la acción.',
	],
	[
		'Inf. present: 	  wash',
		'She needs to wash the dishes before she goes to bed.',
		'Necesita lavar los platos antes de acostarse.',
		'Past tense: 	  washed',
		'He washed the dishes after dinner.',
		'Lavó los platos después de la cena.',
		'Past participle: 	   washed',
		'She has washed the windows and they look so much cleaner now.',
		'Ha lavado las ventanas y ahora se ven mucho más limpias.',
		'Gerund: 	   Washing',
		'Washing your hands regularly is important for preventing the spread of germs.',
		'Lavarse las manos regularmente es importante para prevenir la propagación de gérmenes.',
	],
	[
		'Inf. present: 	  wishes',
		'She wishes to travel to Japan someday.',
		'Ella desea viajar a Japón algún día.',
		'Past tense: 	  wished',
		'He wished he had studied harder for the test.',
		'Deseó haber estudiado más para el examen.',
		'Past participle: 	   wish',
		'The wish had been granted by the time she woke up.',
		'El deseo había sido concedido cuando se despertó.',
		'Gerund: 	   Wishing',
		'Wishing for things can sometimes distract us from enjoying what we have.',
		'Desear cosas a veces nos puede distraer de disfrutar lo que tenemos.',
	],
	[
		'Inf. present: 	  work',
		'They work at a restaurant in downtown.',
		'Trabajan en un restaurante en el centro.',
		'Inf. present: 	  works',
		'He works long hours at his job to provide for his family.',
		'Trabaja largas horas en su trabajo para proveer a su familia.',
		'Past tense: 	  worked',
		'She worked overtime to finish the project on time.',
		'Trabajó horas extras para terminar el proyecto a tiempo.',
		'Past participle: 	   worked',
		'She has worked hard to become a successful entrepreneur.',
		'Ha trabajado duro para convertirse en una emprendedora exitosa.',
		'Gerund: 	   Working',
		'Working on a project with a team can be both challenging and rewarding.',
		'Trabajar en un proyecto con un equipo puede ser desafiante y gratificante.',
	],
];
