export default [
	{
		verb: 'To accept',
		verbo: 'aceptar',
		infinitive: 'I want to accept the invitation to the party.',
		infinitiveTranslation: 'Quiero aceptar la invitación a la fiesta.',
		present: 'She accepts the job offer last week and now works there.',
		presentTranslation: 'Ella acepta la oferta de trabajo la semana pasada y ahora trabaja allí.',
		past: 'He accepted the award for Best Actor at the ceremony last night.',
		pastTranslation: 'Él aceptó el premio al Mejor Actor en la ceremonia de anoche.',
		pastParticiple: 'I have accepted the terms of the contract.',
		pastParticipleTranslation: 'He aceptado los términos del contrato.',
		gerund: 'She is not used to accepting help from others.',
		gerundTranslation: 'Ella no está acostumbrada a aceptar ayuda de otros.',
	},
	{
		verb: 'To answer',
		verbo: 'responder',
		infinitive: 'He needs to answer the phone.',
		infinitiveTranslation: 'Él necesita responder el teléfono.',
		present: 'She always answers my questions.',
		presentTranslation: 'Ella siempre responde mis preguntas.',
		past: "He answered the interviewer's questions with confidence.",
		pastTranslation: 'Él respondió las preguntas del entrevistador con confianza.',
		pastParticiple: 'I have answered all of the questions on the quiz.',
		pastParticipleTranslation: 'He respondido todas las preguntas del cuestionario.',
		gerund: 'She is used to answering emails every day.',
		gerundTranslation: 'Ella está acostumbrada a responder correos electrónicos todos los días.',
	},
	{
		verb: 'To arrive',
		verbo: 'llegar',
		infinitive: 'We plan to arrive at the airport two hours before our flight.',
		infinitiveTranslation: 'Planeamos llegar al aeropuerto dos horas antes de nuestro vuelo.',
		present: 'The train arrives at the station in five minutes.',
		presentTranslation: 'El tren llega a la estación en cinco minutos.',
		past: 'I arrived at the party late because of traffic.',
		pastTranslation: 'Llegué tarde a la fiesta por el tráfico.',
		pastParticiple: 'She has just arrived home from work.',
		pastParticipleTranslation: 'Ella acaba de llegar a casa del trabajo.',
		gerund: 'He enjoys arriving early to avoid the crowds.',
		gerundTranslation: 'A él le gusta llegar temprano para evitar las multitudes.',
	},
	{
		verb: 'To ask',
		verbo: 'preguntar',
		infinitive: 'I need to ask him a question.',
		infinitiveTranslation: 'Necesito hacerle una pregunta.',
		present: 'She asks a lot of questions in class.',
		presentTranslation: 'Ella hace muchas preguntas en clase.',
		past: 'He asked her out on a date last night.',
		pastTranslation: 'Anoche él la invitó a salir en una cita.',
		pastParticiple: 'I have asked for help, but no one seems to be available.',
		pastParticipleTranslation: 'He pedido ayuda, pero parece que nadie está disponible.',
		gerund: 'Asking for a raise can be intimidating.',
		gerundTranslation: 'Pedir un aumento puede ser intimidante.',
	},
	{
		verb: 'To belong',
		verbo: 'pertenecer',
		infinitive: 'The book belongs on the shelf.',
		infinitiveTranslation: 'El libro pertenece a la estantería.',
		present: 'The keys belong to the blue car.',
		presentTranslation: 'Las llaves pertenecen al coche azul.',
		past: 'She belonged to the drama club in high school.',
		pastTranslation: 'Ella pertenecía al club de teatro en la escuela secundaria.',
		pastParticiple: 'This book belongs to me.',
		pastParticipleTranslation: 'Este libro me pertenece a mí.',
		gerund: 'Belonging to a community can be very fulfilling.',
		gerundTranslation: 'Pertenecer a una comunidad puede ser muy gratificante.',
	},
	{
		verb: 'To bother',
		verbo: 'molestar',
		infinitive: "Don't bother him, he's busy.",
		infinitiveTranslation: 'No le molestes, está ocupado.',
		present: "Her loud music bothers me when I'm trying to work.",
		presentTranslation: 'Su música alta me molesta cuando estoy tratando de trabajar.',
		past: 'He bothered to read the instructions before starting the project.',
		pastTranslation: 'Se molestó en leer las instrucciones antes de empezar el proyecto.',
		pastParticiple: "I'm sorry to bother you, but do you have a minute to talk?",
		pastParticipleTranslation: 'Lo siento por molestarte, ¿tienes un minuto para hablar?',
		gerund: 'Bothering others is not a good way to make friends.',
		gerundTranslation: 'Molestar a los demás no es una buena manera de hacer amigos.',
	},
	{
		verb: 'To change',
		verbo: 'cambiar',
		infinitive: 'I want to change my hairstyle.',
		infinitiveTranslation: 'Quiero cambiar mi peinado.',
		present: 'He changes his mind a lot.',
		presentTranslation: 'Él cambia de opinión muchas veces.',
		past: 'She changed her phone number last month.',
		pastTranslation: 'Ella cambió su número de teléfono el mes pasado.',
		pastParticiple: 'I have changed my password for security reasons.',
		pastParticipleTranslation: 'He cambiado mi contraseña por motivos de seguridad.',
		gerund: 'Changing your diet can have a big impact on your health.',
		gerundTranslation: 'Cambiar tu dieta puede tener un gran impacto en tu salud.',
	},
	{
		verb: 'To clean',
		verbo: 'limpiar',
		infinitive: 'We need to clean the house before the guests arrive.',
		infinitiveTranslation: 'Necesitamos limpiar la casa antes de que lleguen los invitados.',
		present: 'She cleans the kitchen every night after dinner.',
		presentTranslation: 'Ella limpia la cocina todas las noches después de cenar.',
		past: 'He cleaned his car last weekend.',
		pastTranslation: 'Limpió su coche el fin de semana pasado.',
		pastParticiple: "I have cleaned the bathroom, so it's ready for guests.",
		pastParticipleTranslation: 'He limpiado el baño, así que está listo para los invitados.',
		gerund: 'Cleaning up after a party is never fun.',
		gerundTranslation: 'Limpiar después de una fiesta nunca es divertido.',
	},
	{
		verb: 'To climb',
		verbo: 'escalar',
		infinitive: 'We plan to climb the mountain next summer.',
		infinitiveTranslation: 'Planeamos escalar la montaña el próximo verano.',
		present: 'He climbs the stairs instead of taking the elevator.',
		presentTranslation: 'Él sube las escaleras en lugar de tomar el ascensor.',
		past: 'They climbed to the top of the tower and took some amazing photos.',
		pastTranslation: 'Escalaron hasta la cima de la torre y tomaron algunas fotos increíbles.',
		pastParticiple: "I have climbed this mountain before, and it's not easy.",
		pastParticipleTranslation: 'He escalado esta montaña antes, y no es fácil.',
		gerund: 'Climbing a tree can be a fun activity for kids.',
		gerundTranslation: 'Escalar un árbol puede ser una actividad divertida para los niños.',
	},
	{
		verb: 'To close',
		verbo: 'cerrar',
		infinitive: 'Please close the door behind you.',
		infinitiveTranslation: 'Por favor, cierra la puerta detrás de ti.',
		present: 'The store closes at 9 pm every day.',
		presentTranslation: 'La tienda cierra a las 9 pm todos los días.',
		past: 'He closed his laptop and went to bed.',
		pastTranslation: 'Cerró su laptop y se fue a dormir.',
		pastParticiple: 'I have closed the deal, and we are now partners.',
		pastParticipleTranslation: 'He cerrado el trato, y ahora somos socios.',
		gerund: 'Closing the door quietly, she left the room.',
		gerundTranslation: 'Cerrando la puerta suavemente, ella salió de la habitación.',
	},
	{
		verb: 'To consider',
		verbo: 'considerar',
		infinitive: 'I need to consider my options before making a decision.',
		infinitiveTranslation: 'Necesito considerar mis opciones antes de tomar una decisión.',
		present: 'He considers himself lucky to have such a supportive family.',
		presentTranslation: 'Se considera afortunado de tener una familia tan solidaria.',
		past: 'They considered several candidates before choosing the right person for the job.',
		pastTranslation: 'Consideraron varios candidatos antes de elegir a la persona adecuada para el trabajo.',
		pastParticiple: 'I have considered quitting my job and traveling the world.',
		pastParticipleTranslation: 'He considerado renunciar a mi trabajo y viajar por el mundo.',
		gerund: 'Considering the circumstances, I think we did the best we could.',
		gerundTranslation: 'Considerando las circunstancias, creo que hicimos lo mejor que pudimos.',
	},
	{
		verb: 'To cook',
		verbo: 'cocinar',
		infinitive: 'I love to cook Italian food.',
		infinitiveTranslation: 'Me encanta cocinar comida italiana.',
		present: 'She cooks dinner for her family every night.',
		presentTranslation: 'Cocina la cena para su familia todas las noches.',
		past: "He cooked a delicious meal for his girlfriend's birthday.",
		pastTranslation: 'Cocinó una comida deliciosa para el cumpleaños de su novia.',
		pastParticiple: 'I have cooked this recipe before, and it always turns out well.',
		pastParticipleTranslation: 'He cocinado esta receta antes, y siempre queda bien.',
		gerund: 'Cooking together can be a fun date night activity.',
		gerundTranslation: 'Cocinar juntos puede ser una actividad divertida para una noche de cita.',
	},
	{
		verb: 'To count',
		verbo: 'contar',
		infinitive: 'You can always count on me to help you.',
		infinitiveTranslation: 'Siempre puedes contar conmigo para ayudarte.',
		present: 'He counts his blessings every day.',
		presentTranslation: 'Cuenta sus bendiciones todos los días.',
		past: 'They counted the votes and announced the winner.',
		pastTranslation: 'Contaron los votos y anunciaron el ganador.',
		pastParticiple: 'I have counted the days until my vacation for months.',
		pastParticipleTranslation: 'He ha contado los días hasta mis vacaciones durante meses.',
		gerund: 'Counting sheep is a popular method to help you fall asleep.',
		gerundTranslation: 'Contar ovejas es un método popular para ayudarte a dormir.',
	},
	{
		verb: 'To dance',
		verbo: 'bailar',
		infinitive: 'I want to learn how to dance salsa.',
		infinitiveTranslation: 'Quiero aprender a bailar salsa.',
		present: 'She dances every Saturday night at the local club.',
		presentTranslation: 'Baila todos los sábados por la noche en el club local.',
		past: 'We danced for hours at the wedding reception.',
		pastTranslation: 'Bailamos durante horas en la recepción de la boda.',
		pastParticiple: 'I have danced in many different countries around the world.',
		pastParticipleTranslation: 'He bailado en muchos países diferentes alrededor del mundo.',
		gerund: 'Dancing is a great way to exercise and have fun at the same time.',
		gerundTranslation: 'Bailar es una excelente manera de hacer ejercicio y divertirse al mismo tiempo.',
	},
	{
		verb: 'To dare',
		verbo: 'atreverse',
		infinitive: "I didn't dare to speak to him because he seemed angry.",
		infinitiveTranslation: 'No me atreví a hablarle porque parecía enojado.',
		present: 'She dares to speak her mind even when others disagree with her.',
		presentTranslation: 'Se atreve a decir lo que piensa incluso cuando los demás no están de acuerdo con ella.',
		past: 'He dared to climb the mountain even though it was dangerous.',
		pastTranslation: 'Se atrevió a subir la montaña aunque era peligroso.',
		pastParticiple: 'I have never dared to skydive, but maybe one day I will.',
		pastParticipleTranslation: 'Nunca me he atrevido a hacer paracaidismo, pero tal vez algún día lo haga.',
		gerund: 'Daring to take risks is an important part of personal growth.',
		gerundTranslation: 'Atreverse a tomar riesgos es una parte importante del crecimiento personal.',
	},
	{
		verb: 'To date',
		verbo: 'salir con alguien',
		infinitive: 'She wants to date someone who shares her interests.',
		infinitiveTranslation: 'Quiere salir con alguien que comparta sus intereses.',
		present: 'He dates a different person every week.',
		presentTranslation: 'Sale con una persona diferente cada semana.',
		past: 'We dated for three years before getting married.',
		pastTranslation: 'Salimos juntos durante tres años antes de casarnos.',
		pastParticiple: 'I have dated people from many different cultures and backgrounds.',
		pastParticipleTranslation: 'He salido con personas de muchas culturas y antecedentes diferentes.',
		gerund: 'Dating can be a fun way to get to know someone new.',
		gerundTranslation: 'Salir con alguien puede ser una forma divertida de conocer a alguien nuevo.',
	},
	{
		verb: 'To deliver',
		verbo: 'entregar',
		infinitive: 'I need to deliver this package before noon.',
		infinitiveTranslation: 'Necesito entregar este paquete antes del mediodía.',
		present: 'He delivers the newspaper to our house every morning.',
		presentTranslation: 'Entrega el periódico a nuestra casa todas las mañanas.',
		past: 'We delivered the project on time and under budget.',
		pastTranslation: 'Entregamos el proyecto a tiempo y dentro del presupuesto.',
		pastParticiple: 'I have delivered many speeches in my career as a public speaker.',
		pastParticipleTranslation: 'He dado muchos discursos en mi carrera como orador público.',
		gerund: "Delivering bad news is never easy, but it's part of the job.",
		gerundTranslation: 'Entregar malas noticias nunca es fácil, pero es parte del trabajo.',
	},
	{
		verb: 'To dress',
		verbo: 'vestirse',
		infinitive: "I don't know how to dress for this occasion.",
		infinitiveTranslation: 'No sé cómo vestirme para esta ocasión.',
		present: 'She dresses very elegantly for work.',
		presentTranslation: 'Se viste muy elegantemente para el trabajo.',
		past: 'We dressed up as superheroes for Halloween.',
		pastTranslation: 'Nos disfrazamos de superhéroes para Halloween.',
		pastParticiple: 'I have dressed in many different styles over the years.',
		pastParticipleTranslation: 'Me he vestido con muchos estilos diferentes a lo largo de los años.',
		gerund: 'Dressing well can give you confidence and make you feel good about yourself.',
		gerundTranslation: 'Vestir bien puede darte confianza y hacerte sentir bien contigo mismo.',
	},
	{
		verb: 'To end',
		verbo: 'terminar',
		infinitive: 'I hope this meeting will end soon.',
		infinitiveTranslation: 'Espero que esta reunión termine pronto.',
		present: 'The concert ends at 10 pm.',
		presentTranslation: 'El concierto termina a las 10 pm.',
		past: 'We ended our relationship because we had different goals.',
		pastTranslation: 'Terminamos nuestra relación porque teníamos metas diferentes.',
		pastParticiple: 'I have ended friendships that were toxic or unhealthy for me.',
		pastParticipleTranslation: 'He terminado amistades que eran tóxicas o poco saludables para mí.',
		gerund: "Ending a relationship is never easy, but sometimes it's necessary.",
		gerundTranslation: 'Terminar una relación nunca es fácil, pero a veces es necesario.',
	},
	{
		verb: 'To enjoy',
		verbo: 'disfrutar',
		infinitive: 'I enjoy spending time with my family.',
		infinitiveTranslation: 'Disfruto pasar tiempo con mi familia.',
		present: 'She enjoys listening to music while she works.',
		presentTranslation: 'Disfruta escuchar música mientras trabaja.',
		past: 'We enjoyed our vacation in Hawaii last year.',
		pastTranslation: 'Disfrutamos nuestras vacaciones en Hawái el año pasado.',
		pastParticiple: 'I have enjoyed reading books since I was a child.',
		pastParticipleTranslation: 'He disfrutado leyendo libros desde que era niño.',
		gerund: 'Enjoying the simple things in life can bring you a lot of happiness.',
		gerundTranslation: 'Disfrutar de las cosas simples de la vida puede traerte mucha felicidad.',
	},
	{
		verb: 'To erase',
		verbo: 'borrar',
		infinitive: 'Can you erase this mistake on the whiteboard?',
		infinitiveTranslation: '¿Puedes borrar este error del pizarrón?',
		present: 'She erases all of her text messages after she reads them.',
		presentTranslation: 'Borra todos sus mensajes de texto después de leerlos.',
		past: 'We erased the whiteboard before the next class started.',
		pastTranslation: 'Borramos el pizarrón antes de que empezara la siguiente clase.',
		pastParticiple: 'I have erased all of my old emails from my inbox.',
		pastParticipleTranslation: 'He borrado todos mis correos electrónicos antiguos de mi bandeja de entrada.',
		gerund: 'Erasing a mistake can be a simple way to correct it.',
		gerundTranslation: 'Borrar un error puede ser una manera simple de corregirlo.',
	},
	{
		verb: 'To expect',
		verbo: 'esperar',
		infinitive: "I don't expect any problems during the trip.",
		infinitiveTranslation: 'No espero ningún problema durante el viaje.',
		present: 'He expects to graduate from college next year.',
		presentTranslation: 'Espera graduarse de la universidad el próximo año.',
		past: "We didn't expect so many people to show up for the party.",
		pastTranslation: 'No esperábamos que tanta gente viniera a la fiesta.',
		pastParticiple: 'I have expected more from people and been disappointed.',
		pastParticipleTranslation: 'He esperado más de las personas y he quedado decepcionado.',
		gerund: 'Expecting the unexpected can help you prepare for the worst.',
		gerundTranslation: 'Esperar lo inesperado puede ayudarte a prepararte para lo peor.',
	},
	{
		verb: 'To fill',
		verbo: 'llenar',
		infinitive: 'Can you fill this glass with water?',
		infinitiveTranslation: '¿Puedes llenar este vaso con agua?',
		present: 'She fills out her timesheet every week.',
		presentTranslation: 'Completa su hoja de horas todas las semanas.',
		past: 'We filled the car up with gas before we hit the road.',
		pastTranslation: 'Llenamos el auto con gasolina antes de salir a la carretera.',
		pastParticiple: 'I have filled out the form and submitted it.',
		pastParticipleTranslation: 'He llenado el formulario y lo he enviado.',
		gerund: 'Filling the gaps in your knowledge can help you learn more.',
		gerundTranslation: 'Completar las lagunas en su conocimiento puede ayudarle a aprender más.',
	},
	{
		verb: 'To finish',
		verbo: 'terminar',
		infinitive: 'I need to finish this report by the end of the day.',
		infinitiveTranslation: 'Necesito terminar este informe para el final del día.',
		present: 'He finishes work at 6pm every day.',
		presentTranslation: 'Termina su trabajo a las 6 pm todos los días.',
		past: 'We finished our meal and left the restaurant.',
		pastTranslation: 'Terminamos nuestra comida y salimos del restaurante.',
		pastParticiple: 'She has finished reading the book already.',
		pastParticipleTranslation: 'Ya ha terminado de leer el libro.',
		gerund: 'Finishing the project ahead of schedule will impress the boss.',
		gerundTranslation: 'Terminar el proyecto antes de lo previsto impresionará al jefe.',
	},
	{
		verb: 'To follow',
		verbo: 'seguir',
		infinitive: 'I always follow my dreams, no matter what.',
		infinitiveTranslation: 'Siempre sigo mis sueños, pase lo que pase.',
		present: 'She follows the instructions carefully.',
		presentTranslation: 'Sigue las instrucciones con cuidado.',
		past: 'They followed the directions on the map to get to the beach.',
		pastTranslation: 'Siguen las indicaciones del mapa para llegar a la playa.',
		pastParticiple: "He has followed in his father's footsteps and become a doctor.",
		pastParticipleTranslation: 'Ha seguido los pasos de su padre y se ha convertido en médico.',
		gerund: 'Following your heart is the key to a happy life.',
		gerundTranslation: 'Seguir tu corazón es la clave de una vida feliz.',
	},
	{
		verb: 'To help',
		verbo: 'ayudar',
		infinitive: 'Can you help me carry this box upstairs?',
		infinitiveTranslation: '¿Puedes ayudarme a subir esta caja por las escaleras?',
		present: 'She helps her colleagues with their work when they need it.',
		presentTranslation: 'Ayuda a sus colegas con su trabajo cuando lo necesitan.',
		past: 'We helped our neighbor fix his car yesterday.',
		pastTranslation: 'Ayer ayudamos a nuestro vecino a arreglar su coche.',
		pastParticiple: 'He has helped many people in need throughout his life.',
		pastParticipleTranslation: 'Ha ayudado a muchas personas necesitadas a lo largo de su vida.',
		gerund: 'Helping others can be very rewarding.',
		gerundTranslation: 'Ayudar a los demás puede ser muy gratificante.',
	},
	{
		verb: 'To hurry',
		verbo: 'apresurarse',
		infinitive: 'We need to hurry if we want to catch the train.',
		infinitiveTranslation: 'Tenemos que apurarnos si queremos tomar el tren.',
		present: 'She hurries to finish her work before the deadline.',
		presentTranslation: 'Se apresura a terminar su trabajo antes de la fecha límite.',
		past: 'They hurried to get to the airport on time.',
		pastTranslation: 'Se apresuraron para llegar al aeropuerto a tiempo.',
		pastParticiple: 'He has hurried through life, never stopping to enjoy the little things.',
		pastParticipleTranslation:
			'Se ha apresurado a través de la vida, nunca deteniéndose a disfrutar las pequeñas cosas.',
		gerund: 'Hurrying is not always the best solution.',
		gerundTranslation: 'Apresurarse no siempre es la mejor solución.',
	},
	{
		verb: 'To intend',
		verbo: 'tener laintención',
		infinitive: 'I intend to finish this project by the end of the week.',
		infinitiveTranslation: 'Tengo la intención de terminar este proyecto para el final de la semana.',
		present: 'He intends to apply for the job before the deadline.',
		presentTranslation: 'Tiene la intención de solicitar el trabajo antes de la fecha límite.',
		past: 'We intended to go to the party, but we got stuck in traffic.',
		pastTranslation: 'Teníamos la intención de ir a la fiesta, pero nos quedamos atrapados en el tráfico.',
		pastParticiple: 'She has always intended to travel the world.',
		pastParticipleTranslation: 'Siempre ha tenido la intención de viajar por el mundo.',
		gerund: 'Intending to do something is not the same as actually doing it.',
		gerundTranslation: 'Tener la intención de hacer algo no es lo mismo que hacerlo realmente.',
	},
	{
		verb: 'To jump',
		verbo: 'saltar',
		infinitive: 'She can jump over the fence with ease.',
		infinitiveTranslation: 'Ella puede saltar por encima de la cerca con facilidad.',
		present: 'He jumps up and down when he gets excited.',
		presentTranslation: 'Salta arriba y abajo cuando se emociona.',
		past: 'They jumped over the puddle to avoid getting their shoes wet.',
		pastTranslation: 'Saltaron sobre el charco para evitar mojarse los zapatos.',
		pastParticiple: 'She has jumped out of an airplane before.',
		pastParticipleTranslation: 'Ha saltado de un avión antes.',
		gerund: 'Jumping on the bed is not allowed!',
		gerundTranslation: '¡No se permite saltar en la cama!',
	},
	{
		verb: 'To learn',
		verbo: 'aprender',
		infinitive: 'I want to learn how to play the guitar.',
		infinitiveTranslation: 'Quiero aprender a tocar la guitarra.',
		present: 'She learns quickly and easily.',
		presentTranslation: 'Aprende rápido y fácilmente.',
		past: 'He learned how to swim when he was a child.',
		pastTranslation: 'Aprendió a nadar cuando era niño.',
		pastParticiple: 'She has learned a lot from her mistakes.',
		pastParticipleTranslation: 'Ha aprendido mucho de sus errores.',
		gerund: 'Learning a new language can be challenging but rewarding.',
		gerundTranslation: 'Aprender un nuevo idioma puede ser desafiante pero gratificante.',
	},
	{
		verb: 'To lie',
		verbo: 'mentir',
		infinitive: 'He lies to his parents about his grades.',
		infinitiveTranslation: 'Les miente a sus padres sobre sus calificaciones.',
		present: 'She lies about her age to get into clubs.',
		presentTranslation: 'Miente sobre su edad para entrar en clubs.',
		past: 'They lied to the police about their whereabouts on the night of the crime.',
		pastTranslation: 'Mintieron a la policía sobre su paradero la noche del crimen.',
		pastParticiple: 'He has lied to his best friend about borrowing money.',
		pastParticipleTranslation: 'Le ha mentido a su mejor amigo sobre pedir dinero prestado.',
		gerund: 'Lying is not a good habit to have.',
		gerundTranslation: 'Mentir no es un buen hábito para tener.',
	},
	{
		verb: 'To like',
		verbo: 'gustar',
		infinitive: 'She likes to read books in her free time.',
		infinitiveTranslation: 'Le gusta leer libros en su tiempo libre.',
		present: 'He likes to watch movies on the weekends.',
		presentTranslation: 'Le gusta ver películas los fines de semana.',
		past: 'They liked the restaurant so much that they went back the next day.',
		pastTranslation: 'Les gustó tanto el restaurante que volvieron al día siguiente.',
		pastParticiple: 'She has always liked the color blue.',
		pastParticipleTranslation: 'Siempre le ha gustado el color azul.',
		gerund: 'Liking something is not the same as loving it.',
		gerundTranslation: 'Gustar algo no es lo mismo que amarlo.',
	},
	{
		verb: 'To listen',
		verbo: 'escuchar',
		infinitive: 'I like to listen to music while I work.',
		infinitiveTranslation: 'Me gusta escuchar música mientras trabajo.',
		present: 'She listens to her favorite podcast every morning.',
		presentTranslation: 'Escucha su podcast favorito todas las mañanas.',
		past: "They listened to their grandfather's stories with rapt attention.",
		pastTranslation: 'Escucharon las historias de su abuelo con atención total.',
		pastParticiple: 'He has listened to this song so many times that he knows every word by heart.',
		pastParticipleTranslation: 'Ha escuchado esta canción tantas veces que se sabe todas las letras de memoria.',
		gerund: 'Listening to others is an important part of communication.',
		gerundTranslation: 'Escuchar a los demás es una parte importante de la comunicación.',
	},
	{
		verb: 'To live',
		verbo: 'vivir',
		infinitive: 'She lives in a small apartment in the city.',
		infinitiveTranslation: 'Vive en un pequeño apartamento en la ciudad.',
		present: 'He lives with his parents while he saves money to buy a house.',
		presentTranslation: 'Vive con sus padres mientras ahorra para comprar una casa.',
		past: 'They lived in Paris for three years before moving back to the US.',
		pastTranslation: 'Vivieron en París durante tres años antes de regresar a los Estados Unidos.',
		pastParticiple: 'She has lived a long and fulfilling life.',
		pastParticipleTranslation: 'Ha vivido una vida larga y satisfactoria.',
		gerund: 'Living in the moment is a good way to reduce stress and anxiety.',
		gerundTranslation: 'Vivir el momento es una buena manera de reducir el estrés y la ansiedad.',
	},
	{
		verb: 'To look',
		verbo: 'mirar',
		infinitive: 'He looks tired today.',
		infinitiveTranslation: 'Se ve cansado hoy.',
		present: 'She looks beautiful in that dress.',
		presentTranslation: 'Se ve hermosa con ese vestido.',
		past: 'They looked for their lost dog all night.',
		pastTranslation: 'Buscaban a su perro perdido toda la noche.',
		pastParticiple: "He has looked everywhere for his keys but can't find them.",
		pastParticipleTranslation: 'Ha buscado por todas partes sus llaves pero no las encuentra.',
		gerund: 'Looking both ways before crossing the street is a good habit to have.',
		gerundTranslation: 'Mirar a ambos lados antes de cruzar la calle es un buen hábito para tener.',
	},
	{
		verb: 'To love',
		verbo: 'amar',
		infinitive: 'I love spending time with my family.',
		infinitiveTranslation: 'Me encanta pasar tiempo con mi familia.',
		present: 'He loves to read before going to bed.',
		presentTranslation: 'Le encanta leer antes de ir a la cama.',
		past: 'They loved their trip to Europe last summer.',
		pastTranslation: 'Les encantó su viaje a Europa el verano pasado.',
		pastParticiple: 'She has loved him since the day they met.',
		pastParticipleTranslation: 'Lo ha amado desde el día en que se conocieron.',
		gerund: 'Loving someone means accepting them for who they are.',
		gerundTranslation: 'Amar a alguien significa aceptarlo por lo que es.',
	},
	{
		verb: 'To miss',
		verbo: 'extrañar',
		infinitive: "I miss my family when I'm away from home.",
		infinitiveTranslation: 'Extraño a mi familia cuando estoy lejos de casa.',
		present: 'She misses her old job sometimes, but she loves her new one too.',
		presentTranslation: 'A veces extraña su antiguo trabajo, pero también ama el nuevo.',
		past: 'They missed their flight and had to book another one.',
		pastTranslation: 'Perdieron su vuelo y tuvieron que reservar otro.',
		pastParticiple: 'He has missed several important events because of work.',
		pastParticipleTranslation: 'Se ha perdido varios eventos importantes debido al trabajo.',
		gerund: 'Missing someone can be a painful experience.',
		gerundTranslation: 'Extrañar a alguien puede ser una experiencia dolorosa.',
	},
	{
		verb: 'To name',
		verbo: 'nombrar',
		infinitive: 'She named her dog after her favorite character in a book.',
		infinitiveTranslation: 'Nombró a su perro en honor a su personaje favorito de un libro.',
		present: 'He names all of his plants after famous artists.',
		presentTranslation: 'Nombra todas sus plantas en honor a artistas famosos.',
		past: 'They named their first child after their grandparents.',
		pastTranslation: 'Nombraron a su primer hijo en honor a sus abuelos.',
		pastParticiple: 'She has named over 50 species of insects during her career.',
		pastParticipleTranslation: 'Ha nombrado más de 50 especies de insectos durante su carrera.',
		gerund: 'Naming a new product can be a challenging process.',
		gerundTranslation: 'Nombrar un nuevo producto puede ser un proceso desafiante.',
	},
	{
		verb: 'To need',
		verbo: 'necesitar',
		infinitive: 'I need to finish this project before the deadline.',
		infinitiveTranslation: 'Necesito terminar este proyecto antes de la fecha límite.',
		present: 'He needs a cup of coffee to start his day.',
		presentTranslation: 'Necesita una taza de café para empezar su día.',
		past: 'They needed extra help to complete the task on time.',
		pastTranslation: 'Necesitaban ayuda extra para completar la tarea a tiempo.',
		pastParticiple: 'She has needed to take a break from work for a while.',
		pastParticipleTranslation: 'Ha necesitado tomar un descanso del trabajo por un tiempo.',
		gerund: 'Needing assistance is not a sign of weakness.',
		gerundTranslation: 'Necesitar ayuda no es una señal de debilidad.',
	},
	{
		verb: 'To open',
		verbo: 'abrir',
		infinitive: 'Can you open the window, please?',
		infinitiveTranslation: '¿Puedes abrir la ventana, por favor?',
		present: 'He opens the door for his clients as a sign of respect.',
		presentTranslation: 'Abre la puerta para sus clientes como muestra de respeto.',
		past: 'They opened a new branch of their business in a different city.',
		pastTranslation: 'Abrieron una nueva sucursal de su negocio en una ciudad diferente.',
		pastParticiple: 'She has opened up about her struggles with mental health.',
		pastParticipleTranslation: 'Ha hablado abiertamente sobre sus luchas con la salud mental.',
		gerund: 'Opening up to someone can be a difficult but rewarding experience.',
		gerundTranslation: 'Abrirse a alguien puede ser una experiencia difícil pero gratificante.',
	},
	{
		verb: 'To order',
		verbo: 'ordenar/pedir',
		infinitive: "I always order pizza when I don't feel like cooking.",
		infinitiveTranslation: 'Siempre pido pizza cuando no tengo ganas de cocinar.',
		present: 'He orders the same thing every time he goes to that restaurant.',
		presentTranslation: 'Siempre pide lo mismo cada vez que va a ese restaurante.',
		past: 'They ordered a bottle of wine to celebrate their anniversary.',
		pastTranslation: 'Pidieron una botella de vino para celebrar su aniversario.',
		pastParticiple: 'She has ordered a book online and is waiting for it to arrive.',
		pastParticipleTranslation: 'Ha pedido un libro en línea y está esperando a que llegue.',
		gerund: 'Ordering food delivery has become more popular in recent years.',
		gerundTranslation: 'Pedir comida a domicilio se ha vuelto más popular en los últimos años.',
	},
	{
		verb: 'To plan',
		verbo: 'planificar',
		infinitive: 'We need to plan our vacation in advance.',
		infinitiveTranslation: 'Necesitamos planear nuestras vacaciones con anticipación.',
		present: 'He plans his day the night before to be more productive.',
		presentTranslation: 'Planea su día la noche anterior para ser más productivo.',
		past: "They planned a surprise party for their friend's birthday.",
		pastTranslation: 'Planearon una fiesta sorpresa para el cumpleaños de su amigo.',
		pastParticiple: 'She has planned every detail of the project to ensure its success.',
		pastParticipleTranslation: 'Ha planeado cada detalle del proyecto para asegurar su éxito.',
		gerund: 'Planning ahead can save you time and money.',
		gerundTranslation: 'Planificar con anticipación puede ahorrarle tiempo y dinero.',
	},
	{
		verb: 'To plant',
		verbo: 'plantar',
		infinitive: 'She loves planting flowers in her garden.',
		infinitiveTranslation: 'Le encanta plantar flores en su jardín.',
		present: 'He plants a tree every year on Earth Day.',
		presentTranslation: 'Planta un árbol cada año en el Día de la Tierra.',
		past: 'They planted a vegetable garden in their backyard.',
		pastTranslation: 'Plantaron un huerto en su patio trasero.',
		pastParticiple: 'She has planted a variety of herbs in her kitchen window.',
		pastParticipleTranslation: 'Ha plantado una variedad de hierbas en la ventana de su cocina.',
		gerund: 'Planting trees helps to reduce air pollution and combat climate change.',
		gerundTranslation: 'Plantar árboles ayuda a reducir la contaminación del aire y combatir el cambio climático.',
	},
	{
		verb: 'To play',
		verbo: 'jugar',
		infinitive: 'They like to play board games on rainy days.',
		infinitiveTranslation: 'Les gusta jugar juegos de mesa en días lluviosos.',
		present: 'He plays basketball with his friends every weekend.',
		presentTranslation: 'Juega baloncesto con sus amigos todos los fines de semana.',
		past: 'They played soccer in high school and won many championships.',
		pastTranslation: 'Jugaron fútbol en la escuela secundaria y ganaron muchos campeonatos.',
		pastParticiple: 'She has played the guitar since she was a teenager.',
		pastParticipleTranslation: 'Ha tocado la guitarra desde que era adolescente.',
		gerund: 'Playing video games can be a fun way to relax after a long day.',
		gerundTranslation: 'Jugar videojuegos puede ser una forma divertida de relajarse después de un día largo.',
	},
	{
		verb: 'To point',
		verbo: 'señalar',
		infinitive: 'He pointed out the mistake in my calculations.',
		infinitiveTranslation: 'Señaló el error en mis cálculos.',
		present: 'She points to the map to show where we are.',
		presentTranslation: 'Señala el mapa para mostrar dónde estamos.',
		past: 'They pointed their fingers at the suspect, accusing him of the crime.',
		pastTranslation: 'Apuntaron con el dedo al sospechoso, acusándolo del crimen.',
		pastParticiple: 'He has pointed to the need for more funding for education.',
		pastParticipleTranslation: 'Ha señalado la necesidad de más financiamiento para la educación.',
		gerund: 'Pointing out mistakes can help us learn and improve.',
		gerundTranslation: 'Señalar errores puede ayudarnos a aprender y mejorar.',
	},
	{
		verb: 'To practice',
		verbo: 'practicar',
		infinitive: 'She practices yoga every morning to start her day off right.',
		infinitiveTranslation: 'Practica yoga todas las mañanas para empezar bien el día.',
		present: 'He practices his guitar skills for an hour every day.',
		presentTranslation: 'Practica sus habilidades con la guitarra durante una hora todos los días.',
		past: 'They practiced their lines for the play until they had them memorized.',
		pastTranslation: 'Practicaron sus líneas para la obra hasta que las memorizaron.',
		pastParticiple: 'She has practiced meditation for years and finds it very beneficial.',
		pastParticipleTranslation: 'Ha practicado meditación durante años y encuentra que es muy beneficiosa.',
		gerund: 'Practicing a skill regularly can lead to mastery and success.',
		gerundTranslation: 'Practicar una habilidad regularmente puede llevar a la maestría y el éxito.',
	},
	{
		verb: 'To push',
		verbo: 'empujar',
		infinitive: 'He pushed the door open with his foot because his hands were full.',
		infinitiveTranslation: 'Empujó la puerta con el pie porque tenía las manos ocupadas.',
		present: 'She pushes herself to be the best she can be in everything she does.',
		presentTranslation: 'Se esfuerza por ser lo mejor que pueda ser en todo lo que hace.',
		past: 'They pushed their car to the gas station when it ran out of fuel.',
		pastTranslation: 'Empujaron su auto hasta la gasolinera cuando se quedó sin combustible.',
		pastParticiple: 'He has pushed through difficult times by staying positive and focused.',
		pastParticipleTranslation: 'Ha superado tiempos difíciles manteniéndose positivo y enfocado.',
		gerund: 'Pushing yourself to try new things can lead to personal growth and development.',
		gerundTranslation:
			'Empujarse a sí mismo para probar cosas nuevas puede conducir al crecimiento y desarrollo personal.',
	},
	{
		verb: 'To rain',
		verbo: 'llover',
		infinitive: 'It started to rain just as we left the house.',
		infinitiveTranslation: 'Empezó a llover justo cuando salimos de la casa.',
		present: 'It often rains in this part of the country.',
		presentTranslation: 'A menudo llueve en esta parte del país.',
		past: 'It rained all day yesterday, so we stayed indoors.',
		pastTranslation: 'Llovió todo el día de ayer, así que nos quedamos adentro.',
		pastParticiple: 'The roads were flooded after the heavy rain we had last night.',
		pastParticipleTranslation: 'Las carreteras estaban inundadas después de la fuerte lluvia que tuvimos anoche.',
		gerund: "It's raining outside, so we'll need an umbrella to go out.",
		gerundTranslation: 'Está lloviendo afuera, así que necesitaremos un paraguas para salir.',
	},
	{
		verb: 'To remember',
		verbo: 'recordar',
		infinitive: 'I always remember to lock the door before I leave the house.',
		infinitiveTranslation: 'Siempre recuerdo cerrar la puerta con llave antes de salir de la casa.',
		present: 'She remembers her childhood fondly, especially the summers she spent at the beach.',
		presentTranslation: 'Recuerda con cariño su infancia, especialmente los veranos que pasó en la playa.',
		past: 'I remembered to bring my umbrella, and I was glad I did when it started raining.',
		pastTranslation: 'Recordé traer mi paraguas, y me alegré de haberlo hecho cuando empezó a llover.',
		pastParticiple: 'He has always remembered the lessons his father taught him.',
		pastParticipleTranslation: 'Siempre ha recordado las lecciones que su padre le enseñó.',
		gerund: 'Remembering to stay calm in stressful situations can be a challenge.',
		gerundTranslation: 'Recordar mantener la calma en situaciones estresantes puede ser un desafío.',
	},
	{
		verb: 'To rent',
		verbo: 'alquilar',
		infinitive: 'They decided to rent a car for their road trip across the country.',
		infinitiveTranslation: 'Decidieron alquilar un coche para su viaje por carretera a través del país.',
		present: "We're currently renting an apartment until we can afford to buy a house.",
		presentTranslation:
			'Actualmente estamos alquilando un apartamento hasta que podamos permitirnos comprar una casa.',
		past: 'They rented a beach house for a week and had a wonderful time.',
		pastTranslation: 'Alquilaron una casa de playa durante una semana y lo pasaron genial.',
		pastParticiple: 'She has rented out her spare room to a student for the past year.',
		pastParticipleTranslation: 'Ha alquilado su habitación libre a un estudiante durante el último año.',
		gerund: 'Renting furniture is a great option for people who move frequently.',
		gerundTranslation: 'Alquilar muebles es una gran opción para personas que se mudan con frecuencia.',
	},
	{
		verb: 'To repeat',
		verbo: 'repetir',
		infinitive: 'He wants to repeat the course next semester.',
		infinitiveTranslation: 'Quiere repetir el curso el próximo semestre.',
		present: "I repeat this mantra to calm myself down when I'm stressed.",
		presentTranslation: 'Repito este mantra para calmarme cuando estoy estresado.',
		past: 'They repeated the same mistake over and over again.',
		pastTranslation: 'Repetían el mismo error una y otra vez.',
		pastParticiple: 'She has repeated that story so many times, I could recite it myself.',
		pastParticipleTranslation: 'Ha repetido esa historia tantas veces que yo mismo podría recitarla.',
		gerund: 'Repeating a task several times can help with memorization.',
		gerundTranslation: 'Repetir una tarea varias veces puede ayudar con la memorización.',
	},
	{
		verb: 'To resist',
		verbo: 'resistir',
		infinitive: 'She tries to resist the urge to check her phone during class.',
		infinitiveTranslation: 'Intenta resistir la tentación de revisar su teléfono durante la clase.',
		present: "He resists the temptation to eat junk food, even when he's craving it.",
		presentTranslation: 'Resiste la tentación de comer comida chatarra, incluso cuando lo está deseando.',
		past: 'They resisted the pressure to conform and stuck to their own beliefs.',
		pastTranslation: 'Resistieron la presión para conformarse y se aferraron a sus propias creencias.',
		pastParticiple: "She has resisted change for so long that she's now stuck in her ways.",
		pastParticipleTranslation: 'Ha resistido el cambio durante tanto tiempo que ahora está atrapada en sus formas.',
		gerund: 'Resisting temptation is a key part of building self-discipline.',
		gerundTranslation: 'Resistir la tentación es una parte clave para desarrollar la autodisciplina.',
	},
	{
		verb: 'To show',
		verbo: 'mostrar',
		infinitive: "He wants to show his parents how much he's improved since starting school.",
		infinitiveTranslation: 'Quiere mostrarle a sus padres cuánto ha mejorado desde que empezó la escuela.',
		present: 'She shows a lot of potential in her new job.',
		presentTranslation: 'Muestra mucho potencial en su nuevo trabajo.',
		past: 'They showed up late to the meeting because of traffic.',
		pastTranslation: 'Llegaron tarde a la reunión debido al tráfico.',
		pastParticiple: 'She has shown great leadership skills in her role as manager.',
		pastParticipleTranslation: 'Ha mostrado grandes habilidades de liderazgo en su papel como gerente.',
		gerund: 'Showing appreciation for your coworkers can improve team morale.',
		gerundTranslation: 'Mostrar aprecio por tus compañeros de trabajo puede mejorar la moral del equipo.',
	},
	{
		verb: 'To smoke',
		verbo: 'fumar',
		infinitive: "He doesn't smoke anymore, he quit last year.",
		infinitiveTranslation: 'Ya no fuma, lo dejó el año pasado.',
		present: 'She smokes a pack a day and is trying to quit.',
		presentTranslation: 'Fuma una cajetilla al día y está tratando de dejarlo.',
		past: 'He smoked for many years before he finally quit.',
		pastTranslation: 'Fumó durante muchos años antes de dejarlo finalmente.',
		pastParticiple: 'The air was thick with smoke from the burning building.',
		pastParticipleTranslation: 'El aire estaba espeso con humo del edificio en llamas.',
		gerund: 'Smoking is harmful to your health and can cause many diseases.',
		gerundTranslation: 'Fumar es perjudicial para la salud y puede causar muchas enfermedades.',
	},
	{
		verb: 'To start',
		verbo: 'empezar',
		infinitive: 'He wants to start a business of his own.',
		infinitiveTranslation: 'Quiere iniciar su propio negocio.',
		present: 'She starts work at 9am every day.',
		presentTranslation: 'Empieza a trabajar a las 9 de la mañana todos los días.',
		past: 'He started his career as a teacher and later became a writer.',
		pastTranslation: 'Comenzó su carrera como profesor y más tarde se convirtió en escritor.',
		pastParticiple: 'The engine started after a few tries.',
		pastParticipleTranslation: 'El motor arrancó después de algunos intentos.',
		gerund: 'Starting a new project can be both exciting and challenging.',
		gerundTranslation: 'Comenzar un nuevo proyecto puede ser emocionante y desafiante.',
	},
	{
		verb: 'To stay',
		verbo: 'quedarse',
		infinitive: 'She decided to stay home and watch a movie.',
		infinitiveTranslation: 'Decidió quedarse en casa y ver una película.',
		present: 'They stay at a different hotel every time they travel.',
		presentTranslation: 'Se quedan en un hotel diferente cada vez que viajan.',
		past: 'He stayed in Paris for a week and visited all the major tourist attractions.',
		pastTranslation: 'Se quedó en París durante una semana y visitó todas las principales atracciones turísticas.',
		pastParticiple: 'The hotel offers a stay of three nights for the price of two.',
		pastParticipleTranslation: 'El hotel ofrece una estadía de tres noches por el precio de dos.',
		gerund: 'Staying active is important for maintaining good health.',
		gerundTranslation: 'Mantenerse activo es importante para mantener una buena salud.',
	},
	{
		verb: 'To stop',
		verbo: 'parar',
		infinitive: 'He stopped to catch his breath after running for so long.',
		infinitiveTranslation: 'Se detuvo para recuperar el aliento después de correr por tanto tiempo.',
		present: 'I stop by the coffee shop every morning for a latte.',
		presentTranslation: 'Paso por la cafetería todas las mañanas para tomar un latte.',
		past: 'The police officer stopped the car for speeding.',
		pastTranslation: 'El oficial de policía detuvo el coche por exceso de velocidad.',
		pastParticiple: 'She has stopped eating red meat for health reasons.',
		pastParticipleTranslation: 'Ha dejado de comer carne roja por razones de salud.',
		gerund: 'Stopping to rest during a hike can be very refreshing.',
		gerundTranslation: 'Detenerse a descansar durante una caminata puede ser muy refrescante.',
	},
	{
		verb: 'To study',
		verbo: 'estudiar',
		infinitive: 'He wants to study architecture in college.',
		infinitiveTranslation: 'Quiere estudiar arquitectura en la universidad.',
		present: 'She studies for her exams for hours every day.',
		presentTranslation: 'Estudia para sus exámenes durante horas todos los días.',
		past: 'He studied abroad in Spain for a semester in college.',
		pastTranslation: 'Estudió en el extranjero en España durante un semestre en la universidad.',
		pastParticiple: 'She has studied French for several years and is fluent.',
		pastParticipleTranslation: 'Ha estudiado francés durante varios años y es fluida.',
		gerund: 'Studying different cultures can be a fascinating experience.',
		gerundTranslation: 'Estudiar diferentes culturas puede ser una experiencia fascinante.',
	},
	{
		verb: 'To talk',
		verbo: 'hablar',
		infinitive: 'We need to talk about the upcoming project and make a plan.',
		infinitiveTranslation: 'Tenemos que hablar sobre el próximo proyecto y hacer un plan.',
		present: 'She talks on the phone with her sister every day.',
		presentTranslation: 'Habla por teléfono con su hermana todos los días.',
		past: 'He talked to the manager about getting a promotion.',
		pastTranslation: 'Habló con el gerente sobre obtener un ascenso.',
		pastParticiple: 'She has talked to her boss about taking time off for a vacation.',
		pastParticipleTranslation: 'Ha hablado con su jefe sobre tomarse un tiempo libre para unas vacaciones.',
		gerund: 'Talking to strangers can sometimes be intimidating.',
		gerundTranslation: 'Hablar con desconocidos a veces puede ser intimidante.',
	},
	{
		verb: 'To travel',
		verbo: 'viajar',
		infinitive: 'I want to travel the world and experience different cultures.',
		infinitiveTranslation: 'Quiero viajar por el mundo y experimentar diferentes culturas.',
		present: 'She travels for work almost every week.',
		presentTranslation: 'Viaja por trabajo casi todas las semanas.',
		past: 'We traveled to Europe last summer and had an amazing time.',
		pastTranslation: 'Viajamos a Europa el verano pasado y la pasamos increíble.',
		pastParticiple: 'He has traveled to over 20 countries in his lifetime.',
		pastParticipleTranslation: 'Ha viajado a más de 20 países en su vida.',
		gerund: 'Traveling can broaden your horizons and help you grow as a person.',
		gerundTranslation: 'Viajar puede ampliar tus horizontes y ayudarte a crecer como persona.',
	},
	{
		verb: 'To try',
		verbo: 'intentar',
		infinitive: 'I will try my best to finish the project on time.',
		infinitiveTranslation: 'Haré todo lo posible para terminar el proyecto a tiempo.',
		present: 'She tries to eat healthy and exercise regularly.',
		presentTranslation: 'Intenta comer saludable y hacer ejercicio regularmente.',
		past: 'He tried to fix the car himself, but ended up making it worse.',
		pastTranslation: 'Intentó arreglar el auto por sí mismo, pero terminó empeorando la situación.',
		pastParticiple: "Have you ever tried sushi? It's delicious!",
		pastParticipleTranslation: '¿Alguna vez has probado sushi? ¡Es delicioso!',
		gerund: 'Trying new things can be scary, but it can also lead to growth and new opportunities.',
		gerundTranslation:
			'Probar cosas nuevas puede ser aterrador, pero también puede conducir al crecimiento y nuevas oportunidades.',
	},
	{
		verb: 'To turn',
		verbo: 'girar',
		infinitive: "Don't forget to turn off the lights before you leave.",
		infinitiveTranslation: 'No olvides apagar las luces antes de irte.',
		present: 'He turns the music down when he needs to focus.',
		presentTranslation: 'Baja el volumen de la música cuando necesita concentrarse.',
		past: 'They turned the corner and saw the most beautiful sunset they had ever seen.',
		pastTranslation: 'Doblaron la esquina y vieron la puesta de sol más hermosa que habían visto.',
		pastParticiple: 'The company has turned a profit every year since it was founded.',
		pastParticipleTranslation: 'La empresa ha obtenido beneficios todos los años desde que fue fundada.',
		gerund: 'Turning your passion into a career can lead to a fulfilling and rewarding life.',
		gerundTranslation: 'Convertir tu pasión en una carrera puede llevar a una vida gratificante y satisfactoria.',
	},
	{
		verb: 'To use',
		verbo: 'usar',
		infinitive: 'I need to use the restroom.',
		infinitiveTranslation: 'Necesito usar el baño.',
		present: 'She uses her laptop for work every day.',
		presentTranslation: 'Ella usa su laptop para el trabajo todos los días.',
		past: 'He used to play basketball in high school.',
		pastTranslation: 'Solía jugar baloncesto en la escuela secundaria.',
		pastParticiple: 'The company has used this marketing strategy before.',
		pastParticipleTranslation: 'La empresa ha utilizado esta estrategia de marketing antes.',
		gerund: 'Using a computer can make many tasks easier.',
		gerundTranslation: 'Usar una computadora puede hacer muchas tareas más fáciles.',
	},
	{
		verb: 'To visit',
		verbo: 'visitar',
		infinitive: 'I want to visit my grandmother in the hospital.',
		infinitiveTranslation: 'Quiero visitar a mi abuela en el hospital.',
		present: 'She visits her parents every weekend.',
		presentTranslation: 'Ella visita a sus padres todos los fines de semana.',
		past: 'We visited several museums during our trip to Europe.',
		pastTranslation: 'Visitamos varios museos durante nuestro viaje a Europa.',
		pastParticiple: 'He has visited many countries in his lifetime.',
		pastParticipleTranslation: 'Ha visitado muchos países en su vida.',
		gerund: 'Visiting new places can broaden your perspective.',
		gerundTranslation: 'Visitar lugares nuevos puede ampliar tu perspectiva.',
	},
	{
		verb: 'To wait',
		verbo: 'esperar',
		infinitive: "I can't wait to see the new movie.",
		infinitiveTranslation: 'No puedo esperar para ver la nueva película.',
		present: 'She waits patiently for her turn in line.',
		presentTranslation: 'Ella espera pacientemente su turno en la fila.',
		past: 'We waited for hours to get tickets to the concert.',
		pastTranslation: 'Esperamos durante horas para conseguir boletos para el concierto.',
		pastParticiple: 'He has waited a long time for this opportunity.',
		pastParticipleTranslation: 'Ha esperado mucho tiempo por esta oportunidad.',
		gerund: "Waiting in line can be boring, but it's often necessary.",
		gerundTranslation: 'Esperar en la fila puede ser aburrido, pero a menudo es necesario.',
	},
	{
		verb: 'To walk',
		verbo: 'caminar',
		infinitive: 'She walks to work every day instead of driving.',
		infinitiveTranslation: 'Ella camina al trabajo todos los días en lugar de conducir.',
		present: 'I walk my dog in the park every morning.',
		presentTranslation: 'Paseo a mi perro en el parque todas las mañanas.',
		past: "He walked home after the party since he didn't want to drive.",
		pastTranslation: 'Caminó a casa después de la fiesta ya que no quería conducir.',
		pastParticiple: 'She has walked the entire Camino de Santiago pilgrimage route.',
		pastParticipleTranslation: 'Ha caminado toda la ruta del peregrinaje del Camino de Santiago.',
		gerund: 'Walking is a great form of exercise and can improve overall health.',
		gerundTranslation: 'Caminar es una excelente forma de ejercicio y puede mejorar la salud en general.',
	},
	{
		verb: 'To want',
		verbo: 'querer',
		infinitive: 'She wants to learn how to play the guitar.',
		infinitiveTranslation: 'Ella quiere aprender a tocar la guitarra.',
		present: 'I want a cup of coffee to wake me up.',
		presentTranslation: 'Quiero una taza de café para despertarme.',
		past: 'He wanted to go to the party but had to work late.',
		pastTranslation: 'Quería ir a la fiesta pero tuvo que trabajar hasta tarde.',
		pastParticiple: 'She has always wanted to visit Paris.',
		pastParticipleTranslation: 'Siempre ha querido visitar París.',
		gerund: 'Wanting something can drive motivation and action.',
		gerundTranslation: 'Querer algo puede impulsar la motivación y la acción.',
	},
	{
		verb: 'To wash',
		verbo: 'lavar',
		infinitive: 'She needs to wash the dishes before she goes to bed.',
		infinitiveTranslation: 'Necesita lavar los platos antes de acostarse.',
		present: 'I wash my car every Saturday morning.',
		presentTranslation: 'Lavo mi auto todos los sábados por la mañana.',
		past: 'He washed his clothes at the laundromat because his washing machine was broken.',
		pastTranslation: 'Lavó su ropa en la lavandería porque su lavadora estaba rota.',
		pastParticiple: 'She has washed the windows and they look so much cleaner now.',
		pastParticipleTranslation: 'Ha lavado las ventanas y ahora se ven mucho más limpias.',
		gerund: 'Washing your hands regularly is important for preventing the spread of germs.',
		gerundTranslation: 'Lavarse las manos regularmente es importante para prevenir la propagación de gérmenes.',
	},
	{
		verb: 'To wish',
		verbo: 'desear',
		infinitive: 'She wishes to travel to Japan someday.',
		infinitiveTranslation: 'Ella desea viajar a Japón algún día.',
		present: 'He wishes he had more time to spend with his family.',
		presentTranslation: 'Él desearía tener más tiempo para pasar con su familia.',
		past: 'I wished for a new bicycle every year when I was a child.',
		pastTranslation: 'Deseaba una bicicleta nueva cada año cuando era niño.',
		pastParticiple: 'She has wished for peace in the world since she was young.',
		pastParticipleTranslation: 'Ha deseado paz en el mundo desde que era joven.',
		gerund: 'Wishing for things can sometimes distract us from enjoying what we have.',
		gerundTranslation: 'Desear cosas a veces nos puede distraer de disfrutar lo que tenemos.',
	},
	{
		verb: 'To work',
		verbo: 'trabajar',
		infinitive: 'I work as a teacher at a local school.',
		infinitiveTranslation: 'Trabajo como maestro en una escuela local.',
		present: 'He works long hours at his job to provide for his family.',
		presentTranslation: 'Trabaja largas horas en su trabajo para proveer a su familia.',
		past: 'I worked in retail for several years before changing careers.',
		pastTranslation: 'Trabajé en venta al por menor durante varios años antes de cambiar de carrera.',
		pastParticiple: 'She has worked hard to become a successful entrepreneur.',
		pastParticipleTranslation: 'Ha trabajado duro para convertirse en una emprendedora exitosa.',
		gerund: 'Working on a project with a team can be both challenging and rewarding.',
		gerundTranslation: 'Trabajar en un proyecto con un equipo puede ser desafiante y gratificante.',
	},
];
