export default [
    "inaccurate / accurate",
    "bad / good",
    "ugly / beautiful",
    "little / big",
    "small / big",
    "uncertain / certain",
    "expensive / cheap",
    "dirty / clean",
    "unclear / clear",
    "hot / cold",
    "uncomfortable / comfortable",
    "uncommon / common",
    "incomplete / complete",
    "inconvenient / convenient",
    "warm / cool",
    "incorrect / correct",
    "safe / dangerous",
    "light / dark",
    "shallow / deep",
    "independent / dependent",
    "same / different",
    "easy / difficult",
    "indirect / direct",
    "wet / dry",
    "late / early",
    "west / east",
    "full / empty",
    "unfair / fair",
    "unfamiliar / familiar",
    "slow / fast",
    "thin / fat",
    "last / first",
    "sad / happy",
    "unhappy / happy",
    "easy / hard",
    "soft / hard",
    "ill / hard",
    "sick / healthy",
    "unhealthy / healthy",
    "light / heavy",
    "low / high",
    "unimportant / important",
    "stupid / intelligent",
    "boring / interesting",
    "unkind / kind",
    "small / large",
    "little / large",
    "unlawful / lawful",
    "illegal / legal",
    "illogical / logical",
    "short / long",
    "neat / messy",
    "old-fashioned / modern",
    "wide / narrow",
    "far / near",
    "unnecessary / necessary",
    "quiet / noisy",
    "abnormal / normal",
    "south / north",
    "new / old",
    "young / old",
    "close / open",
    "unpleasant / pleasant",
    "rude / polite",
    "rich / poor",
    "impossible / possible",
    "public / private",
    "improper / proper",
    "irrational / rational",
    "unreal / real",
    "irregular / regular",
    "irresponsible / responsible",
    "left / right",
    "wrong / right",
    "smooth / rough",
    "tall / short",
    "sweet / sour",
    "weak / strong",
    "unsure / sure",
    "false / true",
    "unusual / usual",
    "invisible / visible"
]
// export default [
//     "inaccurate",
//     "good",
//     "ugly",
//     "small",
//     "uncertain",
//     "expensive",
//     "dirty",
//     "unclear",
//     "hot",
//     "uncomfortable",
//     "uncommon",
//     "incomplete",
//     "inconvenient",
//     "warm",
//     "incorrect",
//     "safe",
//     "light",
//     "shallow",
//     "independent",
//     "same",
//     "easy",
//     "indirect",
//     "wet",
//     "late",
//     "west",
//     "full",
//     "unfair",
//     "unfamiliar",
//     "slow",
//     "thin",
//     "last",
//     "sad",
//     "easy",
//     "unhealthy",
//     "light",
//     "low",
//     "unimportant",
//     "stupid",
//     "boring",
//     "unkind",
//     "unlawful",
//     "small",
//     "illegal",
//     "illogical",
//     "short",
//     "neat",
//     "old-fashioned",
//     "wide",
//     "far",
//     "unnecessary",
//     "quiet",
//     "abnormal",
//     "south",
//     "new",
//     "close",
//     "unpleasant",
//     "rude",
//     "rich",
//     "impossible",
//     "public",
//     "improper",
//     "irrational",
//     "unreal",
//     "irregular",
//     "irresponsible",
//     "left",
//     "smooth",
//     "tall",
//     "sweet",
//     "weak",
//     "unsure",
//     "false",
//     "unusual",
//     "invisible",
// ]